project:
  type: website

website:
  title: "Data_Analysis_II_Notes"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - 1_Types_of_Categoricals.qmd
      - 2_Props_Risks_Odds.qmd
      - 3_Logistic_Regression_I.qmd
      - 4_Logistic_Regression_II.qmd
      - 5_Log_linear_Regression.qmd
      - 6_Dispersion_Zero_Inflation.qmd
      - 7_Random_Effects.qmd
      - 8_Evaluating_Models.qmd
      - 9_Imp_Pred_Validate.qmd
      - 10_Final_Project.qmd
      - text: "Labs"
        menu: 
          - z0_learnR.qmd
          - z1_learnR.qmd
          - z2_learnR.qmd
          - z3_learnR.qmd
          - z4_learnR.qmd
          - z5_learnR.qmd
          - z6_learnR.qmd
          - z7_learnR.qmd
          - z8_learnR.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      sidebar-width: 50px
      margin-width: 150px
      body-width: 1100px
    df-print: kable




