---
title: Reference
---


[Gradescope](https:\\www.gradescope.com)

[Lectures](C:\\Users\\cmeck\\Desktop\\D_Anal\\Anal_II\\_Data_Analysis_II_All_Lectures.pdf)


## Git stuff

**Add, commit, and publish the folder to the github repo**

1. git add .
2. git commit -m “comment”
3. git push origin main

**Set the location of the github repo**

1. git remote set-url origin *url*
2. git remote -v
3. git remote show origin

___

Here are some quarto commands:
    
1. quarto publish gh-pages
2. quarto publish gh-pages document.qmd
3. quarto publish gh-pages --no-prompt

___



    

## Reading list

[Cat Data Anal 3rd](C:\\Users\\cmeck\\Desktop\\Books and References\\Categorical_data_analysis_ed3.pdf)

[Stat. Meth 3rd](https:\\ebookcentral.proquest.com\\lib\\osu\\detail.action?docID=802390)

[Open Stats 4th ed](C:\\Users\\cmeck\\Desktop\\Books and References\\_Open_Intro_Stats.pdf)

[R4DS 1st](https:\\r4ds.had.co.nz\\index.html)


### Extra Reading

[Mathmatical Stats 8th](C:\\Users\\cmeck\\Desktop\\Books and References\\Mathematical Statistics eigth ed.pdf)

[Practical Stats for DS](C:\\Users\\cmeck\\Desktop\\Books and References\\PracticalStatisticsforDataScientists.pdf)



### Module 1

- Categorical Data Analysis, Sections 1.1, 1.2
- Statistical Methods, Section 12.1
- OpenIntro Statistics, Section 6.1
- R for Data Science, Look over Chapters 1, 2, and 3

### Module 2

- Categorical Data Analysis, Sections 1.2, 1.3.
- Statistical Methods, Section 12.2-12.4.
- OpenIntro Statistics, Section 6.2-6.4
- R for Data Science (Lab references Chapter 22)

### Module 3

- Categorical Data Analysis, Sections 4.1, 4.2 (through 4.2.5); 5.1-5.3 (through 5.3.6). Please note: content not in lectures. 
- Statistical Methods, Sections 13.1-13.2.
- OpenIntro Statistics, Section 8.4. and Section 9.5

### Module 4

- Categorical Data Analysis, Sections 4.7, 6.2

### Module 5

- Categorical Data Analysis, Sections 4.3, 9.1 
(through 9.1.3; some of the notation here may be difficult, but it is equivalent to using indicator functions to 
denote different categories).

### Module 6

- An Application of Claim Frequency Data using Zero Inflated and Hurdle Models in General Insurance

### Module 7

- Categorical Data Analysis, Chapter 13, through Section 13.1.4; Section 13.3. Please note: models are given in matrix notation.

### Module 8

- Categorical Data Analysis, Chapter 6, 6.3.1, 6.3.3 and 6.3.4
- OpenIntro Statistics, Section 8.4



## Website


**This is from the github repo creation page**

Push an existing repository from the command line:
    
1. git remote add origin *url*
2. git branch -M main
3. git push -u origin main

___
    
**Setting up the website:**

1. Create a new git repository
2. Create a quarto project website
3. Render the project
4. Add _site & .quarto to the .gitignore file
5. git remote add origin
6. git branch -M main
7. git add .
8. git commit
9. git push
10. refresh github.com/name
11. view all branches -> New -> "gh-pages"
12. settings -> pages -> deploy from gh-pages
13. quarto publish gh-pages

It should work ever after by just typing quarto publish gh-pages. 
There may be a need to get a personal access token at the start. 
I did that my first go around so I'm not sure. 
Sometimes the site doesn't render immediately. You have to wait for it to finish in the actions tab of github. 

