<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data_Analysis_II_Notes - 2 Odds and risks</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data_Analysis_II_Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notes" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notes">    
        <li>
    <a class="dropdown-item" href="./1_Types_of_Categoricals.html" rel="" target="">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_Props_Risks_Odds.html" rel="" target="">
 <span class="dropdown-text">2 Props, Risk &amp; Odds</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./3_Logistic_Regression_I.html" rel="" target="">
 <span class="dropdown-text">3 Log Reg I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./4_Logistic_Regression_II.html" rel="" target="">
 <span class="dropdown-text">4 Log-Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./5_Log_linear_Regression.html" rel="" target="">
 <span class="dropdown-text">5 Log-lin-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./6_Dispersion_Zero_Inflation.html" rel="" target="">
 <span class="dropdown-text">6 Disp &amp; 0 Inflation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./7_Random_Effects.html" rel="" target="">
 <span class="dropdown-text">7 Random_Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./8_Evaluating_Models.html" rel="" target="">
 <span class="dropdown-text">8 Model Eval</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./9_Imp_Pred_Validate.html" rel="" target="">
 <span class="dropdown-text">9 Imp, Pred, Validate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_Final_Project.html" rel="" target="">
 <span class="dropdown-text">10 Final Project</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./z0_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z1_learnR.html" rel="" target="">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z2_learnR.html" rel="" target="">
 <span class="dropdown-text">2 Odds and risks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z3_learnR.html" rel="" target="">
 <span class="dropdown-text">3 Log-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z4_learnR.html" rel="" target="">
 <span class="dropdown-text">4 Log Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z5_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z6_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z7_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z8_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hw" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">HW</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hw">    
        <li>
    <a class="dropdown-item" href="./aHW_1.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_2.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_3.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_4.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_5.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_6.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_7.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_8.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 8</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#load-packages-for-the-lab" id="toc-load-packages-for-the-lab" class="nav-link" data-scroll-target="#load-packages-for-the-lab">Load Packages for the Lab</a></li>
  </ul></li>
  <li><a href="#statistical-independence" id="toc-statistical-independence" class="nav-link" data-scroll-target="#statistical-independence">Statistical Independence</a>
  <ul class="collapse">
  <li><a href="#statistical-independence-for-contingency-tables" id="toc-statistical-independence-for-contingency-tables" class="nav-link" data-scroll-target="#statistical-independence-for-contingency-tables">Statistical Independence for Contingency Tables</a></li>
  <li><a href="#plots" id="toc-plots" class="nav-link" data-scroll-target="#plots">Plots</a></li>
  </ul></li>
  <li><a href="#chi-squared-statistic" id="toc-chi-squared-statistic" class="nav-link" data-scroll-target="#chi-squared-statistic">Chi-Squared Statistic</a></li>
  <li><a href="#chi-squared-test-of-association" id="toc-chi-squared-test-of-association" class="nav-link" data-scroll-target="#chi-squared-test-of-association">Chi-squared Test (of association)</a>
  <ul class="collapse">
  <li><a href="#standard-case-large-sample-size" id="toc-standard-case-large-sample-size" class="nav-link" data-scroll-target="#standard-case-large-sample-size">Standard Case (large sample size)</a></li>
  </ul></li>
  <li><a href="#sampling-randomization-and-small-sample-inference" id="toc-sampling-randomization-and-small-sample-inference" class="nav-link" data-scroll-target="#sampling-randomization-and-small-sample-inference">Sampling, Randomization, and Small-Sample Inference</a>
  <ul class="collapse">
  <li><a href="#data-lady-tasting-tea" id="toc-data-lady-tasting-tea" class="nav-link" data-scroll-target="#data-lady-tasting-tea">Data: Lady Tasting Tea</a></li>
  <li><a href="#parametric-bootstrapping" id="toc-parametric-bootstrapping" class="nav-link" data-scroll-target="#parametric-bootstrapping">Parametric bootstrapping</a></li>
  <li><a href="#sampling-models-optional" id="toc-sampling-models-optional" class="nav-link" data-scroll-target="#sampling-models-optional">Sampling Models (Optional)</a>
  <ul class="collapse">
  <li><a href="#unrestricted-sampling" id="toc-unrestricted-sampling" class="nav-link" data-scroll-target="#unrestricted-sampling">Unrestricted Sampling</a></li>
  <li><a href="#total-sample-size-fixed" id="toc-total-sample-size-fixed" class="nav-link" data-scroll-target="#total-sample-size-fixed">Total Sample Size Fixed</a></li>
  <li><a href="#one-margin-fixed" id="toc-one-margin-fixed" class="nav-link" data-scroll-target="#one-margin-fixed">One Margin Fixed</a></li>
  <li><a href="#both-margins-fixed" id="toc-both-margins-fixed" class="nav-link" data-scroll-target="#both-margins-fixed">Both Margins Fixed</a></li>
  </ul></li>
  <li><a href="#examples-of-re-sampling-lady-tasting-tea" id="toc-examples-of-re-sampling-lady-tasting-tea" class="nav-link" data-scroll-target="#examples-of-re-sampling-lady-tasting-tea">Examples of Re-sampling: Lady Tasting Tea</a></li>
  <li><a href="#beyond-fixed-margins" id="toc-beyond-fixed-margins" class="nav-link" data-scroll-target="#beyond-fixed-margins">Beyond Fixed Margins</a></li>
  <li><a href="#beyond-2-x-2-tables" id="toc-beyond-2-x-2-tables" class="nav-link" data-scroll-target="#beyond-2-x-2-tables">Beyond 2 x 2 Tables</a></li>
  </ul></li>
  <li><a href="#lab-2" id="toc-lab-2" class="nav-link" data-scroll-target="#lab-2">Lab 2</a>
  <ul class="collapse">
  <li><a href="#module-2-lab-assignment-instructions" id="toc-module-2-lab-assignment-instructions" class="nav-link" data-scroll-target="#module-2-lab-assignment-instructions">Module 2 Lab Assignment Instructions</a></li>
  </ul></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions:</a>
  <ul class="collapse">
  <li><a href="#q1." id="toc-q1." class="nav-link" data-scroll-target="#q1.">Q1.</a></li>
  <li><a href="#q2." id="toc-q2." class="nav-link" data-scroll-target="#q2.">Q2.</a></li>
  <li><a href="#q3." id="toc-q3." class="nav-link" data-scroll-target="#q3.">Q3.</a></li>
  <li><a href="#q4." id="toc-q4." class="nav-link" data-scroll-target="#q4.">Q4.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2 Odds and risks</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="overview" class="level1">
<h1>Overview</h1>
<p>In the previous lab, we showed how to produce descriptive statistics that quantify relationships between categorical variables observed on a given sample. No formal attempt was made to extend conclusions <em>beyond</em> the sample. In this lab, we will explore methods for making inference about the association between two categorical variables in a larger population of interest. The usual caveats apply, including but not limited to:</p>
<ol type="1">
<li><p>These methods cannot be interpreted <em>in a straightforward way</em> unless the data are an independent sample from a well-defined population of interest, obtained using a probability (random) mechanism.</p></li>
<li><p>These methods are not necessarily robust to extreme outliers or large quantities of missing data. Intending to do inference does not eliminate the need for exploratory checks on data quality.</p></li>
<li><p>The probabilistic “guarantees” attached to these inferential methods do <em>not</em> hold in the context of using the same data to generate hypotheses and test them. See <a href="http://r4ds.had.co.nz/model-intro.html">R for Data Science, Chapter 22</a> for advice about using “holdout data” when you’re serious about formal inference.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Notation for I x J Tables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Here is a glossary of terms and notation that we’ll use throughout the lab (and the course).</p>
<p>Mathematical expressions are formatted with dollar signs for improved appearance in the HTML document. When reading the .Rmd script, in RStudio, moving your cursor over something between dollar signs “pops out” the formatted mathematical expression from that location on the screen.</p>
<ul>
<li><span class="math inline">\(I\)</span> denotes the number of rows in a 2-way table of counts, <span class="math inline">\(J\)</span> denotes the number of columns</li>
<li><span class="math inline">\(X\)</span> denotes the “row variable” – a categorical random variable (factor) taking on I possible values <span class="math inline">\(x_1, ..., x_I\)</span></li>
<li><span class="math inline">\(Y\)</span> denotes the “column variable” – a categorical random variable taking on <span class="math inline">\(J\)</span> possible values <span class="math inline">\(y_1,...,y_J\)</span></li>
<li>The <strong>cells</strong> in a 2-way table are indexed by <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, where <span class="math inline">\(i\)</span> in <span class="math inline">\(1:I\)</span> is the row index and <span class="math inline">\(j\)</span> in <span class="math inline">\(1:J\)</span> is the column index</li>
<li><span class="math inline">\(N\)</span> is the total count over the whole table, and <span class="math inline">\(n_{ij}\)</span> is the count in the <span class="math inline">\(i,j\)</span> cell. That is, the number of observation for which <span class="math inline">\(X = x_i\)</span> and <span class="math inline">\(Y = y_j\)</span></li>
<li><span class="math inline">\(p_{ij}\)</span> is the proportion, out of the N observations, which fall in the <span class="math inline">\(i,j\)</span> cell (so <span class="math inline">\(p_{ij} = n_{ij}/N\)</span>)</li>
<li><span class="math inline">\(p_i.\)</span> is the ith row proportion, and <span class="math inline">\(p._j\)</span> the <span class="math inline">\(j\)</span>th column proportion – the . notation suggests that we’ve summed over/collapsed the index it replaces</li>
</ul>
</div>
</div>
</div>
<section id="load-packages-for-the-lab" class="level2">
<h2 class="anchored" data-anchor-id="load-packages-for-the-lab">Load Packages for the Lab</h2>
<p>We’ll use the following packages in this lab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="statistical-independence" class="level1">
<h1>Statistical Independence</h1>
<p>Recall that two random variables, X and Y, are independent if they are uninformative about one another in terms of the probability of occurrence of specific outcomes. For example, if we roll two fair dice, one after the other, the outcome on the first roll in no way changes any of the probabilities having to do with the outcome on the second roll. We say, therefore, that the two outcomes are statistically independent.</p>
<p>In terms of the mathematics of probabilities,</p>
<blockquote class="blockquote">
<p>Random variables X and Y are independent &lt;=&gt; P(X,Y) = P(X)P(Y)</p>
</blockquote>
<p>(The &lt;=&gt; signifies logical equivalence)</p>
<p>In words, this expression means that X and Y are independent if and only if the <strong>joint probability</strong>, <span class="math inline">\(P(X,Y)\)</span> [i.e., <span class="math inline">\(P(X = x, Y = y)\)</span>], is the product of the <strong>marginal probabilities</strong>, <span class="math inline">\(P(X = x)\)</span> and <span class="math inline">\(P(Y = y)\)</span>.</p>
<p>Independence can also be characterized in terms of <strong>conditional probabilities</strong>: <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if <span class="math inline">\(P(X|Y) = P(X)\)</span>. In words, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if the conditional probability of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y\)</span> is the same as the marginal probability of <span class="math inline">\(X\)</span> without knowing <span class="math inline">\(Y\)</span>.</p>
<p>It’s important to understand here that the independence relation that we’ve just described is a property of the underlying population distribution of the random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. When we’re given a sample from such a population, in the form of an <span class="math inline">\(I \times J\)</span> contingency table, we have to think about the <em>evidence</em> that table contains for the independence relation <em>in the population</em>.</p>
<section id="statistical-independence-for-contingency-tables" class="level2">
<h2 class="anchored" data-anchor-id="statistical-independence-for-contingency-tables">Statistical Independence for Contingency Tables</h2>
<p>In terms of the sample proportions that we can estimate from an <span class="math inline">\(I \times J\)</span> contingency table, the independence relation is (check the Notation Section above):</p>
<p><span class="math display">\[p_{ij} = p_i.p._j\]</span></p>
<p>In words: the cell probability for the <span class="math inline">\(i,j\)</span> cell is equal to the marginal probability of the <span class="math inline">\(i^{th}\)</span> row times the marginal probability of the <span class="math inline">\(j^{th}\)</span> column.</p>
<p>Because we don’t know the underlying joint probability distribution that leads to a specific, observed contingency table, we can only evaluate the independence assumption on the basis of the sample independence relation, <span class="math inline">\(p_ij = p_i.p._j\)</span>. We say that a contingency table is the <em>most consistent</em> with statistical independence if <span class="math inline">\(p_{ij} = p_i.p._j\)</span> for all <span class="math inline">\(i,j\)</span>. And, the extent to which the observed counts in a table deviate from <span class="math inline">\(p_{ij} = p_i.p._j\)</span> for all <span class="math inline">\(i,j\)</span> provides us with evidence against the statistical independence hypothesis.</p>
</section>
<section id="plots" class="level2">
<h2 class="anchored" data-anchor-id="plots">Plots</h2>
<p>You can use mosaic plots to get a sense for the independence or lack of independence in <span class="math inline">\(I \times J\)</span> tables. In general, when the two variables of an <span class="math inline">\(I \times J\)</span> table are independent, then the vertical splits in the mosaic plot of that table should (approximately) line up. Actually, depending on the complexity of the mosaic plot, it may be that you’re looking for the horizontal splits to line up, but in the examples here, it’s the vertical splits.</p>
<p>Run the following chunk of R code to see some examples.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Approximately independent </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a> tab1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">14</span>,<span class="dv">35</span>,<span class="dv">12</span>),<span class="dv">3</span>,<span class="dv">2</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">mosaic</span>(tab1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probably not independent</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a> tab2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">10</span>,<span class="dv">14</span>,<span class="dv">50</span>,<span class="dv">35</span>,<span class="dv">12</span>),<span class="dv">3</span>,<span class="dv">2</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">mosaic</span>(tab2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Intuitively, the closer the vertical splits are to being aligned, the closer the observed table of counts will be to the expected table of counts. You can play around with adjusting the cell counts in the code above give yourself a better understanding of the mosaic plot as a tool for evaluating statistical independence visually.</p>
<p>A closely-related visualization is the sieve plot, which first draws the outline of the mosaic plot that we would expect to see under the assumption of independence (i.e., with the splits lined up). It then fills in each cell of this outline with a grid of squares, scaled so that <span class="math inline">\(n_{ij}\)</span> squares fit within the <span class="math inline">\(ij^{th}\)</span> cell. Thus, cells with bigger-than-expected counts are filled with denser grids, and cells with smaller-than-expected counts are filled with sparser grids. For extra clarity, the “underfilled” cells are shaded red and the “overfilled” cells shaded blue.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Approximately independent </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">sieve</span>(tab1, <span class="at">shade =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probably not independent</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">sieve</span>(tab2, <span class="at">shade =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The grid sizes on the first sieve plot are approximately the same, indicating independence; whereas the grid sizes on the second plot are different, indicating a departure from independence.</p>
</section>
</section>
<section id="chi-squared-statistic" class="level1">
<h1>Chi-Squared Statistic</h1>
<p>We hope that you remember from your introductory statistics course that the Chi-Squared test is one way to test the independence of two variables in an <span class="math inline">\(I \times J\)</span> contingency table. The essential idea behind the test is this:</p>
<ol type="1">
<li><p>We create (well, the computer does it for us) a table of “expected counts,” or the counts that we would <em>expect</em> to see based on the margin and table totals, <strong>if</strong> the two variables were actually independent.</p></li>
<li><p>We compare this expected table to the observed table (using the <span class="math inline">\(\chi^2\)</span> statistic).</p></li>
<li><p>If the observed and expected tables are far apart, we take this as evidence against the (null) hypothesis of independence.</p></li>
</ol>
<p>The <strong>chi-squared statistic</strong> sums the quantity <span class="math inline">\((O_{ij} - E_{ij})^2 / E_{ij}\)</span> over every cell of the table, where for the <span class="math inline">\(i,j\)</span>th cell, <span class="math inline">\(O_{ij} = n_{ij}\)</span> is the observed cell count, and <span class="math inline">\(E_{ij} = p_i.p._jN\)</span> is the expected count from the expected table (again, to re-emphasize: it’s the expected table <em>under</em> the hypothesized assumption of independence between the two variables, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>).</p>
<p>The following chunk of R code builds a function, called <code>chisq_stat0()</code>, that calculates the chi-squared statistic. This function is almost superfluous, since the calculation of the chi-squared statistic is already built into a function in R that performs the chi-squared test. Nevertheless, we’re creating this function as illustrative of the relatively simple calculations, and because we’ll actually need this variation to perform a simulation later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>chisq_stat0 <span class="ot">&lt;-</span><span class="cf">function</span>(tbl, <span class="at">smooth =</span> <span class="fl">10e-8</span>){</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a> O <span class="ot">&lt;-</span> tbl <span class="sc">+</span> smooth</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a> N <span class="ot">&lt;-</span> <span class="fu">sum</span>(tbl)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a> E <span class="ot">&lt;-</span> <span class="fu">outer</span>(<span class="fu">rowSums</span>(tbl), (<span class="fu">colSums</span>(tbl)))<span class="sc">%&gt;%</span> <span class="fu">divide_by</span>(N) <span class="co"># this is equivalent to (p_i.)*(p._j)*N</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a> X2 <span class="ot">&lt;-</span> (O <span class="sc">-</span> E) <span class="sc">%&gt;%</span> <span class="fu">raise_to_power</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> <span class="fu">divide_by</span>(E) <span class="sc">%&gt;%</span> <span class="fu">sum</span>() </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">return</span>(X2)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>} </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unlike the built-in R function, this function has a “smooth” argument, which adds a tiny positive value to every cell in the table. For tables with all non-zero counts, this changes the chi-squared statistic barely at all. The smoothing is included to ensure that the chi-squared statistic can always be defined, even if one the rows or one of the columns of a table contains all zeroes. This is a somewhat pathological situation in practice It can occur when we know that there was an additional possible level of a categorical variable, but we happened to not observe that level in the particular sample we have. But when we run a simulation that resamples thousands of times from a table of small counts, such a situation will not-infrequently arise.</p>
<blockquote class="blockquote">
<p>Please note that you should NOT do this smoothing in practice. We are only doing it here so that our simulation will run without interruption. If you ever do encounter a table with one row or column that is all zeroes, you should think carefully about how to proceed.</p>
</blockquote>
</section>
<section id="chi-squared-test-of-association" class="level1">
<h1>Chi-squared Test (of association)</h1>
<p>Now we move into a formal statistical test of independence. Depending on the context of the problem, the <span class="math inline">\(\chi^2\)</span> test is also referred to as a test of association or a test of homogeneity. By calculating the <span class="math inline">\(\chi^2\)</span> statistic, we have a number associated with the deviation from independence for an observed table.</p>
<p>But, how big does that statistic have to be for us to say that we have enough evidence against the independence hypothesis? Could we have obtained a number this large or larger if the row and column variables really were independent? If we’re going to interpret this value statistically, to test the hypothesis of independence, we need a <em>reference distribution</em>.</p>
<p>In what follows, we’ll go through several different cases that depend upon sample size. For large samples (one rule of thumb on samples size holds that “large” means that all cell counts are 5 or larger and the table total is at least 30), the reference distribution is a <span class="math inline">\(\chi^2\)</span> distribution. When the sample size is not large, there is another option for evaluating statistical independence.</p>
<section id="standard-case-large-sample-size" class="level2">
<h2 class="anchored" data-anchor-id="standard-case-large-sample-size">Standard Case (large sample size)</h2>
<p>When the sample size is large, the reference distribution for the chi-squared statistic is a Chi-squared distribution with <span class="math inline">\((I-1) \times (J-1)\)</span> degrees of freedom.</p>
<p>You saw the Berkeley Admissions data in the M1L4 narrated lecture. These data are available in R as the object <code>UCBAdmissions</code>. We’ll use the <code>UCBAdmissions</code> data collapsed over department to consider the independence of admission and gender (we know that department matters here, but using the aggregated table is useful as an illustration).</p>
<p><code>UCBAdmissions</code> stores the data in a 2 x 2 x 6 array, so we’ll first collapse over the third dimension (department) using the <code>margin.table()</code> function, and then perform the <span class="math inline">\(\chi^2\)</span> test. Please run this chunk of R code (if you haven’t already).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(UCBA_sum <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(UCBAdmissions,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Gender
Admit      Male Female
  Admitted 1198    557
  Rejected 1493   1278</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(UCBA_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  UCBA_sum
X-squared = 91.61, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There are several things to notice.</p>
<ol type="1">
<li><p>The R output for the test is titled <code>Pearson's Chi-squared test with Yates' continuity correction</code>. We’ll have some comments about the continuity correction below.</p></li>
<li><p>Notice that the value of <code>X-squared</code>, which is the chi-squared statistic is 91.61, <code>df = 1</code> since <code>UCBA_sum</code> is a 2 x 2 table.</p></li>
<li><p>The p-value associated with this test statistic is very small. We can report it as p &lt; 0.0001. This provides convincing evidence that admission and gender are not independent. Let’s also take a quick look at the mosaic plot:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaic</span>(UCBA_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The vertical split between Male and Female in the Admitted group is substantially farther to the right than the vertical split between Male and Female in the Rejected group. Evidence that the two variables, Admit and Gender, are <em>not</em> independent.</p>
<p>What about the continuity correction? There’s actually quite a bit of data in the <code>UCBAdmissions</code> dataset, with <code>N = 4526</code>. In this case, the continuity correction doesn’t make that much difference. In fact, run the following code and compare the <code>X-squared</code> values and the p-values when <code>correct = TRUE</code> (the default) and when <code>correct = FALSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(UCBA_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  UCBA_sum
X-squared = 91.61, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(UCBA_sum,<span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  UCBA_sum
X-squared = 92.205, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>You should notice that the <code>X-squared</code> value changed a little bit without the continuity correction, but the p-value didn’t change at all. This is fairly typical with <em>really</em> large sample sizes like we have here. The continuity correction doesn’t really make any difference for our inference we still have really strong evidence that admission and gender are not independent.</p>
<p>The continuity correction was introduced to accommodate the use of a continuous probability distribution (the <span class="math inline">\(\chi^2\)</span> distribution) as the reference distribution for a statistic calculated from non-continuous (i.e., categorical) data. Simply put, it makes the performance of the <span class="math inline">\(\chi^2\)</span> statistic better (in terms of type II error) when the sample size is of moderate size. We recommend that you simply use the default, <code>correct = TRUE</code>.</p>
<p>The <span class="math inline">\(\chi^2\)</span> test is also called a test for homogeneity in some situations, and the <code>UCBAdmissions</code> dataset provides a good example. Another way that we could consider the independence (or lack of association) between admission and gender is to ask whether the proportion of males admitted is the same as the proportion of females admitted. Put another way, we ask whether the proportions of admits are the same (homogeneous) between the two groups, males and females:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># transpose the UCBA_sum matrix, so Gender is row the variable:</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>(UCBA_sum2 <span class="ot">&lt;-</span> <span class="fu">t</span>(UCBA_sum))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Admit
Gender   Admitted Rejected
  Male       1198     1493
  Female      557     1278</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform the test for a difference in two proportions: </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(UCBA_sum2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  UCBA_sum2
X-squared = 91.61, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: two.sided
95 percent confidence interval:
 0.1129887 0.1703022
sample estimates:
   prop 1    prop 2 
0.4451877 0.3035422 </code></pre>
</div>
</div>
<p>When you run this R chunk, you see the identical <code>X-squared</code> statistic to what we got from running <code>chisq.test(UCBA_sum)</code>.</p>
<p>You’ll also get some output that tells you about the difference between the two admit proportions. That the 95% confidence interval for the difference in the two proportions, 0.113 to 0.170, does not contain zero is another way for us to communicate that we have strong evidence that the two admit proportions are not the same, i.e.&nbsp;that the two genders are not homogeneous in terms of admissions.</p>
<p>Recall again: simply summarizing this particular dataset using this 2 x 2 table is perilous we know there’s more to the story here. Indeed, if we collapsed over the admission decision to see the total numbers of applicants within each department, we could use the chi-squared test on this table to see that gender-specific application rates are not homogeneous, which suggests that collapsing over the departments could be a problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(UCBApplicants <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(UCBAdmissions, <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Dept
Gender     A   B   C   D   E   F
  Male   825 560 325 417 191 373
  Female 108  25 593 375 393 341</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(UCBApplicants)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  UCBApplicants
X-squared = 1068.4, df = 5, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Nevertheless, it’s been useful to use the summary data for illustrating equivalence between the chi-squared test and the difference in proportions test.</p>
</section>
</section>
<section id="sampling-randomization-and-small-sample-inference" class="level1">
<h1>Sampling, Randomization, and Small-Sample Inference</h1>
<p>When some (or all) of the cell counts are sufficiently small, the distribution of the chi-squared statistic does <em>not</em> follow a Chi-squared distribution very closely at all. We’ll explore this phenomenon in a fairly extreme case, where the cell counts are extremely small.</p>
<section id="data-lady-tasting-tea" class="level2">
<h2 class="anchored" data-anchor-id="data-lady-tasting-tea">Data: Lady Tasting Tea</h2>
<p>The Lady Tasting Tea is a classic (and classically British) example given by Sir Ronald Fisher to motivate the “exact test” which now bears his name. Briefly, in the tea-tasting experiment, a woman was presented with eight cups of tea four of which she knew to have had the tea poured first, and four of which she knew to have had the milk poured first, and she was asked to distinguish which cups had tea first and which had milk first.</p>
<p>The data from this experiment naturally fall into a 2x2 table where one dimension represents the lady’s guesses and the other dimension represents the truth. See the <strong>Examples</strong> in the help file for <code>fisher.test()</code> for a full description of these data.</p>
<blockquote class="blockquote">
<p>There’s also a good book called, not surprisingly, “The Lady Tasting Tea,” by David Salsburg that gives an entertaining early history of Statistics.</p>
</blockquote>
<p>The following R chunk recreates the Lady Tasting Tea data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>TeaTasting <span class="ot">&lt;-</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">nrow =</span> <span class="dv">2</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">Guess =</span> <span class="fu">c</span>(<span class="st">"Milk"</span>, <span class="st">"Tea"</span>),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Truth =</span> <span class="fu">c</span>(<span class="st">"Milk"</span>, <span class="st">"Tea"</span>)))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>TeaTasting</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Truth
Guess  Milk Tea
  Milk    3   1
  Tea     1   3</code></pre>
</div>
</div>
<p>There’s nothing to prevent us from applying the <code>chisq.test()</code> function to the TeaTasting data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(TeaTasting, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(TeaTasting, correct = FALSE): Chi-squared approximation
may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  TeaTasting
X-squared = 2, df = 1, p-value = 0.1573</code></pre>
</div>
</div>
<p>We do get an answer, but also the helpful warning that “Chi-squared approximation may be incorrect.” Why so? (It’s not because we said <code>correct = FALSE</code> the same warning will appear either way).</p>
<p>We now present a simulation that should give you some insight into the problem here.</p>
</section>
<section id="parametric-bootstrapping" class="level2">
<h2 class="anchored" data-anchor-id="parametric-bootstrapping">Parametric bootstrapping</h2>
<p>The hypothesis of row-column independence can be expressed mathematically in terms of a probability distribution over the cell counts in a table. With R, if you can “draw” a new table from that distribution, you can draw a thousand. Then, you can compute a <span class="math inline">\(\chi^2\)</span> statistic for each new table, and it turns out that you can use all of those recomputed statistics to approximate the sampling (reference) distribution of that statistic.</p>
<p>This idea (sample from a known distribution, calculate a test statistic, repeat) is closely related to the (perhaps familiar) idea of bootstrapping, in which a test statistic is calculated on re-samples (with replacement) from the original sample of data. There are entire books written about bootstrapping, and it’s well beyond the scope of this course to go into details here. We use this technique here to help illustrate the limitations of the Chi-squared distribution as the reference distribution for the <span class="math inline">\(\chi^2\)</span> statistic in the case of small counts.</p>
<p>The essential result is that the reference distribution we get using our re-sampling technique is closer to the true reference distribution of the <span class="math inline">\(\chi^2\)</span> statistic than is the <span class="math inline">\(\chi^2\)</span> distribution <em>when the sample size is small</em> (simulation works just fine when the sample size is large as well, it’s just a waste of computation when the known large-sample distribution applies).</p>
<p>There are some other tricky details here, because there are multiple probability distributions over cell counts that are consistent with the verbal statement “rows and columns are independent.” For now we’ll just take the simulation script below as given. If you’re interested in some of these details, please see the optional “Sampling Models” section below.</p>
<p>Once the re-sampling script computes a lot of chi-squared statistics (stored in resamp$stats) for tables drawn under the hypothesis of independence, we see where we stand by plotting the distribution of those re-sampled chi-squared statistics, and comparing it to the theoretical Chi-squared distribution on a plot.</p>
<blockquote class="blockquote">
<p>Running this R chunk just creates the function we need for re-sampling.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>two_way_resample <span class="ot">&lt;-</span> <span class="cf">function</span>(tab, <span class="at">nsim =</span> <span class="dv">2000</span>, <span class="at">fixed_margins =</span> <span class="st">"none"</span>) {</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(fixed_margins <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"none"</span>, <span class="st">"columns"</span>, <span class="st">"rows"</span>, <span class="st">"both"</span>))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  new_two_way <span class="ot">&lt;-</span> <span class="cf">function</span>(tab, <span class="at">fixed_margins =</span> <span class="st">"none"</span>){</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    I <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tab)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    J <span class="ot">&lt;-</span> <span class="fu">ncol</span>(tab) </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    n_i. <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(tab) </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    n._j <span class="ot">&lt;-</span> <span class="fu">colSums</span>(tab)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    N <span class="ot">&lt;-</span> <span class="fu">sum</span>(tab)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    null_probs <span class="ot">&lt;-</span> (n_i. <span class="sc">%*%</span> <span class="fu">t</span>(n._j))<span class="sc">/</span>(N<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    new_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, I, J)</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate random table as SINGLE multinomial sample of size N, preserving neither row nor column margins.</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(fixed_margins <span class="sc">==</span> <span class="st">"none"</span>){</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>      new_table <span class="ot">&lt;-</span> <span class="fu">rmultinom</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">size =</span> N, <span class="fu">as.vector</span>(null_probs)) <span class="sc">%&gt;%</span> <span class="fu">matrix</span>(<span class="at">nrow =</span> I, <span class="at">ncol =</span> J)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>      } </span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate random table as independent multinomial samples in each ROW, preserving original row margins.</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="cf">if</span>(fixed_margins <span class="sc">==</span> <span class="st">"rows"</span>){</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>I){</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>        new_table[i, ] <span class="ot">&lt;-</span> <span class="fu">rmultinom</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">size =</span> n_i.[i], <span class="at">prob =</span> null_probs[i ,]) <span class="co"># rmultinom automatically renormalizes the row i probs.</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>      new_table <span class="sc">%&lt;&gt;%</span> <span class="fu">matrix</span>(<span class="at">nrow =</span> I, <span class="at">ncol =</span> J)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate random table as independent multinomial samples in each COLUMN, preserving original column margins.</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="cf">if</span>(fixed_margins <span class="sc">==</span> <span class="st">"columns"</span>){</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>J){</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>        new_table[, j] <span class="ot">&lt;-</span> <span class="fu">rmultinom</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">size =</span> n._j[j], <span class="at">prob =</span> null_probs[, j]) <span class="co"># rmultinom automatically renormalizing the column j probs.</span></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>      new_table <span class="sc">%&lt;&gt;%</span> <span class="fu">matrix</span>(<span class="at">nrow =</span> I, <span class="at">ncol =</span> J)</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate random table by sampling from among all possible I x J tables with the given row and column margins.</span></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="cf">if</span>(fixed_margins <span class="sc">==</span> <span class="st">"both"</span>){</span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>      new_table <span class="ot">&lt;-</span> <span class="fu">r2dtable</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">r =</span> n_i., <span class="at">c =</span> n._j)[[<span class="dv">1</span>]]</span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(new_table)</span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a>  chisqs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, nsim) </span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a>    chisqs[j] <span class="ot">&lt;-</span> <span class="fu">new_two_way</span>(tab, fixed_margins) <span class="sc">%&gt;%</span> chisq_stat0</span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a>  obs_chisq <span class="ot">&lt;-</span> <span class="fu">chisq_stat0</span>(tab)</span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a>  pval <span class="ot">&lt;-</span> <span class="fu">sum</span>(chisqs <span class="sc">&gt;=</span> obs_chisq)<span class="sc">/</span>nsim <span class="co"># One-sided</span></span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">stats =</span> chisqs, <span class="at">obs_chisq =</span> obs_chisq, <span class="at">pval =</span> pval))</span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sampling-models-optional" class="level2">
<h2 class="anchored" data-anchor-id="sampling-models-optional">Sampling Models (Optional)</h2>
<p>In this section, we describe some of the details of the code for re-sampling, in particular the different types of probability distributions from which we can draw the re-samples. In the example of running the code below for the Lady Tasting Tea data, we perform the re-sampling only based on the method imposed by the experimental design in the actual Lady Tasting Tea experiment.</p>
<p>As mentioned above, to use the re-sampling function, we need to make the verbal statement “sample a new 2-way table under the hypothesis of independence” precise enough to do some computing. There are several different ways that the Lady Tasting Tea experiment <em>could have been</em> carried out. Each possible sampling model below corresponds to a different way the tea-tasting experiment could have been designed and performed statistical analysis depends on the experiment design (as it should!). We’ll also point out which way the experiment <em>was actually performed</em>.</p>
<section id="unrestricted-sampling" class="level3">
<h3 class="anchored" data-anchor-id="unrestricted-sampling">Unrestricted Sampling</h3>
<p>Consider this scenario: we give the lady however many cups of tea she feels like tasting, and we don’t tell her anything about how many of each type (milk-first or tea-first) there are. This “unrestricted” sampling can be modeled using a Poisson distribution.</p>
<p>[This case is included for sake of completeness, in the context of inference, this and the next situation, where the total sample size is fixed can be treated the same.]</p>
</section>
<section id="total-sample-size-fixed" class="level3">
<h3 class="anchored" data-anchor-id="total-sample-size-fixed">Total Sample Size Fixed</h3>
<p>Now consider this scenario: The lady is to be presented with eight cups of tea, but the number that are milk-first is not predetermined. In the <em>actual</em> Lady Tasting Tea data, there were four milk-first cups, but in this scenario, there could have been two, five, eight, any number between zero and eight. In this scenario, the lady is not told how many cups of each type (milk-first or tea-first) there were. To perform this sampling, we use a multinomial distribution for the entire table (i.e., with N = 8 and four categories).</p>
</section>
<section id="one-margin-fixed" class="level3">
<h3 class="anchored" data-anchor-id="one-margin-fixed">One Margin Fixed</h3>
<p>In another scenario that could have produced the Lady Tasting Tea data, suppose there are four cups of each type of tea, but the lady <em>doesn’t know</em> there are four of each. In this case “The Truth” margins are fixed (at four), but the “Guess” margins are not. For this type of sampling, we use independent multinomials within rows or within columns (i.e., with N = 4 and two categories).</p>
</section>
<section id="both-margins-fixed" class="level3">
<h3 class="anchored" data-anchor-id="both-margins-fixed">Both Margins Fixed</h3>
<blockquote class="blockquote">
<p>This is the actual situation of Fisher’s original Lady Tasting Tea experiment. Four cups of each type were presented, and the lady knew that she would taste four of each. Because of this, the row margins are fixed at four and the column margins also fixed at four. In this case, we base the sampling on (generalized) hypergeometric distribution.</p>
</blockquote>
</section>
</section>
<section id="examples-of-re-sampling-lady-tasting-tea" class="level2">
<h2 class="anchored" data-anchor-id="examples-of-re-sampling-lady-tasting-tea">Examples of Re-sampling: Lady Tasting Tea</h2>
<p>In the following R chunk, we re-sample the Lady Tasting Tea data, based on the sampling design imposed by the original experimental setup (both margins fixed). Go ahead and run the R chunk and take a look at the resulting plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>resamp_tea <span class="ot">&lt;-</span> <span class="fu">two_way_resample</span>(TeaTasting, <span class="at">nsim =</span> <span class="dv">2000</span>, <span class="at">fixed_margins =</span> <span class="st">"both"</span>) </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>chisq_val <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">8</span>,<span class="at">length=</span><span class="dv">2000</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>chisq_theory <span class="ot">&lt;-</span> <span class="fu">dchisq</span>(chisq_val,<span class="dv">1</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fix both row and column margins</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">ggtitle</span>(<span class="st">"Re-sampling distribution of chi-squared stat vs </span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="st">    theoretical chi-squared distribution"</span>) <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a> <span class="fu">xlab</span>(<span class="fu">expression</span>(X<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a> <span class="fu">ylab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> chisq_val, <span class="at">y =</span> chisq_theory), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_density</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> resamp_tea<span class="sc">$</span>stats), <span class="at">bw =</span> <span class="fl">0.05</span>) <span class="sc">+</span> </span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">chisq_stat0</span>(TeaTasting)), <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this plot, the smooth blue line is the theoretical Chi-squared (df = 1) reference distribution. The black line with a few spikes is the reference distribution we get by running the re-sampling code. There are actually only a few values of the chi-squared statistic that are possible with such a sparse table. Finally, the vertical red line is the value of the chi-squared statistic calculated from the observed table.</p>
<p>The problem here is that with such small counts in the table, there are only a small number of rearranged (re-sampled) tables possible. There just aren’t that many ways to rearrange eight cups of tea into a 2x2 table of counts, especially if we <em>also</em> fix both column and row totals! Therefore, only a limited number of tables, and an even more limited number of chi-squared statistics, can possibly be obtained.</p>
<p>This is precisely why using the large sample reference distribution (blue line) isn’t such a good idea here, because is does a really poor job of approximating the resampled reference distribution (black line).</p>
<p>It might seem like it was overkill to simulate 2000 samples and calculate the chi-squared statistic for each one, when there were actually only three possible chi-squared statistics for this situation! That is, maybe there is some way we could have have worked this out by hand. Indeed, working it out “exactly” by hand is what Fisher did. His test involves (essentially) listing every way that the chi-squared statistic could have been bigger than it was, and calculating the probability of each of those ways.</p>
<p>Execute the following R chunk, which applies Fisher’s Exact Test to the Lady Tasting Tea data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(TeaTasting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  TeaTasting
p-value = 0.4857
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0.2117329 621.9337505
sample estimates:
odds ratio 
  6.408309 </code></pre>
</div>
</div>
<p>Fisher’s Exact Test agrees pretty closely with the final simulation above because Fisher’s exact test supposes that both rows and columns of the tables are fixed by design. Restricting it in this way, as we see above, reduces the number of possible tables to deal with, which makes it easier to calculate the p-value “by hand.” And in the tea-tasting example, these restrictions actually do make sense. There are 4 cups of each kind of tea, the lady <em>knows</em> there are 4 of each, there are only a few ways this thing can go.</p>
<p>We’d also like to call your attention to the odds ratio and 95% confidence interval estimates that appear in the <code>fisher.test()</code> output. Rather than using a chi-squared statistic for making inference, the <code>fisher.test()</code> function uses an odds ratio test.</p>
<blockquote class="blockquote">
<p>Important note: tests for equal odds ratios, equal proportions and homogeneity will yield similar inferences in the case of 2x2 tables. You just have to sort out which procedure makes the most sense for the data you are dealing with.</p>
</blockquote>
</section>
<section id="beyond-fixed-margins" class="level2">
<h2 class="anchored" data-anchor-id="beyond-fixed-margins">Beyond Fixed Margins</h2>
<p>In many (most) cases, the assumption that all the row and column totals are fixed doesn’t make sense and isn’t needed. For example, in a medical study, we might recruit 30 people with a disease; give treatment A to half of them and treatment B to the other half; and record whether or not they were cured after some period of time. In this case, we’ve fixed the row totals by design, because we put 15 patients in each group, but we haven’t fixed the column totals, we can’t say in advance know how many patients will be cured under either treatment. And, in this case, we still have the potential problem of small cell counts.</p>
<p>Fisher’s exact test was designed for precisely the situation of the Lady Tasting Tea (statistically, both margins are fixed). Nevertheless, it is used in many cases to test independence when the cell counts are small, as in the hypothetical medical study just described.</p>
<p>You are welcome to replicate the call to the <code>two_way_resample()</code> function, changing the <code>fixed_margins = "both"</code> argument to any of <code>"none"</code>, <code>"rows"</code> or <code>"columns"</code>. Using the Lady Tasting Tea data, you’ll see that the Chi-squared (df = 1) distribution gives a poor approximation to the re-sampled distribution, <em>because the cell counts are so small!</em></p>
</section>
<section id="beyond-2-x-2-tables" class="level2">
<h2 class="anchored" data-anchor-id="beyond-2-x-2-tables">Beyond 2 x 2 Tables</h2>
<p>You can apply <code>chisq.test()</code> and <code>fisher.test()</code> to general <span class="math inline">\(I \times J\)</span> tables, but you will only learn about the independence hypothesis. That is, you will not get any estimates. For estimates proportions and odds ratios from <span class="math inline">\(I \times J\)</span> tables, we have to turn to more sophisticated statistical models such as generalized linear models.</p>
</section>
</section>
<section id="lab-2" class="level1">
<h1>Lab 2</h1>
<section id="module-2-lab-assignment-instructions" class="level3">
<h3 class="anchored">Module 2 Lab Assignment Instructions</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Repeat instructions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Like for Lab 1, you are asked to create a <strong>self-contained</strong> R Markdown script that can generate a document which answers the questions below. You will submit the .Rmd script, and you will be graded (complete/incomplete) based on whether or not the script generates a reasonable HTML document.</p>
<section id="r-markdown-for-submission" class="level2">
<h2 class="anchored" data-anchor-id="r-markdown-for-submission">R Markdown for submission</h2>
<p>Last week’s instructions are repeated here for your convenience.</p>
<p><strong>NOTE:</strong> <em>If you are reading these instructions from the HTML preview in the Viewer pane, they will be overwritten in the following steps. You can avoid this by “popping out” the current HTML preview into an external browser window, by clicking the the “Show in new window” icon (to the right of the broom icon in the Viewer pane). </em></p>
<p><em>Alternatively, you can read the instructions right from the .Rmd script, keeping in mind that you will need to switch back to the lab script tab to view the rest of the instructions once you create a new script. You could also copy and paste the whole Lab 2 Assignment Instructions section into your new document while you’re working on it, and then delete the instructions before you submit it.</em></p>
<p>Click “File” -&gt; “New File” -&gt; “R Markdown”, and dialog box will pop up. Change the title to “Lab Assignment 1” and name yourself as author. Select PDF as the Default Output Format, then click OK. The header of your new file should look something like this:</p>
<pre><code>---
title: "Lab Assignment 2"
author: "Ronald Fisher"
date: "2024-04-08"
output: pdf_document
---
</code></pre>
<p>The file will initially contain some examples to get you started with RMarkdown, which you should replace with your lab content. Save the notebook as something like “Lab_Assignment_1” using “File” –&gt; “Save As…”</p>
<p>In your new .Rmd script, answer the questions in the “Questions” section below. Include all the code you need to produce the requested outputs. Your script should include a top-level section heading for each question, for example:</p>
<pre><code># Question 1

stuff here

# Question 2

other stuff</code></pre>
<p>Whether or not you include the text of the questions in your script is up to you.</p>
<blockquote class="blockquote">
<p>Do be sure to include, near the top of your script, a code chunk that loads any non-default packages you use (such as <em>vcdExtra</em> or <em>Sleuth3</em>).</p>
</blockquote>
<p>Within the question sections, you can chunk your code in whatever way seems reasonable. Incorporate any written answers outside the code chunks using Markdown formatting as needed (see “Help” -&gt; “RMarkdown Quick Reference” for text formatting help).</p>
<p>To ensure that your .Rmd script will be fully self-contained (i.e.&nbsp;it will not depend on objects that were defined during the lab, and could be run as-is if you sent it to someone else), you should <strong>clear the workspace</strong> before you begin.</p>
<blockquote class="blockquote">
<p>To clear the workspace, click the broom icon in the Environment pane.</p>
</blockquote>
<p>Once you’ve answered the questions in your new .Rmd script and you have verified your code is self contained, you should Run -&gt; Run All Chunks and generate a .pdf file of your document, to check that everything looks like you want it to. Having concluded that your .Rmd script produces a pdf document that includes all the output you want, submit <strong>both the Lab_Assignment_2.Rmd file and the pdf document</strong> on Canvas as your Lab Assignment 2.</p>
<p>Feel free to post on the discussion board if you have any questions or encounter any difficulties with this process.</p>
</section>
</div>
</div>
</div>
</section>
</section>
<section id="questions" class="level1">
<h1>Questions:</h1>
<blockquote class="blockquote">
<p>NOTE: The first two questions are for credit. The next two are optional/for fun.</p>
</blockquote>
<section id="q1." class="level2">
<h2 class="anchored" data-anchor-id="q1.">Q1.</h2>
<p>The following data come from one of Gregor Mendel’s famous experiments with pea plants. In this particular experiment, Mendel examined two categorical traits in pea seeds, each with two possible values: seed color, yellow or green, and seed shape, round or angular.</p>
<p>According to Mendel’s hypothesis, the inheritance pattern of these traits was characterized by “independent assortment”, that is, there was no “genetic linkage” between these traits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>mendel <span class="ot">&lt;-</span> <span class="fu">as.table</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">315</span>, <span class="dv">108</span>, <span class="dv">101</span>, <span class="dv">32</span>),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">nrow =</span> <span class="dv">2</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">dimnames =</span> </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">list</span>(<span class="at">Color=</span> <span class="fu">c</span>(<span class="st">"Yellow"</span>, <span class="st">"Green"</span>),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">Shape =</span> <span class="fu">c</span>(<span class="st">"Round"</span>, <span class="st">"Angular"</span>))))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>mendel</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Shape
Color    Round Angular
  Yellow   315     101
  Green    108      32</code></pre>
</div>
</div>
<p><em>How consistent are these data with Mendel’s hypothesis of independence? </em></p>
<p><em>Is a Chi-squared test appropriate here? Why or why not?</em></p>
<p>Notice that in this particular case, we’re not interested in a <em>departure</em> from independence, but rather a <em>confirmation</em> of independence.</p>
<p>Cells are at least 5, the chi-squared test should be adequate, but I’ll confirm with Fisher.</p>
<p>The null is that the proportions at each shape are the same for both colors, The proportion of round and yellow is the same as round and green.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaic</span>(mendel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>They look independent based on the alignment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mendel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  mendel
X-squared = 0.051332, df = 1, p-value = 0.8208</code></pre>
</div>
</div>
<p>p-value = 0.8208 indicates that there’s evidence of independence of color and shape.</p>
<p>chisq.test() and fisher.test()</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">t</span>(mendel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  t(mendel)
X-squared = 0.051332, df = 1, p-value = 0.8208
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.10334886  0.07391357
sample estimates:
   prop 1    prop 2 
0.7446809 0.7593985 </code></pre>
</div>
</div>
<p>prop test confidence interval contains zero, that is further evidence these groups are the same. Shape is homogeneous in terms of color.</p>
<p>For Fisher, the null is the proportions at one variable are the same for different values of the second variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(mendel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  mendel
p-value = 0.819
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.5667874 1.4806148
sample estimates:
odds ratio 
 0.9242126 </code></pre>
</div>
</div>
<p>Fisher agrees that the proportions are the same.</p>
</section>
<section id="q2." class="level2">
<h2 class="anchored" data-anchor-id="q2.">Q2.</h2>
<p>We mentioned previously, and it’s mentioned in the narrated lecture materials that there’s an equivalence between the Chi-squared test and the difference in proportions test in the case of 2x2 tables. Take a look for the Mendel data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mendel, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  mendel
X-squared = 0.11634, df = 1, p-value = 0.733</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(mendel, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  mendel
X-squared = 0.11634, df = 1, p-value = 0.733
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.09506177  0.06662771
sample estimates:
   prop 1    prop 2 
0.7572115 0.7714286 </code></pre>
</div>
</div>
<p>The output from the prop.test chunk refers to a <code>two.sided</code> test, with an interpretation in terms of a signed difference between two proportions, whereas the <code>chisq.test()</code> is a one-sided test, with an interpretation involving deviation from the hypothesis of independent rows and columns.</p>
<p>It’s not <em>entirely</em> obvious why these results should be the same. The following exercise can help you see what’s going on.</p>
<p>Use <code>rnorm()</code> and <code>rchisq()</code> to produce and store the following vectors:</p>
<p>1000 draws from the standard normal distribution, 1000 draws from the Chi-squared distribution with 1 degree of freedom.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>norm <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>chi <span class="ot">&lt;-</span> <span class="fu">rchisq</span>(<span class="dv">10000</span>, <span class="at">df =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li>Construct separate histograms/density plots of the raw chi-squared values and the <em>squares</em> of the standard normal values.</li>
</ol>
<p>What do you observe?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>squared <span class="ot">&lt;-</span> norm<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(density(norm),</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co">#      xlim = c(-10,10),</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co">#      ylim = c(0,1), </span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co">#      main = "Normal")</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(chi, <span class="at">bw =</span> <span class="fl">0.1354</span>),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>),</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), </span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Chi^2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(squared, <span class="at">bw =</span> <span class="fl">0.1354</span>),</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>),</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Norm^2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>They are very similar. The chi squared graph is a little more left and taller.</p>
<ol start="2" type="a">
<li>Recall (or obtain from <code>qnorm(0.975)</code> that the <em>2-sided 95%</em> critical values for the standard normal distribution are ± 1.96.</li>
</ol>
<p>Use <code>qchisq()</code> to compare the <em>square</em> of these 2-sided 95% critical values from the standard normal to the <em>one-sided</em> 95% critical value for the Chi-squared(1).</p>
<p>What does this suggest about tests based on these two reference distributions?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>crit_z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>crit_chi <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">1</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>crit_z<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.841459</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>crit_chi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.841459</code></pre>
</div>
</div>
<p>At least at where chi-squared has one degree of freedom, these two tests are equivilent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(norm<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(chi) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">1</span>), <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z2_learnR_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>END REQUIRED QUESTIONS</strong></p>
<blockquote class="blockquote">
<p>The next two questions are optional, you do not need to submit anything about them for your assignment.</p>
</blockquote>
</section>
<section id="q3." class="level2">
<h2 class="anchored" data-anchor-id="q3.">Q3.</h2>
<p>This isn’t actually a question, just some reading and code to work through. It’s an interesting continuation of Mendel’s independence hypothesis, and a slightly different application of <code>chisq.test()</code> in R.</p>
<p>Mendel actually had a more sophisticated hypothesis than “seed color and seed shape are independent”, he knew <em>how</em> they should be independent based on his mechanistic understanding of the process of inheritance of dominant and recessive traits. On these grounds, Mendel hypothesized <em>specific proportions</em> for each cell in this particular table. He knew that if his ideas were correct, the cell proportions for his experiment should have been, specifically:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>(mendel_expect <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">3</span>), <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>)))<span class="sc">/</span><span class="dv">16</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]   [,2]
[1,] 0.5625 0.1875
[2,] 0.1875 0.0625</code></pre>
</div>
</div>
<p>This is a more stringent requirement than row/column independence, since there would be many possible tables consistent with some kind of independence relationship, but radically inconsistent with Mendel’s <em>scientific</em> understanding. For instance, if the upper right and lower left cell counts had been reversed, we would get the same chi-squared statistic for the table (check!) but seeing this would have suggested that Mendel was somehow seriously mistaken.</p>
<p>Here, we need a different approach than the chi-squared test of independence. We want to test an entire proposed distribution over the 4 cells. The tool for this job is the <em>chi-squared test of goodness of fit</em>, which in R is also performed by <code>chisq.test().</code></p>
<p>The goodness of fit test is supposed to test the distribution of a single variable, so <code>chisq.test()</code> will perform the goodness of fit test if the data are provided as a single vector, rather than as a 2 x 2 table. Since we have particular distribution in mind, we’ll need to provide those hypothesized probabilities as well:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>(mendel_vec <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(mendel)) <span class="co"># stretch out the table and make sure we know HOW it was stretched out, in order to get the hypothesized probabilities associated with the correct table cells.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 315 108 101  32</code></pre>
</div>
</div>
<p>And now preform the Chi-squared test passing in the <em>vector</em> of observed counts and the vector of specific proportions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mendel_vec, <span class="at">p =</span> <span class="fu">c</span>(<span class="dv">9</span><span class="sc">/</span><span class="dv">16</span>, <span class="dv">3</span><span class="sc">/</span><span class="dv">16</span>, <span class="dv">3</span><span class="sc">/</span><span class="dv">16</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">16</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  mendel_vec
X-squared = 0.47002, df = 3, p-value = 0.9254</code></pre>
</div>
</div>
<p>Note that the degrees of freedom are different – 4-1 = 3 instead of (2-1)(2-1) = 1. A very rough idea of why this should be is that with a more specific hypothesis (“each cell probability should be exactly so”) there are more ways the data could deviate from it.</p>
<p>An interesting historical note: R.A. Fisher, when reviewing Mendel’s original data, applied the chi-squared test to some data like these, and reached the conclusion that deviations were <em>too small</em> to have arisen by chance. He thought that the independence model fit so closely that Mendel’s data must have been deliberately doctored though in his great respect for Mendel, Fisher laid the blame on “some gardening assistant” who must have known too well what his supervisor hoped to see.</p>
</section>
<section id="q4." class="level2">
<h2 class="anchored" data-anchor-id="q4.">Q4.</h2>
<p>Suppose we performed the tea-tasting experiment, and produced a table with 4’s in the diagonal and 0’s in the off-diagonal cells – that is, suppose the lady performed as well as the experiment allowed. If we had observed this (best possible) performance under the <strong>fixed-columns design</strong> (where the lady didn’t know the number of cups of each type), what p-value would she score? (use resampling script). What if we observed this same performance under the <strong>fixed-rows and fixed-columns design</strong> (where she knew there were 4 cups of each)?</p>
<p>Does it make sense that the best-possible performance earns a smaller p-value under the more “challenging” experimental setup than under the “easier” one? What does this say about which design we might prefer to use?</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>