<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data_Analysis_II_Notes - LearnR 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data_Analysis_II_Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./1_Types_of_Categoricals.html" rel="" target="">
 <span class="menu-text">1 Types of Categoricals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./2_Props_Risks_Odds.html" rel="" target="">
 <span class="menu-text">2 Props, Risk &amp; Odds</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./3_Logistic_Regression_I.html" rel="" target="">
 <span class="menu-text">3 Log Reg I</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./4_Logistic_Regression_II.html" rel="" target="">
 <span class="menu-text">4 Log-Reg II</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./5_Log_linear_Regression.html" rel="" target="">
 <span class="menu-text">5 Log-lin-Reg</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./6_Dispersion_Zero_Inflation.html" rel="" target="">
 <span class="menu-text">6 Disp &amp; 0 Inflation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./7_Random_Effects.html" rel="" target="">
 <span class="menu-text">7 Random_Effects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./8_Evaluating_Models.html" rel="" target="">
 <span class="menu-text">8 Model Eval</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./9_Imp_Pred_Validate.html" rel="" target="">
 <span class="menu-text">9 Imp, Pred, Validate</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./10_Final_Project.html" rel="" target="">
 <span class="menu-text">10 Final Project</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./z0_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z1_learnR.html" rel="" target="">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z2_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z3_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z4_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z5_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z6_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z7_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z8_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 8</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#donner-data" id="toc-donner-data" class="nav-link" data-scroll-target="#donner-data">Donner Data</a>
  <ul class="collapse">
  <li><a href="#exploration" id="toc-exploration" class="nav-link" data-scroll-target="#exploration">Exploration</a>
  <ul class="collapse">
  <li><a href="#looking-at-the-data" id="toc-looking-at-the-data" class="nav-link" data-scroll-target="#looking-at-the-data">Looking at the Data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#whats-wrong-with-multiple-linear-regression-here" id="toc-whats-wrong-with-multiple-linear-regression-here" class="nav-link" data-scroll-target="#whats-wrong-with-multiple-linear-regression-here">What’s Wrong with Multiple Linear Regression Here?</a></li>
  <li><a href="#the-logistic-regression-model" id="toc-the-logistic-regression-model" class="nav-link" data-scroll-target="#the-logistic-regression-model">The Logistic Regression Model</a>
  <ul class="collapse">
  <li><a href="#the-logit-transformation" id="toc-the-logit-transformation" class="nav-link" data-scroll-target="#the-logit-transformation">The Logit Transformation</a></li>
  <li><a href="#fitting-the-binary-logistic-regression-model" id="toc-fitting-the-binary-logistic-regression-model" class="nav-link" data-scroll-target="#fitting-the-binary-logistic-regression-model">Fitting the Binary Logistic Regression Model</a></li>
  <li><a href="#assessing-model-fit" id="toc-assessing-model-fit" class="nav-link" data-scroll-target="#assessing-model-fit">Assessing Model Fit</a></li>
  <li><a href="#interpreting-the-fitted-model" id="toc-interpreting-the-fitted-model" class="nav-link" data-scroll-target="#interpreting-the-fitted-model">Interpreting The Fitted Model</a></li>
  <li><a href="#data-scale-vs-model-scale-back-transformation" id="toc-data-scale-vs-model-scale-back-transformation" class="nav-link" data-scroll-target="#data-scale-vs-model-scale-back-transformation">Data Scale vs Model Scale, Back-transformation</a></li>
  </ul></li>
  <li><a href="#module-3-lab-assignment-instructions" id="toc-module-3-lab-assignment-instructions" class="nav-link" data-scroll-target="#module-3-lab-assignment-instructions">Module 3 Lab Assignment Instructions</a>
  <ul class="collapse">
  <li><a href="#r-markdown-for-submission" id="toc-r-markdown-for-submission" class="nav-link" data-scroll-target="#r-markdown-for-submission">R Markdown for submission</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">LearnR 3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="overview" class="level1">
<h1>Overview</h1>
<p>In the previous lab, we introduced some simple statistical inference procedures for analyzing data in contingency tables. These procedures were “randomization-based,” in that they involved either directly constructing a randomization distribution of the data under a hypothesis of complete independence between two variables or approximating such a randomization distribution.</p>
<p>In most real data analysis situations, we will want to ask and answer more sophisticated questions than “are any variables related to any others.” We may have research questions like “how does the relationship between X and Y depend on the changing level of Z?” Or, “How do the odds of success change when we increase the value of a certain explanatory variable?” In these situations, we will need to move beyond randomization methods and begin using statistical models for categorical responses.</p>
<p>As you will see in this lab, modeling categorical responses with statistical methods designed for continuous ones can go sideways almost immediately, so we will use new approaches – such as generalized linear models, of which logistic regression is a special case.</p>
<p>Please run the following chunk of R code to load the packages we will use for this lab.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'vcdExtra' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'vcd' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gnm' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="donner-data" class="level1">
<h1>Donner Data</h1>
<p>You have already seen a version of the Donner Party data in the narrated lectures for Module 3. That version of the dataset was the one found in the <em>Sleuth3</em> package, and it included data only about adult members of the Donner Party. The version we will use here is from the <em>vcdExtra</em> package, and it includes data about <em>all</em> members of the Party, including children.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Donner)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Donner)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">family</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">survived</th>
<th style="text-align: left;">death</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Antoine</td>
<td style="text-align: left;">Other</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">1846-12-29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Breen, Edward</td>
<td style="text-align: left;">Breen</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Breen, Margaret I.</td>
<td style="text-align: left;">Breen</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Breen, James</td>
<td style="text-align: left;">Breen</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Breen, John</td>
<td style="text-align: left;">Breen</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Breen, Mary</td>
<td style="text-align: left;">Breen</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The main question here:</p>
<blockquote class="blockquote">
<p>After accounting for age, is there evidence of a difference in the survival probability of men and women in the Donner Party?</p>
</blockquote>
<p>Since we will be concerned only with how <code>age</code> and <code>sex</code> explain whether Donner Party members <code>survived</code>, we will drop the other variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Donner <span class="sc">%&lt;&gt;%</span> <span class="fu">select</span>(.,sex, age, survived)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a factor version of survival, with named levels, for use in subsequent plotting</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>Donner <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(<span class="at">survival_labeled =</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(survived <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"survived"</span>, <span class="st">"died"</span>)))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>Donner <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>survived) <span class="sc">%&gt;%</span> summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     sex          age        survival_labeled
 Female:35   Min.   : 1.00   died    :42     
 Male  :55   1st Qu.: 7.25   survived:48     
             Median :20.50                   
             Mean   :20.87                   
             3rd Qu.:28.00                   
             Max.   :70.00                   </code></pre>
</div>
</div>
<p>Throughout the remainder of this lab, we will treat the <code>Donner</code> data as a representative sample from some population, and practice performing statistical inference about it as such. However, given the extreme (and frankly bizarre) circumstances that produced these data, it’s unclear what that population might be (hopefully one to which we never belong!). Therefore, the results of inferential procedures we employ may not have any obvious population-level interpretations. Nevertheless, we can use these inferences to make some statements/conclusions about the Donner Party itself.</p>
<p>You might also think of this lab as an exercise in modeling-as-data-exploration for this data set, or simply as general practice with using the modeling methods. In any real data-analysis situation, you should carefully consider the <strong>scope of inference</strong> – given the available data, the range of circumstances to which your statistical conclusions from that data can be reasonably applied.</p>
<section id="exploration" class="level2">
<h2 class="anchored" data-anchor-id="exploration">Exploration</h2>
<p>The variable <code>age</code> is continuous, the response <code>survived</code> is binary, and so far, we don’t have any tools for that situation. When all you have is a chi-square test, everything looks like a contingency table, and if we just collapse <code>age</code> away, we can produce a familiar 2x2 table of counts:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(tbl1 <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> Donner, <span class="sc">~</span> sex <span class="sc">+</span> survived))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        survived
sex       0  1
  Female 10 25
  Male   32 23</code></pre>
</div>
</div>
<p>And see the proportions surviving in each <code>sex</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(tbl1, <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        survived
sex         0    1
  Female 0.29 0.71
  Male   0.58 0.42</code></pre>
</div>
</div>
<p>Of the original 55 males, 42% survived, and of the original 35 females, 71% survived,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tbl1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  tbl1
X-squared = 6.392, df = 1, p-value = 0.01146</code></pre>
</div>
</div>
<p>and the p-value for the difference in survival by sex is fairly small (but remember that a p-value doesn’t really make sense here without a population to point to).</p>
<p>From the proportions, we can get the odds of survival for males and females, respectively:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(male_odds <span class="ot">&lt;-</span> <span class="fl">0.42</span><span class="sc">/</span><span class="fl">0.58</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7241379</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>(female_odds <span class="ot">&lt;-</span> <span class="fl">0.71</span><span class="sc">/</span><span class="fl">0.29</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.448276</code></pre>
</div>
</div>
<p>And the odds ratio for survival by sex:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>(mf_odds_ratio <span class="ot">&lt;-</span> male_odds<span class="sc">/</span>female_odds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2957746</code></pre>
</div>
</div>
<p>Ignoring age, the odds of survival for males is 30% of the odds of survival for females.</p>
<p>We really don’t want to base any conclusions on this simple aggregation, however – we actually do want to use the information about the continuous variable <code>age</code>, and the relationship between <code>sex</code> and <code>survival</code> may be different at different <code>age</code> values. Let’s see how we might proceed treating <code>age</code> as continuous.</p>
<section id="looking-at-the-data" class="level3">
<h3 class="anchored" data-anchor-id="looking-at-the-data">Looking at the Data</h3>
<p>If you looked at Module 1 Lab 0, you already saw a plot of the Donner Party data. Let’s look at a similar plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data=</span>Donner,<span class="fu">aes</span>(age,survived,<span class="at">color=</span>sex,<span class="at">shape=</span>sex)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Also, remember that in Lab 0, we showed you these data with some jitter added so that the overlapping points are given a little separation. Here is the plot with jitter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Donner) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot jittered data</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> survived,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shape =</span> sex),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">width =</span> <span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It’s still not at all obvious what’s going on here. You can see from this jittered version of the plot that there do seem to be a higher proportion of females that survived than males (<code>survived == 1</code> corresponds to survival), and maybe that there was a “sweet spot” in terms of the ages of the females that survived (i.e., between the ages of about 5 and 35, it looks like most of the females survived).</p>
</section>
</section>
</section>
<section id="whats-wrong-with-multiple-linear-regression-here" class="level1">
<h1>What’s Wrong with Multiple Linear Regression Here?</h1>
<p>The multiple linear regression model equates the mean of a response variable to a linear combination of explanatory variables, often called the “linear predictor”:</p>
<p><span class="math display">\[Mean(Y|X_1,...X_p) = \beta_0 + \beta_1X_1 + ... + \beta_{p}X_p\]</span></p>
<p>In the Donner Party data, <span class="math inline">\(Y\)</span> is the 0/1 (binary) survival outcome, and we have <span class="math inline">\(X_1\)</span> = <code>age</code> and <span class="math inline">\(X_2\)</span> = <code>sex</code>. The mean of a binary random variable is just the probability of a 1, so this model says the probability of <code>survival</code> is a linear function of <code>age</code> and <code>sex</code> (and possibly the interaction between them). We could call this the “linear probability model”</p>
<p><span class="math display">\[P(Survive|Sex, Age) = \beta_0 + \beta_1Age + \beta_2Sex + \beta_3Age \times Sex\]</span></p>
<p>As you may recall from previous courses, including the binary predictor <code>sex</code> means the <em>intercept</em> of the survival-probability/age line can be different for males and females. Including the interaction of <code>age</code> with <code>sex</code> means that the <em>slope</em> of the line is allowed to differ between males and females as well.</p>
<p>Using the binary-coded survival values, let’s go ahead and fit a multiple linear regression model to these data. That is, we’re going to tell <code>lm()</code> that 0 and 1 are just regular numbers, <code>lm()</code> is going to draw some straight lines through the points, and we’re going to try to interpret y-values from those fitted lines as estimates of survival probabilities at different values of <code>age</code> and <code>sex</code>.</p>
<blockquote class="blockquote">
<p>Recall that probabilities must, <em>by definition</em>, take values within the range [0, 1]</p>
</blockquote>
<p>Here’s our linear model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> Donner, survived <span class="sc">~</span> sex <span class="sc">*</span> age) <span class="co"># don't try this at work</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = survived ~ sex * age, data = Donner)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8793 -0.4081  0.1347  0.4724  0.7512 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.888690   0.121520   7.313 1.27e-10 ***
sexMale     -0.339005   0.163881  -2.069   0.0416 *  
age         -0.009362   0.004914  -1.905   0.0601 .  
sexMale:age  0.003463   0.006348   0.546   0.5868    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4729 on 86 degrees of freedom
Multiple R-squared:  0.1415,    Adjusted R-squared:  0.1115 
F-statistic: 4.724 on 3 and 86 DF,  p-value: 0.004236</code></pre>
</div>
</div>
<p>Well that didn’t explode (unfortunately, R will typically allow us to fit any goofy model we want – it’s up to us to realize it’s a goofy model!) The R-Squared isn’t that high, but it’s not terribly low. So what’s wrong with this model? Let’s examine the fit of the model and its predictions more closely.</p>
<p>The following R chunk obtains 95% confidence and prediction bands, and then plots those bands, along with the linear fit, to the Donner Party data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain confidence and prediction bounds from predict.lm()</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>linear_confidence_bands <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm1, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span> data.frame <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">lwr_conf =</span> lwr, <span class="at">upr_conf =</span> upr)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>linear_prediction_bands <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm1, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span> data.frame <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">lwr_pred =</span> lwr, <span class="at">upr_pred =</span> upr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(lm1, interval = "prediction", level = 0.95): predictions on current data refer to _future_ responses</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>augment_Donner <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(Donner, linear_confidence_bands, linear_prediction_bands))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Delete duplicate 'fit' columns, since both linear_confidence_bands and linear_prediction_bands have 'fit'.</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>augment_Donner <span class="ot">&lt;-</span> augment_Donner[,<span class="sc">-</span><span class="dv">5</span>]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Big plot</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> augment_Donner) <span class="sc">+</span> </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot jittered data</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> survived,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shape =</span> sex),</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot fitted lines</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> fit, </span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex)) <span class="sc">+</span> </span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 95% confidence bands</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>                  <span class="at">fill =</span> sex, </span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymin =</span> lwr_conf, </span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> upr_conf),</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 95% prediction bands</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>                  <span class="at">fill =</span> sex, </span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymin =</span> lwr_pred, </span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> upr_pred),</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot reference lines at 0 and 1 (minimum and maximum possible probabilities)</span></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>sex) <span class="sc">+</span> </span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Linear model for Donner Party"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this plot, we’ve split the data for males and females into two side-by-side panels. In both panels, the horizontal dashed lines appear at y = 0 and y = 1, to demarcate the lower and upper bounds on probability. In each plot, you’ll see a solid, decreasing straight line – this is the model fit, or the estimated linear regression lines that we obtain from fitting the linear probability model.</p>
<p>In each panel, the 95% confidence bands appear as the darker ribbons around the fitted model lines. The confidence bands show, at each value of <code>age</code> and <code>sex</code>, a 95% confidence interval for the probability of survival. The confidence bands are widest at age values further from the mean age – uncertainty about the intercept applies to the whole line equally, but uncertainty about the slope makes a bigger difference near the ends. Notice that for the higher ages, 95% confidence bands slip over the y = 0 line for both males and females – but <em>we know</em> that probability cannot be less than zero!</p>
<p>The lightly-shaded and substantially wider ribbons around the fitted regression lines represent 95% <em>prediction</em> intervals. Remember that prediction intervals are <em>wider</em> than confidence intervals, because prediction intervals incorporate uncertainty in the regression estimates <em>and</em> uncertainty due to sampling (predicting) a new response value. These make sense when the response is continuous, but not when it’s binary. If we go to predict a new binary observation, the only possible values for the new response are 0 and 1 – there’s zero probability that a new observation falls anywhere but along the Y = 0 or Y = 1 lines, and uncertainty about <em>which one</em> of those two values it will take cannot be meaningfully quantified by <em>any</em> kind of interval. This is a critical difference between the binary response and continuous response situations, which the linear probability model cannot respect.</p>
<p>In light of the disclaimer about scope of inference earlier in the lab, you might reasonably object to this nitpicking about confidence intervals in the Donner scenario – after all, it’s not like we can define the population from which this sample of individuals was drawn, so what do the intervals mean? Isn’t it enough that our fitted values make sense? Leaving aside the fact that in similar binary-response situations we would prefer sane confidence intervals, it’s easy to see that the fitted values themselves may NOT make sense when we use the linear probability model. Look what happens when we restrict our model to the adult members of the Donner Party:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset to include only adults</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>Donner_adults <span class="ot">&lt;-</span> <span class="fu">filter</span>(Donner, age <span class="sc">&gt;</span> <span class="dv">18</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot just estimated probabilities, no uncertainty bands</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Donner_adults) <span class="sc">+</span> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># original data</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> survived,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shape =</span> sex),</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># This is a shortcut, within ggplot, to fitting a linear model and plotting the fits</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> survived, <span class="at">color =</span> sex), </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># reference lines</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>sex) <span class="sc">+</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Linear model for Donner Adults"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now we see that the estimated probability of survival for a female over age 60 is negative, which is absurd.</p>
<p>The demonstrates that the linear probability model, when applied to binary data, can grossly violate the most basic constraints of the problem.</p>
</section>
<section id="the-logistic-regression-model" class="level1">
<h1>The Logistic Regression Model</h1>
<p>The technique we will use for modeling probabilities of binary responses as a function of one or more (possibly continuous) explanatory variables is called logistic regression. This model is one instance of the <em>generalized linear model</em>, which we will rely on throughout the rest of the course. Whereas standard linear regression models suppose that the linear predictor is equal to the mean of the response variable, generalized linear models suppose that the linear predictor is equal to some <em>known function</em> of the mean response. By incorporating different functions (called “links”) that transform the mean response, generalized linear models let us extend the linear model idea to accommodate many different types of responses.</p>
<p>In the binary response situation, our problem is that linear functions of numeric variables can, in general, take values from across the entire real line, <span class="math inline">\((-\infty,\infty)\)</span>, while the probabilities of success are necessarily restricted to the [0,1] interval. In this situation, a simple straight line fit can always go “out of bounds”, as shown above. However, if we find a function that stretches the probabilities from <span class="math inline">\([0,1]\)</span> to <span class="math inline">\((-\infty,\infty)\)</span>, then we can model the <em>transformed</em> probabilities as a linear function of numeric explanatory variables, without worrying about going out of bounds. Then we can back-transform the fitted values back onto the <span class="math inline">\([0,1]\)</span> interval using the inverse transformation, which will map <span class="math inline">\((-\infty,\infty)\)</span> back to <span class="math inline">\([0,1]\)</span>. This circumvents the problem we saw above with getting fitted probabilities outside of the [0,1] interval. If we choose a good transformation function, we can even keep much of the simplicity and interpretability of the linear regression model. Let’s make this concrete.</p>
<section id="the-logit-transformation" class="level2">
<h2 class="anchored" data-anchor-id="the-logit-transformation">The Logit Transformation</h2>
<p>We will use the <strong>logit</strong> (or “log-odds”) function to link the probabilities to the linear combination of predictors. The logit function looks like this:</p>
<p><span class="math display">\[\mathrm{logit}(p) = \log(p/(1-p))\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="cf">function</span>(p){<span class="fu">log</span>(p<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p))}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is a smooth, invertible function from the <span class="math inline">\([0,1]\)</span> interval to the whole real line, <span class="math inline">\((-\infty,\infty)\)</span>. Plug in a probability, get the (natural) log of the odds. You can see this transformation, as well as the probability to odds transformation, compared in the plot below. The probability to odds transformation takes us from <span class="math inline">\([0,1]\)</span> to <span class="math inline">\([0,\infty)\)</span>, and the log transformation of that takes us from <span class="math inline">\([0,\infty)\)</span> to <span class="math inline">\((-\infty,\infty)\)</span>.</p>
<p>The y-axis on the plot below ranges only from <span class="math inline">\([-3, 3]\)</span>, but remember that the odds function is actually defined all the way from 0 to <span class="math inline">\(\infty\)</span>, and the logit ranges all the way from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>. The identity transformation, <span class="math inline">\(f(p) = p\)</span>, is included for reference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.05</span>, <span class="fl">0.95</span>, <span class="at">length =</span> <span class="dv">100</span>) <span class="co"># restricting the range of probabilities shown in order to keep the transformed values finite.   </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>odds <span class="ot">&lt;-</span> prob<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>prob)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>logits <span class="ot">&lt;-</span> <span class="fu">log</span>(odds)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>transformations <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">identity =</span> prob, odds, logits) <span class="sc">%&gt;%</span> <span class="fu">gather</span>() <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">transform_function =</span> key)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> transformations, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">rep</span>(prob, <span class="dv">3</span>), <span class="at">y =</span> value, <span class="at">color =</span> transform_function)) <span class="sc">+</span> </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span><span class="sc">:</span><span class="dv">3</span>)) <span class="sc">+</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.5</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"original probabilities"</span>) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"transformed values"</span>) <span class="sc">+</span> </span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Possible transformations</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="st">          from probability scale"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>The logit is not the only invertible transformation from the probability interval to the entire real line, but it has several desirable properties.</p>
<p>From this plot, we can see that probabilities greater than 1/2 are mapped to positive logits and probabilities less than 1/2 are mapped to negative logits (remember <span class="math inline">\(p = 1/2 =&gt; odds = 1 =&gt; \log(odds) = 0\)</span>) so the sign of the logit of a probability has a straightforward interpretation – if the log-odds is positive, the event is more likely than not to occur.</p>
<p>In the context of our Donner problem, we can apply the logit function to the survival probability to get a new <strong>logistic regression</strong> model that might work better than the linear probability model we tried before. We’ll write the new model as:</p>
<p><span class="math display">\[\mathrm{logit}(P(Survived|Sex, Age)) = \beta_0 + \beta_1Age + \beta_2Sex + \beta_3Age \times Sex\]</span> That is, a non-linear function of survival probability is equal to the linear predictor.</p>
<p>The inverse of the logit function is called the <strong>logistic</strong> function. It looks like this:</p>
<p><span class="math display">\[f(x) = (e^x)/(1 + e^x)\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>logistic <span class="ot">&lt;-</span> <span class="cf">function</span>(x){<span class="fu">exp</span>(x)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(x))}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The logit and logistic function are inverses in the same way that the log and exponential functions are inverses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.7</span> <span class="co"># Start with a probability p</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>(lp <span class="ot">&lt;-</span> <span class="fu">logit</span>(p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8472979</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logistic</span>(lp) <span class="co"># Recover the original p</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">17</span> <span class="co"># Start with any real number</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>(lx <span class="ot">&lt;-</span> <span class="fu">logistic</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.139938e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logit</span>(lx) <span class="co"># Recover the original x</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -17</code></pre>
</div>
</div>
<p>Applying the logistic function to both sides of the model equation gives another equivalent way to write the model: <span class="math display">\[P(Survived|Sex, Age) = logistic(\beta_0 + \beta_1Age + \beta_2Sex + \beta_3Age \times Sex)\]</span> Hence the name “logistic regression”. Now we have survival probability on it’s own, but it’s equal to nonlinear function of the linear predictor.</p>
<p>We could also pull out the log from the logit (log-odds), and write the model as</p>
<p><span class="math display">\[odds(Survived|Sex, Age) = \exp{(\beta_0 + \beta_1Age + \beta_2Sex + \beta_3Age \times Sex)}\]</span> This leads to a useful interpretation. To see this, let’s drop back to a simpler logistic regression model with one predictor <span class="math inline">\(X\)</span> and a binary response <span class="math inline">\(Y\)</span>, where <span class="math inline">\(p = P(Y = 1)\)</span>. The equation for this simple model is</p>
<p><span class="math display">\[\log(p/(1 - p)) = \beta_0 + \beta_1X\]</span></p>
<p>if we exponentiate both sides to get back to the odds scale, we have</p>
<p><span class="math display">\[p/(1-p) = e^{\beta_0 + \beta_1X}\]</span></p>
<p>Let’s sort out what happens to <span class="math inline">\(\log(p/(1-p))\)</span> when <span class="math inline">\(X\)</span> changes by one:</p>
<p><span class="math inline">\([\beta_0 + \beta_1(X+1)] - [\beta_0 + \beta_1X] = \beta_1\)</span></p>
<p>So a one-unit increase in <span class="math inline">\(X\)</span> corresponds to a <span class="math inline">\(\beta_1\)</span>-unit change in the log odds. And, because we can exponentiate both sides, a one-unit increase in <span class="math inline">\(X\)</span> corresponds to a multiplicative change of <span class="math inline">\(e^{\beta_1}\)</span>. You already saw this result for the Donner Party data from the <em>Sleuth3</em> library, and we’ll give another example of interpreting logistic regression coefficients later in this lab.</p>
</section>
<section id="fitting-the-binary-logistic-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-binary-logistic-regression-model">Fitting the Binary Logistic Regression Model</h2>
<p>You already saw an R demonstration of the logistic regression model fit to the Donner Party data from the <em>Sleuth3</em> package. Let’s look at the model fit to the full Donner Party dataset in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>glm1 <span class="ot">=</span> <span class="fu">glm</span>(survived <span class="sc">~</span> sex <span class="sc">*</span> age, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), <span class="at">data =</span> Donner)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ sex * age, family = binomial(link = "logit"), 
    data = Donner)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  1.85515    0.67108   2.764   0.0057 **
sexMale     -1.62177    0.82673  -1.962   0.0498 * 
age         -0.04565    0.02480  -1.841   0.0657 . 
sexMale:age  0.01957    0.03120   0.627   0.5305   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 124.37  on 89  degrees of freedom
Residual deviance: 110.73  on 86  degrees of freedom
AIC: 118.73

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>It doesn’t look like the interaction term, <code>sexMale:age</code> is needed, so we’ll refit the model without it, and use that model to examine a few things and make interpretations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(survived <span class="sc">~</span> sex <span class="sc">+</span> age, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), <span class="at">data =</span> Donner)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ sex + age, family = binomial(link = "logit"), 
    data = Donner)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)   1.5992     0.5041   3.172  0.00151 **
sexMale      -1.2068     0.4790  -2.519  0.01176 * 
age          -0.0338     0.0151  -2.238  0.02525 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 124.37  on 89  degrees of freedom
Residual deviance: 111.13  on 87  degrees of freedom
AIC: 117.13

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>In the same way that we examined the (poor) fit of the multiple linear regression model above, let’s examine the (better) fit of this logistic regression model and see what we notice:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain 95% pointwise confidence bands from predict.glm()</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>glm_pred <span class="ot">&lt;-</span> <span class="fu">predict.glm</span>(glm2, <span class="at">type=</span><span class="st">"link"</span>, <span class="at">se.fit=</span><span class="cn">TRUE</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>low <span class="ot">&lt;-</span> glm_pred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> glm_pred<span class="sc">$</span>se.fit</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>upp <span class="ot">&lt;-</span> glm_pred<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> glm_pred<span class="sc">$</span>se.fit</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># back-transform everything to the data scale</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>glm_fit <span class="ot">&lt;-</span> <span class="fu">logistic</span>(glm_pred<span class="sc">$</span>fit)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>glm_lower <span class="ot">&lt;-</span> <span class="fu">logistic</span>(low)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>glm_upper <span class="ot">&lt;-</span> <span class="fu">logistic</span>(upp)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># augment the Donner data frame</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>augment_Donner <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(Donner, glm_fit, glm_lower, glm_upper))</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Big plot</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> augment_Donner) <span class="sc">+</span> </span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot jittered data</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> survived,</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex,</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shape =</span> sex),</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot fitted lines</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> glm_fit, </span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex)) <span class="sc">+</span> </span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 95% pointwise confidence bands</span></span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>                  <span class="at">fill =</span> sex, </span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymin =</span> glm_lower, </span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> glm_upper),</span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot reference lines at 0 and 1 (minimum and maximum possible probabilities)</span></span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>sex) <span class="sc">+</span> </span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Generalized linear model for Donner Party"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this plot, we show the fitted line for both males and females, and the 95% confidence bands for both. Just like our confidence bands from the linear model we fit before, these are <em>pointwise</em> confidence bands. They do not represent 95% confidence that the band contains the entire survival curve, only 95% confidence that the survival probability is within the band at each individual point. Simultaneous confidence bands for curves are much more theoretically challenging to construct than pointwise bands, but intuitively, a 95% simultaneous confidence band for the whole curve would be wider than the 95% pointwise band shown here. As explained above, prediction <em>intervals</em> do not make sense in principle for binary data, so we do not calculate any from this model.</p>
<p>Binary logistic regression models <em>can</em> be used as classifiers – where a new combination of explanatory information is mapped to a 0 or a 1. Recall from Data Analytics I that a prediction from a multiple linear regression model is our best guess at a new observation from a Normal population distribution, conditioned on specific, known values for the explanatory variables. In the present case, a prediction should be our best guess at a new observation (i.e., survived or died) from a <em>binary</em> distribution, conditioned on an age and a sex for a new individual (supposing we didn’t already know the survival status of all the possible Donner Party members). The predictive distribution for a new observation at each point is Bernoulli(p), where p is the fitted probability at the specific values of the new combination of explanatory information. Obtaining a new prediction at a given setting of the predictor variables involves either drawing from this Bernoulli distribution, or setting a probability threshold (typically 1/2) and predicting a value of 1 if the fitted probability exceeds the threshold, 0 otherwise. For example, you could predict that a man like Jacob Donner, age 65, would not survive according to the 1/2 probability threshold:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>like_Jacob_Donner <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="dv">65</span>, <span class="at">sex =</span> <span class="st">"Male"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>like_Jacob_Donner<span class="sc">$</span>age <span class="sc">%&lt;&gt;%</span> <span class="fu">as.numeric</span>()</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted probability that a 65 year old man would survive</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(glm2, <span class="at">newdata =</span> like_Jacob_Donner, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
0.141301 </code></pre>
</div>
</div>
<p>It’s really important to notice that neither the fitted lines nor the 95% pointwise confidence bands go outside the horizontal band given by the y = 0 and y = 1 lines. This is what we should expect – a much more satisfactory result from the logistic regression model than from the multiple linear regression model. Conceptually, this is because the logistic regression model is designed for modeling data such as those in the Donner Party example, where the response variable is binary. Mathematically, it is because the logistic function that maps the fitted values and confidence bounds back from the log-odds scale to the probability scale is only capable of outputting values between 0 and 1.</p>
</section>
<section id="assessing-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="assessing-model-fit">Assessing Model Fit</h2>
<p>In the case of binary responses, it’s not necessary or even all that meaningful to examine residuals. Since the only response values are 0’s and 1’s, and the fitted values (once we back transform to the data scale) are probabilities, there is not a wide range of possible values for the residuals and they tend to be not very informative.</p>
<p>In the case of the Donner Party data, and as you can see from the plot above, the model fit is not terrific. For example, the model did not seem to pick up the “sweet spot” we noted earlier – females between the ages of about 5 and 25 seem to have all survived. Perhaps a more curvy or wiggly function would provide a better fit? Consider the following plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> augment_Donner) <span class="sc">+</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot jittered data</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> survived,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shape =</span> sex),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># plot loess smoother</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, </span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> survived,</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> sex)) <span class="sc">+</span> </span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_grid</span>(.<span class="sc">~</span>sex) <span class="sc">+</span> </span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Loess Smooth for Donner Party"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="z3_learnR_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The loess smoother that <code>ggplot()</code> used to fit a line and plot confidence bands is called a non-parametric scatterplot smoother. It does seem that these non-monotonic wiggly lines do a better job of modeling survival probability as a function of age, although both the fitted line and 95% confidence bands go outside of the 0 and 1 boundaries, which is troubling.</p>
<p>Unfortunately, the details of loess and other non-parametric approaches are beyond the scope of this class. A <em>big drawback</em> to this non-parametric model fit, however, is that we can’t make any inferences about the relationships among age, sex and survival from it. That is, all we have is the plot above and a wiggly fitted line which we <em>could</em> use to make predictions. For all our talk about the process of making predictions from a logistic regression model, we can’t actually make much use of a purely predictive model for these particular data – whose survival are we to predict, anyway?!</p>
<p>Instead, we’ll go back to our imperfect logistic regression model and make inferences about the relationships among sex, age and survival using that model. There’s a famous quote, attributed to George Box (1919-2013), a well-respected British statistician who spent a large part of his academic career in the US:</p>
<blockquote class="blockquote">
<p>“All models are wrong, but some are useful.”</p>
</blockquote>
<p>This is certainly the case with our logistic regression model. It may not be the “correct” model, or even the “best” one for the Donner Party data (you might try adding a quadratic term in age and see if that looks better than either of the preceding approaches). Nevertheless, we can use it to make some useful statements about the data.</p>
</section>
<section id="interpreting-the-fitted-model" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-fitted-model">Interpreting The Fitted Model</h2>
<p>Let’s look again at the summary information from the logistic regression model we fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ sex + age, family = binomial(link = "logit"), 
    data = Donner)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)   1.5992     0.5041   3.172  0.00151 **
sexMale      -1.2068     0.4790  -2.519  0.01176 * 
age          -0.0338     0.0151  -2.238  0.02525 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 124.37  on 89  degrees of freedom
Residual deviance: 111.13  on 87  degrees of freedom
AIC: 117.13

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>It appears that both age and sex are important for helping us to understand the odds of survival using this model. Since <code>sexMale</code> is an indicator function, we can write the fitted model in two parts, one for females:</p>
<p>log(odds of survival) = 1.60 - 0.03age.</p>
<p>And one for males:</p>
<p>log(odds of survival) = 0.39 - 0.03age.</p>
<p>In this second sub-model, 0.3924 = 1.5992 - 1.2068, and we rounded to the hundredths to get 0.39.</p>
<p>It’s from these model fits that we can obtain some estimate of the relative odds of survival for men and women of the same age. As you saw in the narrated lecture materials, because there’s no interaction term in this model, we can just exponentiate the coefficient on sexMale (-1.2068) and obtain an estimate of the multiplicative difference in odds of survival for a male and female of the same age. We can also exponentiate the upper and lower bounds of the 95% confidence interval for the regression coefficient on sexMale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.2068</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.299153</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(glm2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %     97.5 %
(Intercept) 1.9486563 14.3550499
sexMale     0.1128658  0.7481205
age         0.9367677  0.9945734</code></pre>
</div>
</div>
<p>The odds of survival for a male are estimated to be roughly 30% of the odds of survival for a female, when comparing individuals of the same age (remember this is exactly the result we got from the contingency table when we ignored <code>age</code>, because in our final logistic regression model we’ve decided not to include any interaction between <code>age</code> and <code>sex</code>). A 95% confidence interval for this multiplicative difference runs from 11% to 75%.</p>
<p>You can also use the logistic back-transformation to make a comparison in terms of the probability of survival:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logistic</span>(<span class="sc">-</span><span class="fl">1.2068</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2302677</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logistic</span>(ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 0.6608625 0.9348748
sexMale     0.1014191 0.4279571
age         0.4836758 0.4986397</code></pre>
</div>
</div>
<p>The probability of survival for a male is estimated to be 0.23 lower than that of a female, when comparing two individuals of the same age. A 95% confidence interval for this (additive) difference runs from 0.10 to 0.43.</p>
</section>
<section id="data-scale-vs-model-scale-back-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-scale-vs-model-scale-back-transformation">Data Scale vs Model Scale, Back-transformation</h2>
<p>Notice that the two interpretations just given are both on back-transformed scales. In general, people have a better appreciation for and understanding of probabilities and odds than they do (have) of log-odds.</p>
<blockquote class="blockquote">
<p>The logistic regression model is fit on the log-odds scale – we call this the model scale. When we back-transform to probabilities, we get back to the data scale (i.e., the same scale as the data).</p>
</blockquote>
<p>The odds scale is intermediate between the the data scale and the model scale, and it affords another option for how we interpret and communicate the results of a logistic regression model.</p>
</section>
</section>
<section id="module-3-lab-assignment-instructions" class="level1">
<h1>Module 3 Lab Assignment Instructions</h1>
<p>You are again asked to create a <strong>self-contained</strong> R Markdown script that can generate a document which answers the questions below. You will submit the .Rmd script, and the .pdf document produced by knitting the script.</p>
<section id="r-markdown-for-submission" class="level2">
<h2 class="anchored" data-anchor-id="r-markdown-for-submission">R Markdown for submission</h2>
<p>Last week’s instructions are repeated here for your convenience.</p>
<p><strong>NOTE:</strong> <em>If you are reading these instructions from the HTML preview in the Viewer pane, they will be overwritten in the following steps. You can avoid this by “popping out” the current HTML preview into an external browser window, by clicking the the “Show in new window” icon (to the right of the broom icon in the Viewer pane).</em></p>
<p><em>Alternatively, you can read the instructions right from the .Rmd script, keeping in mind that you will need to switch back to the lab script tab to view the rest of the instructions once you create a new script. You could also copy and paste the whole Lab 3 Assignment Instructions section into your new document while you’re working on it, and then delete the instructions before you submit it.</em></p>
<p>Click “File” -&gt; “New File” -&gt; “R Markdown”, and dialog box will pop up. Change the title to “Lab Assignment 3” and name yourself as author. Select PDF as the Default Output Format, then click OK. The header of your new file should look something like this:</p>
<pre><code>---
title: "Lab Assignment 3"
author: "Ronald Fisher"
date: "2024-04-04"
output: pdf_document
---</code></pre>
<p>The file will initially contain some examples to get you started with RMarkdown, which you should replace with your lab content. Save the notebook as something like “Lab_Assignment_3” using “File” –&gt; “Save As…”</p>
<p>In your new .Rmd script, answer the questions in the “Questions” section below. Include all the code you need to produce the requested outputs. Your script should include a top-level section heading for each question, for example:</p>
<pre><code># Question 1

stuff here

# Question 2

other stuff</code></pre>
<p>Whether or not you include the text of the questions in your script is up to you.</p>
<blockquote class="blockquote">
<p>Do be sure to include, near the top of your script, a code chunk that loads any non-default packages you use (such as <em>vcdExtra</em> or <em>Sleuth3</em>).</p>
</blockquote>
<p>Within the question sections, you can chunk your code in whatever way seems reasonable. Incorporate any written answers outside the code chunks using Markdown formatting as needed (see “Help” -&gt; “RMarkdown Quick Reference” for text formatting help).</p>
<p>To ensure that your .Rmd script will be fully self-contained (i.e.&nbsp;it will not depend on objects that were defined during the lab, and could be run as-is if you sent it to someone else), you should <strong>clear the workspace</strong> before you begin.</p>
<blockquote class="blockquote">
<p>To clear the workspace, click the broom icon in the Environment pane.</p>
</blockquote>
<p>Once you’ve answered the questions in your new .Rmd script and you have verified your code is self contained, you should Run -&gt; Run All Chunks and generate a .pdf file of your document, to check that everything looks like you want it to. Having concluded that your .Rmd script produces a pdf document that includes all the output you want, submit <strong>both the Lab_Assignment_3.Rmd file and the pdf document</strong> on Canvas as your Lab Assignment 3.</p>
<p>Feel free to post on the discussion board if you have any questions or encounter any difficulties with this process.</p>
</section>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<p>The data set <code>ResumeNames</code> in the <em>AER</em> package contains information about 4870 fictitious resumes, sent to real employers as part of an experiment about racial discrimination in hiring. The binary response for each resume is whether the employer called back. Although the original research question was about racial discrimination, there are many kinds of questions you might answer using these data.</p>
<ol type="1">
<li><p>Install and load the <em>AER</em> package, and read the help file for the <code>ResumeNames</code> data.</p></li>
<li><p>Come up with a question about the probability of <code>callback</code> (the binary response) that can be answered using at least one (but no more than 5) of the 26 available predictor variables.</p></li>
</ol>
<p>Consider: - Restricting your analysis to an interesting subset of the data - Transforming and combining input variables - Exploring interactions</p>
<p>Some example questions (which you may use or modify if you want)</p>
<ul>
<li><p>(How) does the relationship between callback probability and resume quality differ by applicant race?</p></li>
<li><p>How many additional years of experience is having a white name vs a black name “worth” in terms of callback probability?</p></li>
<li><p>Does callback probability differ between applicants who meet stated job requirements and applicants who don’t? For instance, you might compare applicants who do or not meet the stated minimum number of years of experience, or applicants who do or do not list computer skills when applying to jobs for which computer skills are ostensibly required.</p></li>
<li><p>Does callback probability differ between male and female applicants by industry or position?</p></li>
</ul>
<p>Be creative!</p>
<ol start="3" type="1">
<li>Use a logisitic regression model to address the question you posed in 2. Be sure to examine the fit of your model, and write a few sentences about your interpretation of the model as it addresses the question you posed.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>