<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data_Analysis_II_Notes - LearnR 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data_Analysis_II_Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notes" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notes">    
        <li>
    <a class="dropdown-item" href="./1_Types_of_Categoricals.html" rel="" target="">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_Props_Risks_Odds.html" rel="" target="">
 <span class="dropdown-text">2 Props, Risk &amp; Odds</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./3_Logistic_Regression_I.html" rel="" target="">
 <span class="dropdown-text">3 Log Reg I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./4_Logistic_Regression_II.html" rel="" target="">
 <span class="dropdown-text">4 Log-Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./5_Log_linear_Regression.html" rel="" target="">
 <span class="dropdown-text">5 Log-lin-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./6_Dispersion_Zero_Inflation.html" rel="" target="">
 <span class="dropdown-text">6 Disp &amp; 0 Inflation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./7_Random_Effects.html" rel="" target="">
 <span class="dropdown-text">7 Random_Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./8_Evaluating_Models.html" rel="" target="">
 <span class="dropdown-text">8 Model Eval</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./9_Imp_Pred_Validate.html" rel="" target="">
 <span class="dropdown-text">9 Imp, Pred, Validate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_Final_Project.html" rel="" target="">
 <span class="dropdown-text">10 Final Project</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./z0_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z1_learnR.html" rel="" target="">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z2_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z3_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z4_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z5_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z6_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z7_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z8_learnR.html" rel="" target="">
 <span class="dropdown-text">LearnR 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hw" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">HW</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hw">    
        <li>
    <a class="dropdown-item" href="./aHW_1.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_2.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_3.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_4.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_5.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_6.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_7.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_8.html" rel="" target="">
 <span class="dropdown-text">ST-518 HW 8</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#count-responses" id="toc-count-responses" class="nav-link active" data-scroll-target="#count-responses">Count responses</a></li>
  <li><a href="#binomial-logistic-regression" id="toc-binomial-logistic-regression" class="nav-link" data-scroll-target="#binomial-logistic-regression">Binomial logistic regression</a>
  <ul class="collapse">
  <li><a href="#aflatoxin-data" id="toc-aflatoxin-data" class="nav-link" data-scroll-target="#aflatoxin-data">Aflatoxin data</a></li>
  <li><a href="#binary-vs-binomial" id="toc-binary-vs-binomial" class="nav-link" data-scroll-target="#binary-vs-binomial">Binary vs binomial</a>
  <ul class="collapse">
  <li><a href="#modeling-a-binomial-count-for-each-tank" id="toc-modeling-a-binomial-count-for-each-tank" class="nav-link" data-scroll-target="#modeling-a-binomial-count-for-each-tank">Modeling a binomial count for each tank</a></li>
  <li><a href="#modeling-a-binary-outcome-for-each-fish" id="toc-modeling-a-binary-outcome-for-each-fish" class="nav-link" data-scroll-target="#modeling-a-binary-outcome-for-each-fish">Modeling a binary outcome for each fish</a></li>
  <li><a href="#modeling-as-binomial-counts-within-each-dose" id="toc-modeling-as-binomial-counts-within-each-dose" class="nav-link" data-scroll-target="#modeling-as-binomial-counts-within-each-dose">Modeling as binomial counts within each Dose</a></li>
  <li><a href="#ok-so-now-what" id="toc-ok-so-now-what" class="nav-link" data-scroll-target="#ok-so-now-what">Ok, so now what?!</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model-fit-and-model-comparison" id="toc-model-fit-and-model-comparison" class="nav-link" data-scroll-target="#model-fit-and-model-comparison">Model fit and model comparison</a>
  <ul class="collapse">
  <li><a href="#empirical-logits" id="toc-empirical-logits" class="nav-link" data-scroll-target="#empirical-logits">Empirical logits</a></li>
  <li><a href="#deviance-goodness-of-fit" id="toc-deviance-goodness-of-fit" class="nav-link" data-scroll-target="#deviance-goodness-of-fit">Deviance goodness of fit</a></li>
  <li><a href="#drop-in-deviance-test" id="toc-drop-in-deviance-test" class="nav-link" data-scroll-target="#drop-in-deviance-test">Drop-in-deviance test</a></li>
  <li><a href="#information-criteria-for-model-comparison" id="toc-information-criteria-for-model-comparison" class="nav-link" data-scroll-target="#information-criteria-for-model-comparison">Information criteria for model comparison</a></li>
  <li><a href="#deviance-residuals-pearson-residuals---dispersion-parameter-estimated-from-pearson-chi-squared" id="toc-deviance-residuals-pearson-residuals---dispersion-parameter-estimated-from-pearson-chi-squared" class="nav-link" data-scroll-target="#deviance-residuals-pearson-residuals---dispersion-parameter-estimated-from-pearson-chi-squared">Deviance residuals, Pearson residuals - dispersion parameter estimated from Pearson – chi squared</a></li>
  </ul></li>
  <li><a href="#dealing-with-over-dispersion" id="toc-dealing-with-over-dispersion" class="nav-link" data-scroll-target="#dealing-with-over-dispersion">Dealing with over-dispersion</a></li>
  <li><a href="#a-pitfall-perfect-separation" id="toc-a-pitfall-perfect-separation" class="nav-link" data-scroll-target="#a-pitfall-perfect-separation">A Pitfall – perfect separation</a></li>
  <li><a href="#test-for-difference-in-proportions" id="toc-test-for-difference-in-proportions" class="nav-link" data-scroll-target="#test-for-difference-in-proportions">Test for difference in proportions</a></li>
  <li><a href="#lab-4-assignment" id="toc-lab-4-assignment" class="nav-link" data-scroll-target="#lab-4-assignment">Lab 4 Assignment</a>
  <ul class="collapse">
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question">Question</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">LearnR 4</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="count-responses" class="level1">
<h1>Count responses</h1>
<p>Please load these libraries that you’ll need for this lab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'arm' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
arm (Version 1.14-4, built: 2024-4-1)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Working directory is C:/Users/cmeck/Desktop/D_Anal/Anal_II/Anal_II_Notes/Data_Analysis_II_Notes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Sleuth3)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::expand() masks Matrix::expand()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ tidyr::pack()   masks Matrix::pack()
✖ dplyr::select() masks MASS::select()
✖ tidyr::unpack() masks Matrix::unpack()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'vcdExtra' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: vcd</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'vcd' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: grid
Loading required package: gnm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gnm' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'vcdExtra'

The following object is masked from 'package:dplyr':

    summarise</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'magrittr'

The following object is masked from 'package:purrr':

    set_names

The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
</div>
<p>In this lab, we’ll go over some of the finer details of binomial logistic regression that you only saw briefly in the narrated lectures. We’ll cover the drop in deviance and deviance goodness of fit tests, and show how to perform them using R. We’ll also talk more about residuals from binomial logistic regression and about the dispersion parameter and over dispersion. Two additional topics are (1) a pathological (but not altogether rare) situation that can arise in logistic regression and (2) using logistic regression to perform a test of the difference in two proportions.</p>
</section>
<section id="binomial-logistic-regression" class="level1">
<h1>Binomial logistic regression</h1>
<p>In the previous lab, we introduced binary logistic regression in the context of a continuous explanatory variable (age). In this situation, each individual could, in principle, have had a unique combination of values of the explanatory variables. In practice, due to rounding of ages to whole years, there were several explanatory variable combinations that occurred multiple times (this was why we had to jitter the plot of survival vs age). For those particular combinations of the explanatory variables, we could count up the number of Donner party survivors and non-survivors – so we’d have a count as the response, rather than a binary observations.</p>
<p>We are typically still inclined to think of the survival of <em>individual</em> Donner Party members, however; rather than in terms of the <em>count</em> of survivors out of the total number of members at each age-sex combination.</p>
<p>In this lab, we take a different perspective on logistic regression. We consider binary observations that are clustered into groups, where the <em>counts</em> of outcomes in each group are the natural measurements of interest. We consider each count to have a <em>binomial</em> distribution with some probability <span class="math inline">\(p\)</span>, and derive the log-odds from these binomial probabilities. Since a binomial <span class="math inline">\(p\)</span> comes from an underlying Bernoulli <span class="math inline">\(p\)</span> (or since a Bernoulli is a special case of a binomial), however, logistic regressions for binary outcomes and binomial counts are not fundamentally different beasts – they use the same model equations, they are fit with the same R function, they estimate the same parameters, and they rely on the same assumptions. Using binomial logistic regression when applicable, though, makes <em>checking</em> some of those assumptions more direct.</p>
<section id="aflatoxin-data" class="level2">
<h2 class="anchored" data-anchor-id="aflatoxin-data">Aflatoxin data</h2>
<p>In this lab we will continue with the <code>ex2116</code> data from <em>Sleuth3</em>, introduced in lecture. Each of 20 tanks was stocked with fishes that had been exposed as embryos to one of 5 doses of a carcinogen. When the fishes were dissected a year later, the number of fishes that had developed liver tumors was recorded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ex2116)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>tumors <span class="ot">&lt;-</span> ex2116</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tumors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Dose</th>
<th style="text-align: right;">Tumor</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">87</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">86</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">89</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">86</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">86</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Here we’ll add a column that records the number of fish in each tank which did not develop liver tumors, and a column that assigns a unique label to each of the 20 tanks. We’ll also add a column for log(Dose) and log(Dose)^2 since we used those as explanatory variables in the model you saw in the narrated lectures.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tumors <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(<span class="at">Dose =</span> Dose, <span class="at">Tumor =</span> Tumor, <span class="at">NoTumor =</span> Total <span class="sc">-</span> Tumor, <span class="at">TankID =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(tumors)),<span class="at">logDose =</span> <span class="fu">log</span>(Dose), <span class="at">logDose2 =</span> <span class="fu">log</span>(Dose)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tumors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Dose</th>
<th style="text-align: right;">Tumor</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">NoTumor</th>
<th style="text-align: left;">TankID</th>
<th style="text-align: right;">logDose</th>
<th style="text-align: right;">logDose2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">78</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">81</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">76</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">56</td>
<td style="text-align: left;">5</td>
<td style="text-align: right;">-3.68888</td>
<td style="text-align: right;">13.60783</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">45</td>
<td style="text-align: left;">6</td>
<td style="text-align: right;">-3.68888</td>
<td style="text-align: right;">13.60783</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We’ll also create a case-format version that records the binary status (tumor or not) for each of the 1739 individual fishes.<br>
# check code tumors_case$Outcome should be a factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The syntax dplyr::select() ensures that the select() function from the dplyr package is </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># used instead of the select() function from the MASS package, in case you still have MASS</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># loaded in the library.</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>tumors_freq <span class="ot">&lt;-</span> tumors <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Total) <span class="sc">%&gt;%</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(Tumor<span class="sc">:</span>NoTumor,<span class="at">names_to=</span><span class="st">"Outcome"</span>,<span class="at">values_to=</span><span class="st">"Freq"</span>,<span class="at">cols_vary =</span> <span class="st">"slowest"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Outcome=</span><span class="fu">as.factor</span>(Outcome))</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>tumors_case <span class="ot">&lt;-</span> <span class="fu">expand.dft</span>(tumors_freq) <span class="sc">%&gt;%</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Outcome=</span><span class="fu">as.factor</span>(Outcome))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tumors_case)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Dose</th>
<th style="text-align: right;">TankID</th>
<th style="text-align: right;">logDose</th>
<th style="text-align: right;">logDose2</th>
<th style="text-align: left;">Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
<td style="text-align: left;">Tumor</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
<td style="text-align: left;">Tumor</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
<td style="text-align: left;">Tumor</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
<td style="text-align: left;">Tumor</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
<td style="text-align: left;">Tumor</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.60517</td>
<td style="text-align: right;">21.20759</td>
<td style="text-align: left;">Tumor</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>(With most of the lab examples so far oriented around examples of death, discrimination, and disease, you might accuse us statisticians of attempting to usurp from economics the title of “dismal science”! (Economists think <em>they’re</em> pessimists – what they call “maximizing utility”, statisticians call “minimizing loss”). We promise nobody dies in the next lab. Probably.</p>
</section>
<section id="binary-vs-binomial" class="level2">
<h2 class="anchored" data-anchor-id="binary-vs-binomial">Binary vs binomial</h2>
<p>There are several equivalent ways of fitting a logistic regression model with <code>glm()</code> to data such as the <code>ex2116</code> data. We will see why the fitting methods that preserve information about the counts within each tank are preferable for our purposes.</p>
<section id="modeling-a-binomial-count-for-each-tank" class="level3">
<h3 class="anchored" data-anchor-id="modeling-a-binomial-count-for-each-tank">Modeling a binomial count for each tank</h3>
<p>First, the response can be specified as a 2-column matrix containing counts of successes in the first column and counts of failures in the second.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, <span class="fu">cbind</span>(Tumor, NoTumor) <span class="sc">~</span> logDose <span class="sc">+</span> logDose2, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Tumor, NoTumor) ~ logDose + logDose2, family = "binomial", 
    data = tumors)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.02921    0.49343   2.086  0.03699 *  
logDose     -1.03048    0.35743  -2.883  0.00394 ** 
logDose2    -0.39195    0.06136  -6.388 1.68e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 667.195  on 19  degrees of freedom
Residual deviance:  26.048  on 17  degrees of freedom
AIC: 119.45

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The response can also be specified as a vector of <em>proportions</em> of successes in each group, with the total in each group given through the <code>weights</code> argument:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, Tumor<span class="sc">/</span>Total <span class="sc">~</span> logDose <span class="sc">+</span> logDose2, <span class="at">weights =</span> Total, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Tumor/Total ~ logDose + logDose2, family = "binomial", 
    data = tumors, weights = Total)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.02921    0.49343   2.086  0.03699 *  
logDose     -1.03048    0.35743  -2.883  0.00394 ** 
logDose2    -0.39195    0.06136  -6.388 1.68e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 667.195  on 19  degrees of freedom
Residual deviance:  26.048  on 17  degrees of freedom
AIC: 119.45

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Be sure to verify that <code>mod1</code> and <code>mod2</code> are equivalent.</p>
</section>
<section id="modeling-a-binary-outcome-for-each-fish" class="level3">
<h3 class="anchored" data-anchor-id="modeling-a-binary-outcome-for-each-fish">Modeling a binary outcome for each fish</h3>
<p>We have converted the data to case format, where each row contains an individual binary outcome corresponding to an individual fish. These outcomes can be modeled directly, just as we saw with the (ungrouped) Donner data in Lab 3.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors_case, Outcome <span class="sc">~</span> logDose <span class="sc">+</span> logDose2, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Outcome ~ logDose + logDose2, family = "binomial", 
    data = tumors_case)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.02921    0.49341   2.086  0.03698 *  
logDose     -1.03048    0.35740  -2.883  0.00394 ** 
logDose2    -0.39195    0.06135  -6.388 1.68e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2395.8  on 1738  degrees of freedom
Residual deviance: 1754.7  on 1736  degrees of freedom
AIC: 1760.7

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Make a quick comparison of the coefficient estimates from <code>mod2</code> and <code>mod3</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coefficients</span>(mod2),<span class="fu">coefficients</span>(mod3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  [,1]      [,2]
(Intercept)  1.0292126  1.029213
logDose     -1.0304804 -1.030480
logDose2    -0.3919491 -0.391949</code></pre>
</div>
</div>
<p>The two models give the same coefficient estimates, and you can also verify that the corresponding standard errors are the same. Therefore, in terms of inferences about the regression coefficients, treating the data as binary (one 0/1 outcome for each fish) or binomial (one count outcome for each tank) doesn’t <em>seem</em> to matter.</p>
<p>But, let’s remember that when we looked at the binomial logistic regression model in class, we noticed some over dispersion in the counts. We’ll first examine one more approach to modeling the binomial counts, and then turn to talking about the over dispersion.</p>
</section>
<section id="modeling-as-binomial-counts-within-each-dose" class="level3">
<h3 class="anchored" data-anchor-id="modeling-as-binomial-counts-within-each-dose">Modeling as binomial counts within each Dose</h3>
<p>Note that “TankID” is not a term in any of the models we fit above. The binomial logistic models treat the 4 tanks in each of the 5 dose groups as independent binomial observations – within each <code>Dose</code> level, the 4 tanks are supposed to be draws from 4 independent binomial random variables, with potentially different <span class="math inline">\(n\)</span> (different number of fish in each tank) but all with the same <span class="math inline">\(p\)</span>. In the binary logistic model, the tanks are ignored and the fish-level outcomes are treated as independent Bernoulli random variables, with a common <span class="math inline">\(p\)</span> at each <code>Dose</code>. In either form, a single <span class="math inline">\(p\)</span> applies to every fish in the <code>Dose</code> level, regardless of tank. Indeed, we can explicitly collapse across the tanks before fitting the model, without affecting any of the inferences:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>(summed_tumor <span class="ot">&lt;-</span> <span class="fu">summarize</span>(<span class="fu">group_by</span>(tumors, Dose, logDose, logDose2), <span class="fu">sum</span>(Tumor), <span class="fu">sum</span>(NoTumor)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Dose', 'logDose'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Dose</th>
<th style="text-align: right;">logDose</th>
<th style="text-align: right;">logDose2</th>
<th style="text-align: right;">sum(Tumor)</th>
<th style="text-align: right;">sum(NoTumor)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">-4.605170</td>
<td style="text-align: right;">21.207592</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">322</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">-3.688880</td>
<td style="text-align: right;">13.607832</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">214</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">-2.995732</td>
<td style="text-align: right;">8.974412</td>
<td style="text-align: right;">226</td>
<td style="text-align: right;">127</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.100</td>
<td style="text-align: right;">-2.302585</td>
<td style="text-align: right;">5.301898</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">74</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-1.386294</td>
<td style="text-align: right;">1.921812</td>
<td style="text-align: right;">286</td>
<td style="text-align: right;">52</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Notice that we’ve now reduced the dataset down to five observations! And now we’ll fit the model to these summed responses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> summed_tumor, <span class="fu">cbind</span>(<span class="st">`</span><span class="at">sum(Tumor)</span><span class="st">`</span>, <span class="st">`</span><span class="at">sum(NoTumor)</span><span class="st">`</span>) <span class="sc">~</span> logDose <span class="sc">+</span> logDose2, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(`sum(Tumor)`, `sum(NoTumor)`) ~ logDose + 
    logDose2, family = "binomial", data = summed_tumor)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.02921    0.49343   2.086  0.03699 *  
logDose     -1.03048    0.35743  -2.883  0.00394 ** 
logDose2    -0.39195    0.06136  -6.388 1.68e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 641.234089  on 4  degrees of freedom
Residual deviance:   0.086879  on 2  degrees of freedom
AIC: 35.091

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>And compare coefficient estimates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coefficients</span>(mod2),<span class="fu">coefficients</span>(mod3),<span class="fu">coefficients</span>(mod4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  [,1]      [,2]       [,3]
(Intercept)  1.0292126  1.029213  1.0292126
logDose     -1.0304804 -1.030480 -1.0304804
logDose2    -0.3919491 -0.391949 -0.3919491</code></pre>
</div>
</div>
<p>And once again you can verify that all of the corresponding standard errors are also the same. So what’s going on here, and which of these models is “the best one” to use?</p>
</section>
<section id="ok-so-now-what" class="level3">
<h3 class="anchored" data-anchor-id="ok-so-now-what">Ok, so now what?!</h3>
<p>The parameter estimates and standard errors are all identical – we reach the same conclusions from each model. But let’s look at the residual deviances for each of the models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">deviance</span>(mod2),<span class="fu">deviance</span>(mod3),<span class="fu">deviance</span>(mod4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]     [,2]       [,3]
[1,] 26.04806 1754.692 0.08687945</code></pre>
</div>
</div>
<p>It’s also important to recognize that in <code>mod2</code>, <code>mod3</code> and <code>mod4</code>, the sample sizes are n = 20, n = 1739 and n = 5, respectively. And, the null deviances for each model are also substantially different; again in order of <code>mod2</code>, <code>mod3</code> and <code>mod4</code> these are 667.20, 2395.84 and 641.23. The <em>difference</em> in deviance (the deviance accounted for by a model), however, is the same for every form of the model.</p>
<p>To see more plainly that the methods above are equivalent, we can view minimal summaries from each using the <code>display()</code> function from <em>arm</em>. The abbreviated output (compared to <code>summary</code>) facilitates comparison between several models on the same page.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># counts in tanks</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = Tumor/Total ~ logDose + logDose2, family = "binomial", 
    data = tumors, weights = Total)
            coef.est coef.se
(Intercept)  1.03     0.49  
logDose     -1.03     0.36  
logDose2    -0.39     0.06  
---
  n = 20, k = 3
  residual deviance = 26.0, null deviance = 667.2 (difference = 641.1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># binary outcomes per fish</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = Outcome ~ logDose + logDose2, family = "binomial", 
    data = tumors_case)
            coef.est coef.se
(Intercept)  1.03     0.49  
logDose     -1.03     0.36  
logDose2    -0.39     0.06  
---
  n = 1739, k = 3
  residual deviance = 1754.7, null deviance = 2395.8 (difference = 641.1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># counts in dose level ignoring tanks</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = cbind(`sum(Tumor)`, `sum(NoTumor)`) ~ logDose + 
    logDose2, family = "binomial", data = summed_tumor)
            coef.est coef.se
(Intercept)  1.03     0.49  
logDose     -1.03     0.36  
logDose2    -0.39     0.06  
---
  n = 5, k = 3
  residual deviance = 0.1, null deviance = 641.2 (difference = 641.1)</code></pre>
</div>
</div>
<p>All the same assumptions go into each of these ways of fitting the models, and all the same inferences come out. In particular, we are always assuming that once we know the <code>Dose</code> a fish received, knowing the particular <em>tank</em> in which that fish was housed cannot give us any more information about that fish’s chance of having a tumor – not even if we know that the fish came from a tank in which an especially large (or small) number of <em>other</em> fish got tumors, compared to other tanks within the same dose level. In the binomial-tank-counts model, this assumption reads like “every binomial within a dose level has the same <span class="math inline">\(p\)</span>.” In the binary-fish model, it reads “every Bernoulli within a dose level has the same <span class="math inline">\(p\)</span>.” In the binomial-dose-count model, it reads “the Bernoulli’s across all tanks within a dose must be independent.” We could call this the assumption of “irrelevant groups (tanks).”</p>
<p>If we have some grouping at all, however, we often suspect that this last assumption about independence is not sound. Fish in the same tank are expected to be more similar to one another than fish in different tanks. That is, we should <em>not</em> expect same binomial <span class="math inline">\(p\)</span> in every tank, nor should we suppose that all the Bernoulli responses in a dose level are independent, regardless of tank.</p>
<p>In what follows, we will see that fitting the model in the “tank-count” binomial form, as opposed to per-fish binary form or the dose-count binomial form, is the way that will allow us to <em>check</em> whether the group-irrelevance of assumption is reasonable. We’ll see that <em>not</em> making this assumption comes with a steep price, and preview another technique that will sometimes allow us to avoid paying it.</p>
</section>
</section>
</section>
<section id="model-fit-and-model-comparison" class="level1">
<h1>Model fit and model comparison</h1>
<p>In the binary logistic case, there was little we could do to directly assess model fit. You could try squinting at some residual plots, but that’s about it. The single binary outcomes just bounce around too much to say of anything about what the fitted line “should have done” at any given predictor value – it certainly should not chase every individual 1 or 0. To get some stability, you need to be able to put multiple observations within the same “bin”, so that you can say whether the proportion (or log-odds) in that bin is close to what the model predicts.</p>
<section id="empirical-logits" class="level2">
<h2 class="anchored" data-anchor-id="empirical-logits">Empirical logits</h2>
<p>The empirical logit is just the logit transformation applied to the proportion within a bin (this isn’t the log-odds of the <em>probability</em> within the bin, it’s just an estimate based on the observed proportion – hence “empirical”).</p>
<p>Remember the logit transformation of a proportion/probability is given by <code>qlogis()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>empirical_logits <span class="ot">&lt;-</span> <span class="fu">with</span>(tumors, <span class="fu">qlogis</span>(Tumor<span class="sc">/</span>Total))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We plot the empirical logits against <code>Dose</code> to see the shape of the relationship we’re trying to capture on the log-odds scale, along with a loess smooth.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tumors, <span class="fu">aes</span>(<span class="at">x =</span> Dose, <span class="at">y =</span> empirical_logits))<span class="sc">+</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.005</span>, <span class="at">height =</span> <span class="fl">0.01</span>) <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Empirical Logits vs Dose"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This appearance of a logarithmic relationship between the Dose and the logits prompts the a log-transformation of the dose to straighten it out (that is, it suggests that the <em>odds</em> of tumor are nearly linear in dose).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tumors, <span class="fu">aes</span>(<span class="at">x =</span> logDose, <span class="at">y =</span> empirical_logits)) <span class="sc">+</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Empirical Logits vs log(Dose)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot suggests that a logistic regression model which includes both <code>log(Dose)</code> and <code>log(Dose)^2</code> would be appropriate to capture the observed trend in the empirical logits. Unlike with binary logistic regression, the binomial model lets us measure the lack-of-fit to a proposed model, and compare the fit between models.</p>
</section>
<section id="deviance-goodness-of-fit" class="level2">
<h2 class="anchored" data-anchor-id="deviance-goodness-of-fit">Deviance goodness of fit</h2>
<p>Recall that the deviance goodness of fit test compares a fitted model to a saturated model, or one in which there are as many parameters as there are data points. In these goodness of fit comparisons, the null hypothesis corresponds to the fitted model (which is a reduced model relative to the saturated model), and the alternative hypothesis corresponds to the saturated model. Therefore, a small p-value indicating evidence for rejection of the fitted model in favor of the saturated model is evidence of <em>lack of fit</em>.</p>
<p>The <code>LRstats()</code> from <em>vcdExtra</em> function shows a convenient summary of the fits of one or more model objects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, (Tumor<span class="sc">/</span>Total) <span class="sc">~</span> Dose, <span class="at">weights =</span> Total, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>mod6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, (Tumor<span class="sc">/</span>Total) <span class="sc">~</span> logDose, <span class="at">weights =</span> Total, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>mod7 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, (Tumor<span class="sc">/</span>Total) <span class="sc">~</span> logDose <span class="sc">+</span> logDose2, <span class="at">weights =</span> Total, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(mod5, mod6, mod7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod5</td>
<td style="text-align: right;">368.4449</td>
<td style="text-align: right;">370.4364</td>
<td style="text-align: right;">277.04682</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod6</td>
<td style="text-align: right;">160.2947</td>
<td style="text-align: right;">162.2862</td>
<td style="text-align: right;">68.89661</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mod7</td>
<td style="text-align: right;">119.4461</td>
<td style="text-align: right;">122.4333</td>
<td style="text-align: right;">26.04806</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.0735894</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The <code>LR Chisq</code> is the residual deviance, which is the sum of the squared deviance residuals. For instance, for <code>mod5</code>, the residual deviance value of 277 comes can be obtained as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid</span>(mod5, <span class="at">type =</span> <span class="st">'deviance'</span>) <span class="sc">%&gt;%</span> <span class="fu">raise_to_power</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 277.0468</code></pre>
</div>
</div>
<p>or as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>mod5<span class="sc">$</span>deviance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 277.0468</code></pre>
</div>
</div>
<p>This quantity has an approximate chi-squared distribution if the model is correct, which is the basis for the deviance goodness of fit test. <code>Pr(&gt;Chisq)</code> provides the p-value for this test. For <code>mod6</code>, let’s check that this is equivalent to doing this test “by hand,” using the residual deviance and residual df:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(mod6<span class="sc">$</span>deviance, <span class="at">df =</span> mod6<span class="sc">$</span>df.residual, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.940025e-08</code></pre>
</div>
</div>
<p>Each successive model shows a better fit, as evidenced by the successively larger p-values from the goodness of fit tests.</p>
</section>
<section id="drop-in-deviance-test" class="level2">
<h2 class="anchored" data-anchor-id="drop-in-deviance-test">Drop-in-deviance test</h2>
<p>Just a reminder that the drop in deviance test is different from the deviance goodness of fit test. Whereas the deviance goodness of fit test provides a comparison between a single fitted model and a saturated model, a drop in deviance test provides a way to compare two fitted models when one of those models is nested within the other one. Put another way, the drop in deviance test is a comparison between a reduced model (null hypothesis) and a full model (alternative hypothesis) – and we use it in cases where the reduced model is reduced from (or nested in) the full model.</p>
<p>Using the models we have already fit, let’s use the <code>anova()</code> function to perform a drop in deviance test comparing a reduced model (only <code>logDose</code> included) to a full model (<code>logDose</code> and <code>logDose2</code> included):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod6, mod7,<span class="at">test=</span><span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Resid. Df</th>
<th style="text-align: right;">Resid. Dev</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Deviance</th>
<th style="text-align: right;">Pr(&gt;Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: right;">68.89661</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">17</td>
<td style="text-align: right;">26.04806</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">42.84856</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The p-value of the drop in deviance test is quite small, p &lt; 0.0001. This provides convincing evidence in favor of the full model; namely, the one that includes <code>logDose</code> and <code>logDose2</code>.</p>
</section>
<section id="information-criteria-for-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="information-criteria-for-model-comparison">Information criteria for model comparison</h2>
<p>Let’s look at the <code>LRstats</code> again, this time with a focus on the first two columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(mod5, mod6,mod7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod5</td>
<td style="text-align: right;">368.4449</td>
<td style="text-align: right;">370.4364</td>
<td style="text-align: right;">277.04682</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod6</td>
<td style="text-align: right;">160.2947</td>
<td style="text-align: right;">162.2862</td>
<td style="text-align: right;">68.89661</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mod7</td>
<td style="text-align: right;">119.4461</td>
<td style="text-align: right;">122.4333</td>
<td style="text-align: right;">26.04806</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.0735894</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The AIC and BIC, as you may recall from Data Analytics I, are likelihood-based methods for comparing models. Both penalize models with more parameters, but the BIC generally applies a larger penalty (and hence promotes selection of simpler models). Models with smaller values are preferred. The AIC or BIC of a single model is not a measure of the goodness of fit for that model – the information criteria are only meaningful as comparisons between models. The information criteria can be applied to compare models which are not nested (neither model’s parameters are a strict subset of the other’s), as long as each model has a likelihood.</p>
<blockquote class="blockquote">
<p>Which of these three candidate models would we choose, based on the information criteria? Does this align with the conclusion from the drop-in-deviance test, given that mod6 is nested within mod7?</p>
</blockquote>
</section>
<section id="deviance-residuals-pearson-residuals---dispersion-parameter-estimated-from-pearson-chi-squared" class="level2">
<h2 class="anchored" data-anchor-id="deviance-residuals-pearson-residuals---dispersion-parameter-estimated-from-pearson-chi-squared">Deviance residuals, Pearson residuals - dispersion parameter estimated from Pearson – chi squared</h2>
<p>In the case of binomial logistic regression it can be helpful to look at the deviance and/or Pearson residuals to (a) evaluate the model fit and (b) check for outliers. Provided that the binomial counts are fairly large, both the deviance and Pearson residuals should look like draws from a standard Normal distribution, so too many residuals outside of the [-2,2] interval may be cause for concern. Here’ we’ll look at a few plots of both the deviance and Pearson residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>tumors<span class="sc">$</span>residuals_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod7)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>tumors<span class="sc">$</span>residuals_pearson <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod7, <span class="at">type =</span> <span class="st">"pearson"</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tumors, <span class="fu">aes</span>(logDose,residuals_deviance)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tumors, <span class="fu">aes</span>(logDose,residuals_pearson)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tumors, <span class="fu">aes</span>(residuals_deviance,residuals_pearson)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are no obvious patterns in either of the plots showing the residuals against <code>logDose</code>, and there are also no outliers. This is all good – it suggests that we’ve done a good job at modeling the log odds of tumors (although we still have to talk about the over dispersion). We created the scatterplot of the Pearson residuals versus the deviance residuals just so you could see how similar they are – for the most part, they fall along the y = x diagonal.</p>
<p>When looking at residuals, it can also be useful to plot the residuals versus the fitted values of a model. Again, we’re hoping that we <em>don’t</em> see any patterns in such a plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>tumors<span class="sc">$</span>fitted <span class="ot">=</span> <span class="fu">predict.glm</span>(mod7,<span class="at">scale=</span><span class="st">"link"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> tumors, <span class="fu">aes</span>(fitted,residuals_deviance)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are no clear patterns or problems with this plot, so again we have confirmation that we’re using a decent model at this point.</p>
</section>
</section>
<section id="dealing-with-over-dispersion" class="level1">
<h1>Dealing with over-dispersion</h1>
<p>Over dispersion can arise when there is structure in the data that is not accounted for by a model. A high degree of over dispersion may indicate that important predictors have been omitted, the functional form of the predictors is inadequate to capture relevant features of the data, observations assumed independent are not so, or large outliers are present. When there is evidence of lack of fit, we expect overdispersion.</p>
<p>From the residuals of <code>mod7</code> that we just examined (<code>mod7</code> includes <code>logDose + logDose2</code>), it doesn’t seem that there are outliers. It also seems that we’ve gotten a good functional form for the predictors (i.e., <code>logDose + logDose2</code>). Is there even evidence of lack of fit here? We looked at the deviance goodness of fit above, but let’s repeat it here just for <code>mod7</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(mod7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod7</td>
<td style="text-align: right;">119.4461</td>
<td style="text-align: right;">122.4333</td>
<td style="text-align: right;">26.04806</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.0735894</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The p-value is 0.07, which suggests that our model is a good fit, but just barely. You also saw in the narrated lectures that the estimated dispersion parameter here is 1.48 – not wildly larger than one, but larger nonetheless. Even though there may not be strong evidence for over dispersion here, it makes sense that the counts of fish with tumors are over dispersed because it’s not likely that measurements on fish from the same tank are statistically independent.</p>
<blockquote class="blockquote">
<p>When in doubt, assume that counts are over dispersed.</p>
</blockquote>
<p>You saw in the narrated lecture that the approach to use in the binomial setting when over dispersion is present is called quasi-binomial logistic regression. We’ll perform this in R, and then we’ll compare the model output from the quasi-binomial approach to the binomial approach in <code>mod7</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mod8 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, (Tumor<span class="sc">/</span>Total) <span class="sc">~</span> logDose <span class="sc">+</span> logDose2, <span class="at">weights =</span> Total, <span class="at">family =</span> <span class="st">"quasibinomial"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(mod7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = (Tumor/Total) ~ logDose + logDose2, family = "binomial", 
    data = tumors, weights = Total)
            coef.est coef.se
(Intercept)  1.03     0.49  
logDose     -1.03     0.36  
logDose2    -0.39     0.06  
---
  n = 20, k = 3
  residual deviance = 26.0, null deviance = 667.2 (difference = 641.1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(mod8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = (Tumor/Total) ~ logDose + logDose2, family = "quasibinomial", 
    data = tumors, weights = Total)
            coef.est coef.se
(Intercept)  1.03     0.60  
logDose     -1.03     0.43  
logDose2    -0.39     0.07  
---
  n = 20, k = 3
  residual deviance = 26.0, null deviance = 667.2 (difference = 641.1)
  overdispersion parameter = 1.5</code></pre>
</div>
</div>
<p>The fundamental change between <code>mod7</code> and <code>mod8</code> is that the standard errors of the regression coefficients in <code>mod8</code>, the quasi-binomial model are larger than they are in <code>mod7</code>. This illustrates the problem with ignoring a lack of statistical independence:</p>
<blockquote class="blockquote">
<p>If responses are not statistically independent, but you fit a model that assumes statistical independence, the mistake you often make is that of underestimating standard errors. This results in p-values being smaller than they should be, and confidence intervals being more narrow than they should be.</p>
</blockquote>
<p>A strong disadvantage of the quasi-likelihood (in this case quasi-binomial) approach is that since quasi-likelihoods are not real likelihoods, we cannot use likelihood-based methods of model comparison, like AIC and BIC, to choose between them, nor can we compare them with true likelihood models. Indeed, the idea of “model comparison” becomes somewhat muddled when we are talking about a collection of things that are not proper probability models to begin with.</p>
<p>You’ll learn about an alternative to the quasi-binomial model in Module 7 when we introduce mixed effects models. In that Module, we’ll refit the tumor data, including <code>TankID</code> as a random effect. You might wonder why we can’t just include <code>TankID</code> in our logistic regression model to address the over dispersion problem. Recall, however, that there are 20 tanks, so that if we use <code>TankID</code> in the model, we’ll gobble up all 20 data points before we can estimate all the “tank effects.” Look at what happens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>mod9 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> tumors, (Tumor<span class="sc">/</span>Total) <span class="sc">~</span> logDose <span class="sc">+</span> logDose2 <span class="sc">+</span> TankID, <span class="at">weights =</span> Total, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = (Tumor/Total) ~ logDose + logDose2 + TankID, family = "binomial", 
    data = tumors, weights = Total)

Coefficients: (2 not defined because of singularities)
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  0.33225    1.28208   0.259  0.79552   
logDose     -1.45660    1.00434  -1.450  0.14697   
logDose2    -0.43379    0.16314  -2.659  0.00784 **
TankID2     -0.62553    0.57989  -1.079  0.28073   
TankID3     -1.61328    0.79714  -2.024  0.04299 * 
TankID4      0.02598    0.49820   0.052  0.95842   
TankID5     -0.42670    0.39718  -1.074  0.28269   
TankID6      0.10437    0.39138   0.267  0.78973   
TankID7     -0.58424    0.40069  -1.458  0.14481   
TankID8     -0.26517    0.39306  -0.675  0.49991   
TankID9     -0.36920    0.40678  -0.908  0.36409   
TankID10    -0.32905    0.40933  -0.804  0.42147   
TankID11     0.09795    0.41529   0.236  0.81354   
TankID12    -0.29201    0.40849  -0.715  0.47471   
TankID13     0.04317    0.37730   0.114  0.90890   
TankID14     0.13158    0.38163   0.345  0.73027   
TankID15    -0.34740    0.35820  -0.970  0.33212   
TankID16          NA         NA      NA       NA   
TankID17    -0.32395    0.37597  -0.862  0.38888   
TankID18     0.85371    0.48207   1.771  0.07657 . 
TankID19     0.56157    0.44855   1.252  0.21058   
TankID20          NA         NA      NA       NA   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6.6720e+02  on 19  degrees of freedom
Residual deviance: 6.2617e-14  on  0  degrees of freedom
AIC: 127.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>This model is <em>over-saturated</em> – we’ve put too many terms in it, and not all of them can be estimated. Notice also that the degrees of freedom corresponding to the residual deviance is 0. We should not use this model for inference.</p>
</section>
<section id="a-pitfall-perfect-separation" class="level1">
<h1>A Pitfall – perfect separation</h1>
<p>In this section of the lab, we’ll discuss a pathology that can arise in logistic regression. We’ll show you what happens, and we’ll make a suggestion for dealing with the problem.</p>
<p>First, we’ll create some fake data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">10</span>,<span class="dv">11</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(y, x1, x2)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">y</th>
<th style="text-align: right;">x1</th>
<th style="text-align: right;">x2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Take a look at a plot of the data below, and it will be easy to see what the potential problem is – somewhere between 3 and 5, there’s perfect separation between the y = 0 responses and the y = 1 responses. The question is, where is “somewhere?”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Note the clean split between 0's and 1's"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="z4_learnR_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The following will not work – try inserting an “r” to make it executable.</p>
<pre><code>m1 &lt;- glm(y ~ x1 + x2, family = binomial, data = df)</code></pre>
<p>This generates an error, because <code>x1</code> predicts <em>too well</em>. There is no unique “maximum likelihood estimate” for the coefficient on <code>x1</code>, because there are too many super-excellent solutions, and the numerical algorithm behind the <code>glm()</code> function just can’t choose. This might seem like the silliest possible problem to have – that there are <em>too many</em> good solutions – but saying that doesn’t make the algorithm converge.</p>
<p>If we really believe that we can predict <code>y</code> perfectly from <code>x1</code>, we could throw out the whole model and just write down a decision rule like “predict y = 1 if x1 &gt;= 4, predict y = 0 otherwise.” Of course, we don’t know if this is a better or worse rule than, say, “predict y = 1 if x1 &gt;= 3.5, predict y = 0 otherwise” – the choice of ‘4’ as the cutpoint was arbitrary. That is, we might have the same problem that the <code>glm()</code> algorithm had – which cut-point is the best one?!</p>
<p>The real underlying issue here is that we should not believe that we’ve derived a perfect classifier (i.e., a decision rule that says when y = 1 and when y = 0) from 8 data points! In fact, in the fake data we created above, we also created a second explanatory variable, <code>x2</code>, and we never even used it.</p>
<p>An alternative approach sidesteps the problem by directly imposing our belief that a perfect classifier is too good to be true, and so it allows for estimating a coefficient on <code>x1</code>. This approach, a Bayesian generalized linear model, is well beyond the scope of this course, but you can nevertheless see it in action using the <code>bayesglm()</code> function in the <em>arm</em> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>bayes1 <span class="ot">&lt;-</span> <span class="fu">bayesglm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">family =</span> binomial, <span class="at">data =</span> df, <span class="at">prior.df =</span> <span class="dv">1</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bayes1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
bayesglm(formula = y ~ x1 + x2, family = binomial, data = df, 
    prior.df = 1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -3.6937     1.9372  -1.907   0.0566 .
x1            0.7055     0.3863   1.826   0.0678 .
x2            0.3347     0.4448   0.752   0.4518  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11.0904  on 7  degrees of freedom
Residual deviance:  2.4855  on 5  degrees of freedom
AIC: 8.4855

Number of Fisher Scoring iterations: 57</code></pre>
</div>
</div>
<p>You should still take a careful look at this model summary. In particular there were 46 iterations of the Fisher scoring algorithm – even with the prior specification about imperfect separation, the algorithm still took a while to find a solution.</p>
</section>
<section id="test-for-difference-in-proportions" class="level1">
<h1>Test for difference in proportions</h1>
<p>Another important application of logistic regression is its use in testing the difference in two proportions. We’ll return to the Berkeley Admissions data to take a look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a> (UCBA_sum <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">margin.table</span>(UCBAdmissions,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Admit
Gender   Admitted Rejected
  Male       1198     1493
  Female      557     1278</code></pre>
</div>
</div>
<p>And remember that we looked at the equivalence between <code>prop.test()</code> and <code>chisq.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(UCBA_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  UCBA_sum
X-squared = 91.61, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: two.sided
95 percent confidence interval:
 0.1129887 0.1703022
sample estimates:
   prop 1    prop 2 
0.4451877 0.3035422 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(UCBA_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  UCBA_sum
X-squared = 91.61, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Now let’s perform the same test, using logistic regression. # Check code: gender should be factor and admit is factor with 0 levels</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>UCBA_case <span class="ot">&lt;-</span> <span class="fu">expand.dft</span>(UCBA_sum)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>UCBA_case <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(<span class="at">Gender=</span><span class="fu">factor</span>(Gender), <span class="at">Admit =</span> <span class="fu">relevel</span>(<span class="fu">factor</span>(Admit),<span class="st">"Rejected"</span>))</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#mutate(Admit = factor(Admit,levels(Admit)[2:1]))</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make sure that "Rejected" is the failure level in glm</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(UCBA_case)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: left;">Admit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Admitted</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Admitted</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Admitted</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Admitted</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Admitted</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Admitted</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>test1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> UCBA_case, Admit <span class="sc">~</span> Gender, <span class="at">family =</span> binomial)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Admit ~ Gender, family = binomial, data = UCBA_case)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.83049    0.05077 -16.357   &lt;2e-16 ***
GenderMale   0.61035    0.06389   9.553   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6044.3  on 4525  degrees of freedom
Residual deviance: 5950.9  on 4524  degrees of freedom
AIC: 5954.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The relationship to <code>prop.test()</code> may not be immediately clear, and this is partly because the logistic regression output is on then model scale – in this case the log odds. Take a look at the <code>z value</code> corresponding to the <code>GenderMale</code> variable. If you take the square of this value, you get 91.26, which is quite similar to the <code>X squared</code> value you get from <code>prop.test()</code> and from <code>Chisq.test</code>. Recall that the square of a standard Normal random variable is a Chi-square random variable, and this helps to explain the similarity.</p>
<p>If we perform the appropriate back-transformations from the logistic regression output, we’ll see the correspondence to the test for a difference in proportions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">0.83049</span>) <span class="co">#Pr(Admit|Female)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3035415</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">0.83049+0.61035</span>) <span class="co"># Pr(Admit|Male)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4451862</code></pre>
</div>
</div>
</section>
<section id="lab-4-assignment" class="level1">
<h1>Lab 4 Assignment</h1>
<section id="question" class="level2">
<h2 class="anchored" data-anchor-id="question">Question</h2>
<p>Here we will return to the UCBAdmissions dataset and fit a logistic regression model for the count of students admitted (out of the total applicants) for each combination of the factors gender and department. The usual drill applies – submit your answers as an RMarkdown document, following the instructions given in the previous labs.</p>
<ol type="a">
<li>Construct an informative ggplot() of the empirical logits of admission proportion vs gender and department. It’s up to you what aesthetics to map to which variables – there is more than one right answer here.</li>
</ol>
<p>Some tips for part (a):</p>
<ul>
<li><p>You can use the <code>group</code> argument to geom_line() to connect points within a group – for instance, given a plot with Gender on the x axis and a variable called <code>eLogits</code> on the y, you could add <code>geom_line(aes(group = Dept, x = Gender, y = eLogits))</code>, where the slope of the connecting lines would correspond to the sign and magnitude of the difference in empirical logits (log of observed odds ratio) between genders within each department.</p></li>
<li><p>You can also incorporate information about the total number of applicants to each department into your plot. For instance, supposing you had a data frame with separate columns containing counts of “Admitted” and “Rejected” by sex and department, you could map the number of applicants to the size of the plot points using <code>geom_point(size = Admitted + Rejected)</code>.</p></li>
</ul>
<ol start="2" type="a">
<li><p>Based on your plot from (a), which variable (gender or department) appears to account for more of the variability in admissions? Explain.</p></li>
<li><p>Fit an appropriate (binomial) logistic regression model for admissions. What is the estimated dispersion parameter? Is there evidence of lack of fit?</p></li>
<li><p>Construct a plot of residuals vs fitted values (try just <code>plot</code>-ing your fitted model object). From this plot, can you identify a source for any fit problems encountered in part (c)?</p></li>
<li><p>Refit the binomial model above, but excluding the data from department A. Now what is the estimated dispersion parameter? Based on the p-value, what would you conclude about the effect of Gender on admissions (to departments other than A) using this model?</p></li>
<li><p>The approach in part (d) allowed us to keep the binomial likelihood model, but only by performing an unprincipled exclusion of some apparently-legitimate data that happened to be “outlying”.</p></li>
</ol>
<p>To avoid this, we’ll refit the model for all departments with the quasibinomial family.</p>
<p>Using the quasibinomial model for all departments, what do you conclude about the effect of Gender on admissions? Support your conclusion by constructing and interpreting a 95% confidence interval for</p>
<p><span class="math inline">\(P_{diff} = [P(Admit | (Department, Male)) - P(Admit | (Department, Female))]\)</span></p>
<p>That is, construct an interval on the model scale, then backtransform to the data scale. Be careful with the direction (male higher or female higher) of the observed difference in conditional probability of admission.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>