<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data_Analysis_II_Notes - 5 Log Lin Reg</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data_Analysis_II_Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notes" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notes">    
        <li>
    <a class="dropdown-item" href="./1_Types_of_Categoricals.html">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_Props_Risks_Odds.html">
 <span class="dropdown-text">2 Props, Risk &amp; Odds</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./3_Logistic_Regression_I.html">
 <span class="dropdown-text">3 Log Reg I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./4_Logistic_Regression_II.html">
 <span class="dropdown-text">4 Log-Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./5_Log_linear_Regression.html">
 <span class="dropdown-text">5 Log-lin-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./6_Dispersion_Zero_Inflation.html">
 <span class="dropdown-text">6 Disp &amp; 0 Inflation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./7_Random_Effects.html">
 <span class="dropdown-text">7 Random_Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./8_Evaluating_Models.html">
 <span class="dropdown-text">8 Model Eval</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./9_Imp_Pred_Validate.html">
 <span class="dropdown-text">9 Imp, Pred, Validate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_Final_Project.html">
 <span class="dropdown-text">10 Final Project</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./z0_learnR.html">
 <span class="dropdown-text">LearnR 0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z1_learnR.html">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z2_learnR.html">
 <span class="dropdown-text">2 Odds and risks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z3_learnR.html">
 <span class="dropdown-text">3 Log-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z4_learnR.html">
 <span class="dropdown-text">4 Log Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z5_learnR.html">
 <span class="dropdown-text">5 Log Lin Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z6_learnR.html">
 <span class="dropdown-text">6 Zero Inflation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z7_learnR.html">
 <span class="dropdown-text">7 Mixed Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z8_learnR.html">
 <span class="dropdown-text">LearnR 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hw" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">HW</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hw">    
        <li>
    <a class="dropdown-item" href="./aHW_1.html">
 <span class="dropdown-text">ST-518 HW 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_2.html">
 <span class="dropdown-text">ST-518 HW 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_3.html">
 <span class="dropdown-text">ST-518 HW 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_4.html">
 <span class="dropdown-text">ST-518 HW 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_5.html">
 <span class="dropdown-text">ST-518 HW 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_6.html">
 <span class="dropdown-text">ST-518 HW 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_7.html">
 <span class="dropdown-text">ST-518 HW 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_8.html">
 <span class="dropdown-text">ST-518 HW 8</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#log-lin-reg" id="toc-log-lin-reg" class="nav-link active" data-scroll-target="#log-lin-reg">5 Log lin reg</a></li>
  <li><a href="#count-responses" id="toc-count-responses" class="nav-link" data-scroll-target="#count-responses">Count responses</a></li>
  <li><a href="#salamander-data" id="toc-salamander-data" class="nav-link" data-scroll-target="#salamander-data">Salamander Data</a>
  <ul class="collapse">
  <li><a href="#some-data-exploration" id="toc-some-data-exploration" class="nav-link" data-scroll-target="#some-data-exploration">Some data exploration</a></li>
  </ul></li>
  <li><a href="#the-log-linear-model" id="toc-the-log-linear-model" class="nav-link" data-scroll-target="#the-log-linear-model">The Log Linear Model</a>
  <ul class="collapse">
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting">Model Fitting</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model Evaluation</a></li>
  <li><a href="#drop-in-deviance-test" id="toc-drop-in-deviance-test" class="nav-link" data-scroll-target="#drop-in-deviance-test">Drop-in-deviance test</a></li>
  <li><a href="#looking-at-residuals" id="toc-looking-at-residuals" class="nav-link" data-scroll-target="#looking-at-residuals">Looking at Residuals</a></li>
  </ul></li>
  <li><a href="#log-linear-models-for-general-contingency-tables" id="toc-log-linear-models-for-general-contingency-tables" class="nav-link" data-scroll-target="#log-linear-models-for-general-contingency-tables">Log Linear Models for General Contingency Tables</a></li>
  <li><a href="#lab-5-assignment" id="toc-lab-5-assignment" class="nav-link" data-scroll-target="#lab-5-assignment">Lab 5 Assignment</a>
  <ul class="collapse">
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a>
  <ul class="collapse">
  <li><a href="#exploration" id="toc-exploration" class="nav-link" data-scroll-target="#exploration">exploration</a></li>
  </ul></li>
  <li><a href="#fit-two-way-interctions." id="toc-fit-two-way-interctions." class="nav-link" data-scroll-target="#fit-two-way-interctions.">1 fit two way interctions.</a>
  <ul class="collapse">
  <li><a href="#fit-saturated" id="toc-fit-saturated" class="nav-link" data-scroll-target="#fit-saturated">fit saturated</a></li>
  </ul></li>
  <li><a href="#fit-three-way-interactions." id="toc-fit-three-way-interactions." class="nav-link" data-scroll-target="#fit-three-way-interactions.">2 fit three way interactions.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">5 Log Lin Reg</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="log-lin-reg" class="level1">
<h1>5 Log lin reg</h1>
</section>
<section id="count-responses" class="level1">
<h1>Count responses</h1>
<p>Please load these libraries that you’ll need for this lab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arm)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Sleuth3)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this lab, we’ll go over log linear regression in the case of count data in a little more detail than you saw in the narrated lectures. We’ll cover the deviance goodness of fit test (which, remember, is an informal test here) and the drop in deviance test in R; and we’ll discuss residuals and model evaluation. You’ll see more about over dispersion in the case of Poisson counts, and we’ll cover the negative binomial model for over dispersion. We’ll conclude with another example of log linear regression for general contingency tables.</p>
</section>
<section id="salamander-data" class="level1">
<h1>Salamander Data</h1>
<p>The data that we’ll use for this lab concern salamander habitat:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ?case2202</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>salamanders <span class="ot">&lt;-</span> case2202</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salamanders)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Site</th>
<th style="text-align: right;">Salamanders</th>
<th style="text-align: right;">PctCover</th>
<th style="text-align: right;">ForestAge</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">316</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">548</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">64</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">43</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">368</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>As you can see (and read about in the help file) the <code>salamanders</code> data contain counts of salamanders at 47 sites in national forest and parkland; the available explanatory information is <code>PctCover</code>, a percentage of canopy cover at the site and <code>ForestAge</code>, the age of the forest at the site.</p>
<section id="some-data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="some-data-exploration">Some data exploration</h2>
<p>We’ll start with some exploration of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(<span class="at">x =</span> PctCover, <span class="at">y =</span> Salamanders)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Salamanders vs Percent Cover"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This first figure seems to indicate that there are two distinct types of sites those with <code>PctCover</code> below about 53% and those with <code>PctCover</code> greater than 75%. It also seems clear that only sites with <code>PctCover</code> greater than 75% have <code>Salamander</code> counts higher than 2.</p>
<p>Here’s another plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(<span class="at">x =</span> ForestAge, <span class="at">y =</span> Salamanders)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Salamanders vs Forest Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There doesn’t appear to be anything remarkable about this plot, though it’s important to notice the range of the x-axis scale – it’s fairly large. This suggests that we might observe something more informative if we look at <code>ForestAge</code> on the log scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>), <span class="at">y =</span> Salamanders)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Salamanders vs log(Forest Age)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice that we used <code>x = log(ForestAge + 1/2)</code> in the <code>ggplot()</code> function call because some of the <code>ForestAge</code> values are zero, and <code>log(0)</code> is undefined.</p>
<p>This plot seems to indicate a clearer relationship between <code>ForestAge</code> and <code>Salamanders</code> as <code>ForestAge</code> increases on the log scale, the salamander counts tend to increase and they get more variable. Let’s also look at the relationship between the two explanatory variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>), <span class="at">y =</span> PctCover)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Percent Cover vs log(Forest Age"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot tells and interesting story almost all of the older sites are those with <code>PctCover</code> greater than 75%. For the younger sites, there is a increasing (perhaps curvilinear) relationship with <code>PctCover</code>.</p>
<p>Remember that multicollinearity is a problem when two or more explanatory variables are highly correlated. Let’s check the correlation between log-transformed <code>PctCover</code> and the <code>ForestAge</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>salamanders <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(<span class="at">Site =</span> Site, <span class="at">Salamanders =</span> Salamanders, <span class="at">ForestAge =</span> ForestAge, <span class="at">logPctCover =</span> <span class="fu">log</span>(PctCover <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(salamanders<span class="sc">$</span>ForestAge,salamanders<span class="sc">$</span>logPctCover)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5352604</code></pre>
</div>
</div>
<p>The correlation is not actually so high that we should be concerned about it. Remember, too, that correlation tells us about the <em>linear</em> association between two variables. In terms of a linear association, these two variables are moderately correlated – even though from our last plot we see that there is a strong relationship between them.</p>
<p>Because of the distinctive cut-point in the <code>PctForest</code> variable, we’ll create a new variable, called <code>CovGroup</code>, that just takes the value 0 if <code>PctCover &lt; 75)</code> and 1 otherwise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>CovGroup <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salamanders<span class="sc">$</span>PctCover <span class="sc">&lt;</span> <span class="dv">75</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, as a last bit of exploration, let’s just take a look at the histogram of <code>Salamander</code> counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(salamanders,<span class="fu">aes</span>(Salamanders)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can see that there are a lot of zeroes in among the <code>Salamander</code> counts. One method for analyzing Poisson count data is to take the log of the counts, and then perform a multiple linear regression. We don’t recommend that here, since there are so many zeroes – you’d have to first add a small amount to the zero counts, then take logs, and that means that interpretations will be difficult.</p>
<p>Instead, we’ll turn to fitting the log linear model (another special case of a generalized linear model).</p>
</section>
</section>
<section id="the-log-linear-model" class="level1">
<h1>The Log Linear Model</h1>
<p>Remember that for independent Poisson counts, <span class="math inline">\(Y_1,\ldots,Y_n\)</span>, each with rate parameter <span class="math inline">\(\lambda_i\)</span> for <span class="math inline">\(i = 1,\ldots,n\)</span>, we have</p>
<blockquote class="blockquote">
<p><span class="math inline">\(log(\lambda_i) = \beta_0 + \beta_1X_{1i} + \cdots + \beta_kX_{ki}\)</span></p>
</blockquote>
<p>for explanatory variables, <span class="math inline">\(X_1,\ldots,X_k\)</span>. Let’s go ahead and fit some models to the <code>salamander</code> data.</p>
<section id="model-fitting" class="level2">
<h2 class="anchored" data-anchor-id="model-fitting">Model Fitting</h2>
<p>In this part of the lab, we’ll fit several different models, and make some comparisons among them. This is a little bit of data snooping, and we will likely end up with biased estimates in the model we do select (recall the simulation you saw back in Data Analytics I). So, please, consider this to be the academic exercise it’s intended to be!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model with PctCover only</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>pois_mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> PctCover, <span class="at">family =</span> poisson)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># model the log(Forest Age + 1/2) only</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>pois_mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>), <span class="at">family =</span> poisson)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># model with both explanatory variables</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>pois_mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> PctCover <span class="sc">+</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>), <span class="at">family =</span> poisson)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># model with both explanatory variables, plus their interaction</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>pois_mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> PctCover <span class="sc">*</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>), <span class="at">family =</span> poisson)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># comparison of the models</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(pois_mod1, pois_mod2, pois_mod3, pois_mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pois_mod1</td>
<td style="text-align: right;">210.3639</td>
<td style="text-align: right;">214.0642</td>
<td style="text-align: right;">121.3050</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">pois_mod2</td>
<td style="text-align: right;">243.1239</td>
<td style="text-align: right;">246.8242</td>
<td style="text-align: right;">154.0650</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pois_mod3</td>
<td style="text-align: right;">212.0690</td>
<td style="text-align: right;">217.6195</td>
<td style="text-align: right;">121.0101</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">pois_mod4</td>
<td style="text-align: right;">213.7578</td>
<td style="text-align: right;">221.1584</td>
<td style="text-align: right;">120.6989</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In terms of the AIC comparisons, there’s not much difference between models 1, 2 and 4; and the same is true if we use the BIC comparisons. This is somewhat surprising – from the exploratory plots above, you might have suspected that both <code>PctCover</code> and <code>ForestAge</code>, and maybe even their interaction might be important. Let’s take a look at the summary information for <code>pois_mod4</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pois_mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Salamanders ~ PctCover * log(ForestAge + 1/2), 
    family = poisson, data = salamanders)

Coefficients:
                               Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)                   -0.969454   0.820929  -1.181  0.23763   
PctCover                       0.029067   0.011184   2.599  0.00935 **
log(ForestAge + 1/2)          -0.213107   0.293009  -0.727  0.46704   
PctCover:log(ForestAge + 1/2)  0.001957   0.003423   0.572  0.56741   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 190.22  on 46  degrees of freedom
Residual deviance: 120.70  on 43  degrees of freedom
AIC: 213.76

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>It looks like there pretty clear evidence of over dispersion, the residual deviance divided by the residual degrees of freedom is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fl">120.7</span><span class="sc">/</span><span class="dv">43</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.806977</code></pre>
</div>
</div>
<p>That’s pretty big. Before we talk a lot more about model fitting and model comparison in terms of what explanatory information to include, we should address the over dispersion. Remember that we can do this using the <code>family = quasipoisson</code> argument to the <code>glm()</code> function, or we can do this using the <code>glm.nb</code> function. We’ll leave it to you to try the quasi-poisson approach, and we’ll go over the negative binomial approach here. We’ll simply fit the same four models as above, but using the negative binomial likelihood rather than the Poisson likelihood.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model with PctCover only</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>nb_mod1 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> PctCover)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># model the log(Forest Age + 1/2) only</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>nb_mod2 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># model with both explanatory variables</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>nb_mod3 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> PctCover <span class="sc">+</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># model with both explanatory variables, plus their interaction</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>nb_mod4 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> PctCover <span class="sc">*</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>))</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># comparison of the models</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(nb_mod1, nb_mod2, nb_mod3, nb_mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">nb_mod1</td>
<td style="text-align: right;">176.9625</td>
<td style="text-align: right;">182.5130</td>
<td style="text-align: right;">47.60608</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.3670830</td>
</tr>
<tr class="even">
<td style="text-align: left;">nb_mod2</td>
<td style="text-align: right;">188.2859</td>
<td style="text-align: right;">193.8363</td>
<td style="text-align: right;">47.99615</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.3523296</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nb_mod3</td>
<td style="text-align: right;">178.8296</td>
<td style="text-align: right;">186.2302</td>
<td style="text-align: right;">47.56748</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.3295507</td>
</tr>
<tr class="even">
<td style="text-align: left;">nb_mod4</td>
<td style="text-align: right;">180.5434</td>
<td style="text-align: right;">189.7941</td>
<td style="text-align: right;">47.48537</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.2948841</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Again, there’s no clear winner here in terms of either AIC or BIC, so we’ll go with Occam’s Razor and look at results for the simplest model, <code>nb_mod1</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Salamanders ~ PctCover, data = salamanders, 
    init.theta = 1.26199236, link = log)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.416365   0.527696  -2.684  0.00727 ** 
PctCover     0.031513   0.006655   4.735 2.19e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.262) family taken to be 1)

    Null deviance: 75.691  on 46  degrees of freedom
Residual deviance: 47.606  on 45  degrees of freedom
AIC: 176.96

Number of Fisher Scoring iterations: 1

              Theta:  1.262 
          Std. Err.:  0.478 

 2 x log-likelihood:  -170.963 </code></pre>
</div>
</div>
<p>Remember that we still didn’t use the <code>CovGroup</code> indicator variable that we created above. Let’s fit a couple more models using that variable, and see where we are.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model with CovGroup only </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>nb_mod5 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> CovGroup)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># model with CovGroup*log(ForestAge + 1/2)</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>nb_mod6 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(<span class="at">data =</span> salamanders, Salamanders <span class="sc">~</span> CovGroup <span class="sc">*</span> <span class="fu">log</span>(ForestAge <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># compare with the other models</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(nb_mod1,nb_mod2,nb_mod3,nb_mod4,nb_mod5,nb_mod6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">nb_mod1</td>
<td style="text-align: right;">176.9625</td>
<td style="text-align: right;">182.5130</td>
<td style="text-align: right;">47.60608</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.3670830</td>
</tr>
<tr class="even">
<td style="text-align: left;">nb_mod2</td>
<td style="text-align: right;">188.2859</td>
<td style="text-align: right;">193.8363</td>
<td style="text-align: right;">47.99615</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.3523296</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nb_mod3</td>
<td style="text-align: right;">178.8296</td>
<td style="text-align: right;">186.2302</td>
<td style="text-align: right;">47.56748</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.3295507</td>
</tr>
<tr class="even">
<td style="text-align: left;">nb_mod4</td>
<td style="text-align: right;">180.5434</td>
<td style="text-align: right;">189.7941</td>
<td style="text-align: right;">47.48537</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.2948841</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nb_mod5</td>
<td style="text-align: right;">176.7513</td>
<td style="text-align: right;">182.3018</td>
<td style="text-align: right;">47.17214</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.3838253</td>
</tr>
<tr class="even">
<td style="text-align: left;">nb_mod6</td>
<td style="text-align: right;">180.7331</td>
<td style="text-align: right;">189.9838</td>
<td style="text-align: right;">47.16892</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.3060094</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now it seems like there’s really not much difference among any of these models (except that many <code>nb_mod2</code> is a clear-ish loser) in terms of AIC or BIC. We’ll continue with <code>nb_mod1</code> at this point. Let’s take a look at the model and it’s fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nb_mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Salamanders ~ PctCover, data = salamanders, 
    init.theta = 1.26199236, link = log)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.416365   0.527696  -2.684  0.00727 ** 
PctCover     0.031513   0.006655   4.735 2.19e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.262) family taken to be 1)

    Null deviance: 75.691  on 46  degrees of freedom
Residual deviance: 47.606  on 45  degrees of freedom
AIC: 176.96

Number of Fisher Scoring iterations: 1

              Theta:  1.262 
          Std. Err.:  0.478 

 2 x log-likelihood:  -170.963 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>resid <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nb_mod1)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>fits <span class="ot">&lt;-</span> <span class="fu">predict.glm</span>(nb_mod1,<span class="at">scale=</span><span class="st">"data"</span>,<span class="at">se.fit=</span><span class="cn">TRUE</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>fits <span class="ot">&lt;-</span> <span class="fu">exp</span>(fits<span class="sc">$</span>fit)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>low <span class="ot">&lt;-</span> <span class="fu">exp</span>(fits<span class="sc">$</span>fit<span class="fl">-1.96</span><span class="sc">*</span>fits<span class="sc">$</span>se.fit)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>upp <span class="ot">&lt;-</span> <span class="fu">exp</span>(fits<span class="sc">$</span>fit<span class="fl">+1.96</span><span class="sc">*</span>fits<span class="sc">$</span>se.fit)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(salamanders,<span class="fu">aes</span>(PctCover,Salamanders)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span>      </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> PctCover, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> fits)) <span class="sc">+</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> PctCover, </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymin =</span> low, </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> upp),</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alpha =</span> <span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The model fit is not bad – remember that the solid line in the figure above is the model estimate of the Poisson rate parameter at each value of <code>PctCover</code>, and the shaded bands are 95% pointwise confidence intervals. The model output gives strong evidence of a positive association between <code>PctCover</code> and the number of salamanders at a site.</p>
<p>Notice also that the residual deviance divided by its degrees of freedom for <code>nb_mod1</code> is very close to 1. The negative binomial model also gives an estimate of the “Theta” parameter. In the negative binomial model, if the expected count is <span class="math inline">\(E(Y)\)</span>, the variance of the count is <span class="math inline">\(Var(Y) = E(Y) + [E(Y)^2]/\theta\)</span>.</p>
<p>Since the negative binomial model uses the log-link as does the Poisson model, the interpretation of the coefficient on <code>PctCover</code> is the same as in the Poisson model – an increase of 1% in forest cover is associated with an <span class="math inline">\(exp(0.0315) = 1.03\)</span>-fold increase in the expected number of salamanders. In other words, a 1% increase in forest cover is associated with a 3% increase in expected number of salamanders at a site.</p>
</section>
<section id="model-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="model-evaluation">Model Evaluation</h2>
<p>Recall that the deviance goodness of fit test compares a fitted model to a saturated model, or one in which there are as many parameters as there are data points. In these goodness of fit comparisons, the null hypothesis corresponds to the fitted model (which is a reduced model relative to the saturated model), and the alternative hypothesis corresponds to the saturated model. In the case of Poisson counts, the goodness of fit should only be used as a guideline, not as a firm decision making tool.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">LRstats</span>(nb_mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR Chisq</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">nb_mod1</td>
<td style="text-align: right;">176.9625</td>
<td style="text-align: right;">182.513</td>
<td style="text-align: right;">47.60608</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.367083</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>This large p-value may be an indication of an adequate model, but there are many small counts in the <code>salamanders</code> data, so we should not rely heavily on this result.</p>
</section>
<section id="drop-in-deviance-test" class="level2">
<h2 class="anchored" data-anchor-id="drop-in-deviance-test">Drop-in-deviance test</h2>
<p>Just a reminder that the drop in deviance test is different from the deviance goodness of fit test. Whereas the deviance goodness of fit test provides a comparison between a single fitted model and a saturated model, a drop in deviance test provides a way to compare two fitted models when one of those models is nested within the other one. Put another way, the drop in deviance test is a comparison between a reduced model (null hypothesis) and a full model (alternative hypothesis) – and we use it in cases where the reduced model is reduced from (or nested in) the full model.</p>
<p>Using the models we have already fit, let’s use the <code>anova()</code> function to perform a drop in deviance test comparing the model that only contains <code>PctCover</code> to the one that contains <code>PctCover</code>, <code>ForestAge</code> and their interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(nb_mod1,nb_mod4,<span class="at">test=</span><span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 32%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">theta</th>
<th style="text-align: right;">Resid. df</th>
<th style="text-align: right;">2 x log-lik.</th>
<th style="text-align: left;">Test</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">LR stat.</th>
<th style="text-align: right;">Pr(Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PctCover</td>
<td style="text-align: right;">1.261992</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">-170.9625</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PctCover * log(ForestAge + 1/2)</td>
<td style="text-align: right;">1.279151</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">-170.5434</td>
<td style="text-align: left;">1 vs 2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.419181</td>
<td style="text-align: right;">0.8109163</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The p-value of the drop in deviance test is rather large, giving us strong evidence that the simpler model is sufficient in this case, as compared to the more complicated model.</p>
</section>
<section id="looking-at-residuals" class="level2">
<h2 class="anchored" data-anchor-id="looking-at-residuals">Looking at Residuals</h2>
<p>As in the case of binomial logistic regression, it can be helpful to look at the deviance and/or Pearson residuals from our negative binomial (or Poisson) regression mode to (a) evaluate the model fit and (b) check for outliers. Provided that the counts are fairly large, both the deviance and Pearson residuals should look like draws from a standard Normal distribution, so too many residuals outside of the [-2,2] interval may be cause for concern. Here, we’ll look at plots of both the deviance and Pearson residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>residuals_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nb_mod1)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>salamanders<span class="sc">$</span>residuals_pearson <span class="ot">&lt;-</span> <span class="fu">residuals</span>(nb_mod1, <span class="at">type =</span> <span class="st">"pearson"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(PctCover,residuals_deviance)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(PctCover,residuals_pearson)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> salamanders, <span class="fu">aes</span>(residuals_deviance,residuals_pearson)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-19-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>First, you should notice that there are some distinctive patterns in both the deviance and Pearson residual plots. These kinds of patterns are quite common when we are dealing with count data, and they are result of the discreteness of those counts. In these residual plots, we are more concerned with detecting potential outliers, and there do not appear to be any here.</p>
<p>Next, the plot of the two types of residuals against each other shows the strong relationship between them – in this case it’s not a linear relationship as it was in the case of binomial logistic regression – but it’s a strong relationship nonetheless.</p>
</section>
</section>
<section id="log-linear-models-for-general-contingency-tables" class="level1">
<h1>Log Linear Models for General Contingency Tables</h1>
<p>We’ll now turn to an example of using a log linear model for data in general contingency tables. The following table relates education level, religious views, and approval of homosexual marriage for 133 Americans age 18-25 (see example 8.4.2 in Agresti (2013)). In this table “agree” indicates that the respondent agrees that homosexual marriage should be allowed in the US.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>marriage <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">opinion =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Agree"</span>, <span class="st">"Neutral"</span>, <span class="st">"Disagree"</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Agree"</span>, <span class="st">"Neutral"</span>, <span class="st">"Disagree"</span>)),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">relig =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Fundamentalist"</span>, <span class="st">"Moderate"</span>, <span class="st">"Liberal"</span>), <span class="fu">c</span>(<span class="st">"Liberal"</span>, <span class="st">"Moderate"</span>, <span class="st">"Fundamentalist"</span>)),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">educ =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"High school or less"</span>, <span class="st">"At least some college"</span>), <span class="fu">c</span>(<span class="st">"High school or less"</span>, <span class="st">"At least some college"</span>))) </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>marriage<span class="sc">$</span>Freq <span class="ot">&lt;-</span> <span class="fu">c</span>(  <span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">10</span>,<span class="dv">8</span>,<span class="dv">3</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">11</span>,<span class="dv">21</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">22</span>,<span class="dv">4</span>,<span class="dv">1</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>marriage_tab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> marriage, Freq <span class="sc">~</span> educ <span class="sc">+</span> relig <span class="sc">+</span> opinion)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ftable</span>(marriage_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     opinion Agree Neutral Disagree
educ                  relig                                        
High school or less   Liberal                   11       5        6
                      Moderate                   8       3        9
                      Fundamentalist             6       2       10
At least some college Liberal                   22       4        1
                      Moderate                  21       3        5
                      Fundamentalist             4       2       11</code></pre>
</div>
</div>
<p>If we just think about questions regarding whether and how these three variables are related, we can fit a log linear model, with the count frequencies as the responses, and the levels of three factors as explanatory information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod_relig <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> marriage_tab, Freq <span class="sc">~</span> relig <span class="sc">+</span> educ <span class="sc">+</span> opinion, <span class="at">family =</span> poisson)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_relig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Freq ~ relig + educ + opinion, family = poisson, 
    data = marriage_tab)

Coefficients:
                            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                2.482e+00  1.895e-01  13.095  &lt; 2e-16 ***
religModerate             -5.009e-15  2.020e-01   0.000   1.0000    
religFundamentalist       -3.365e-01  2.213e-01  -1.520   0.1284    
educAt least some college  1.961e-01  1.743e-01   1.125   0.2604    
opinionNeutral            -1.332e+00  2.579e-01  -5.165  2.4e-07 ***
opinionDisagree           -5.390e-01  1.942e-01  -2.776   0.0055 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 72.362  on 17  degrees of freedom
Residual deviance: 34.930  on 12  degrees of freedom
AIC: 111.43

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The results of this model seem to indicate that the only factor that is associated with variation in the table frequencies is the opinion regarding gay marriage. What about the association questions?</p>
</section>
<section id="lab-5-assignment" class="level1">
<h1>Lab 5 Assignment</h1>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<section id="exploration" class="level3">
<h3 class="anchored" data-anchor-id="exploration">exploration</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>marriage_tab <span class="sc">|&gt;</span> <span class="fu">ftable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     opinion Agree Neutral Disagree
educ                  relig                                        
High school or less   Liberal                   11       5        6
                      Moderate                   8       3        9
                      Fundamentalist             6       2       10
At least some college Liberal                   22       4        1
                      Moderate                  21       3        5
                      Fundamentalist             4       2       11</code></pre>
</div>
</div>
<p>I am assuming the log relationship due to this being the lab for that scenario.</p>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>marriage <span class="sc">|&gt;</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> <span class="fu">log</span>(Freq), <span class="at">color =</span> opinion, <span class="at">shape =</span> relig) <span class="sc">+</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">angle =</span> <span class="dv">90</span>)) </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>marriage <span class="sc">|&gt;</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> relig, <span class="at">y =</span> <span class="fu">log</span>(Freq), <span class="at">color =</span> opinion) <span class="sc">+</span> </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>educ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Some college is more spread out than high school, opinions cluster more. There is a single count of Liberal, college, disagree that is a potential outlier. In both sets, disagreement increases as liberal goes to fundamentalist and vice versa, agreement goes down.<br>
Neutrality decreases as liberal goes to fundamentalist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>marriage <span class="sc">|&gt;</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> <span class="fu">log</span>(Freq), <span class="at">color =</span> opinion) <span class="sc">+</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>relig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For college vs religion, among liberals agreement goes up with education, neutrality slightly down. For moderates, it’s the same, but more folks disagree and neutrality might go a little up. For fundamentalists, agreement goes down and disagree up. That is different. Neutrality is roughly the same.</p>
</section>
</section>
<section id="fit-two-way-interctions." class="level2">
<h2 class="anchored" data-anchor-id="fit-two-way-interctions.">1 fit two way interctions.</h2>
<ol type="1">
<li>Fit a model to the gay marriage data that includes all two-way interactions. What do you conclude from this model? Be specific and try to address questions having to do with the association among the three variables.</li>
</ol>
<section id="fit-saturated" class="level3">
<h3 class="anchored" data-anchor-id="fit-saturated">fit saturated</h3>
<p>Looking at table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>marriage_tab <span class="sc">|&gt;</span> <span class="fu">ftable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     opinion Agree Neutral Disagree
educ                  relig                                        
High school or less   Liberal                   11       5        6
                      Moderate                   8       3        9
                      Fundamentalist             6       2       10
At least some college Liberal                   22       4        1
                      Moderate                  21       3        5
                      Fundamentalist             4       2       11</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> marriage_tab, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> poisson, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>          Freq<span class="sc">~</span>relig<span class="sc">*</span>opinion <span class="sc">+</span> relig<span class="sc">*</span>educ <span class="sc">+</span> opinion<span class="sc">*</span>educ)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(m2)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>s2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Freq ~ relig * opinion + relig * educ + opinion * 
    educ, family = poisson, data = marriage_tab)

Coefficients:
                                              Estimate Std. Error z value
(Intercept)                                     2.5263     0.2649   9.535
religModerate                                  -0.3176     0.3779  -0.840
religFundamentalist                            -1.3054     0.4838  -2.699
opinionNeutral                                 -0.9123     0.4562  -2.000
opinionDisagree                                -1.0287     0.4607  -2.233
educAt least some college                       0.4938     0.3216   1.535
religModerate:opinionNeutral                   -0.2255     0.5911  -0.381
religFundamentalist:opinionNeutral              0.4139     0.7069   0.585
religModerate:opinionDisagree                   0.8969     0.5412   1.657
religFundamentalist:opinionDisagree             2.3377     0.5825   4.013
religModerate:educAt least some college         0.2881     0.4250   0.678
religFundamentalist:educAt least some college   0.1739     0.4957   0.351
opinionNeutral:educAt least some college       -0.7272     0.5241  -1.388
opinionDisagree:educAt least some college      -1.0634     0.4359  -2.440
                                              Pr(&gt;|z|)    
(Intercept)                                    &lt; 2e-16 ***
religModerate                                  0.40067    
religFundamentalist                            0.00697 ** 
opinionNeutral                                 0.04554 *  
opinionDisagree                                0.02556 *  
educAt least some college                      0.12467    
religModerate:opinionNeutral                   0.70287    
religFundamentalist:opinionNeutral             0.55823    
religModerate:opinionDisagree                  0.09750 .  
religFundamentalist:opinionDisagree              6e-05 ***
religModerate:educAt least some college        0.49791    
religFundamentalist:educAt least some college  0.72573    
opinionNeutral:educAt least some college       0.16527    
opinionDisagree:educAt least some college      0.01469 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 72.3623  on 17  degrees of freedom
Residual deviance:  6.5821  on  4  degrees of freedom
AIC: 99.078

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>It appears that fundamentalists and opinions about gay marriage are main effects that are associated with variation in the table. Those with at least some college who disagree with gay marriage and Fundamentalists who disagree also appear to account for some variation. Also moderates who disagree could also account for some variation.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                   2.5 %      97.5 %
(Intercept)                                    1.9652588  3.00852096
religModerate                                 -1.0740121  0.41947706
religFundamentalist                           -2.3106386 -0.39824367
opinionNeutral                                -1.8640548 -0.05379958
opinionDisagree                               -2.0031444 -0.17037201
educAt least some college                     -0.1285080  1.14077865
religModerate:opinionNeutral                  -1.4293902  0.92350177
religFundamentalist:opinionNeutral            -1.0566124  1.77303287
religModerate:opinionDisagree                 -0.1375381  2.00722939
religFundamentalist:opinionDisagree            1.2442200  3.54536159
religModerate:educAt least some college       -0.5423790  1.13070428
religFundamentalist:educAt least some college -0.7922154  1.16236149
opinionNeutral:educAt least some college      -1.7733304  0.30270736
opinionDisagree:educAt least some college     -1.9388926 -0.22115922</code></pre>
</div>
</div>
<p>The 95% confidence intervals for the coefficients of the interaction terms that include zero are:</p>
<ul>
<li>religModerate:opinionNeutral</li>
<li>religModerate:opinionDisagree</li>
<li>religModerate:educAt least some college</li>
<li>religFundamentalist:opinionNeutral</li>
<li>religFundamentalist:educAt least some college</li>
<li>opinionNeutral:educAt least some college</li>
</ul>
<p><em>religModerate:opinionNeutral -1.4293902 0.92350177</em> <em>religFundamentalist:opinionNeutral -1.0566124 1.77303287</em> <em>religModerate:opinionDisagree -0.1375381 2.00722939</em> <strong>religFundamentalist:opinionDisagree 1.2442200 3.54536159</strong> <em>religModerate:educAt least some college -0.5423790 1.13070428</em> <em>religFundamentalist:educAt least some college -0.7922154 1.16236149</em> <em>opinionNeutral:educAt least some college -1.7733304 0.30270736</em> <strong>opinionDisagree:educAt least some college -1.9388926 -0.22115922</strong></p>
<p>I am interpreting these to mean that there are no interactions between these terms. The following groups are independent of each other:</p>
<ul>
<li>Religious moderates and neutrality</li>
<li>Religious fundamentalists and neutrality</li>
<li>Religious moderates and disagreeing</li>
<li>Religious moderates and college</li>
<li>Religious fundamentalists and At least some college</li>
<li>At least some college and Neutrality</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>marriage <span class="sc">|&gt;</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> <span class="fu">log</span>(Freq), <span class="at">color =</span> opinion, <span class="at">size =</span> Freq) <span class="sc">+</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>relig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If we are considering opinion the response, it looks to me like the major interaction here is fundamentalists and college. With the exception of fundamentalists, college tends to result in mostly increasing agreement. However, that is not the case for fundamentalists.</p>
</section>
</section>
<section id="fit-three-way-interactions." class="level2">
<h2 class="anchored" data-anchor-id="fit-three-way-interactions.">2 fit three way interactions.</h2>
<ol start="2" type="1">
<li>Fit a model that includes all two-way and the three-way interactions. Is there anything problematic about this model? Please explain.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># m2 &lt;- glm(data = marriage_tab, </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co">#           family = poisson, </span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co">#           Freq~relig*opinion + relig*educ + opinion*educ)</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># s2 &lt;- summary(m2)</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># s2</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> marriage_tab, </span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> poisson, </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>          Freq<span class="sc">~</span>relig<span class="sc">*</span>opinion<span class="sc">*</span>educ)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(m3)</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>s3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Freq ~ relig * opinion * educ, family = poisson, 
    data = marriage_tab)

Coefficients:
                                                              Estimate
(Intercept)                                                    2.39790
religModerate                                                 -0.31845
religFundamentalist                                           -0.60614
opinionNeutral                                                -0.78846
opinionDisagree                                               -0.60614
educAt least some college                                      0.69315
religModerate:opinionNeutral                                  -0.19237
religFundamentalist:opinionNeutral                            -0.31015
religModerate:opinionDisagree                                  0.72392
religFundamentalist:opinionDisagree                            1.11696
religModerate:educAt least some college                        0.27193
religFundamentalist:educAt least some college                 -1.09861
opinionNeutral:educAt least some college                      -0.91629
opinionDisagree:educAt least some college                     -2.48491
religModerate:opinionNeutral:educAt least some college        -0.04879
religFundamentalist:opinionNeutral:educAt least some college   1.32176
religModerate:opinionDisagree:educAt least some college        0.93204
religFundamentalist:opinionDisagree:educAt least some college  2.98568
                                                              Std. Error
(Intercept)                                                      0.30151
religModerate                                                    0.46466
religFundamentalist                                              0.50752
opinionNeutral                                                   0.53936
opinionDisagree                                                  0.50752
educAt least some college                                        0.36927
religModerate:opinionNeutral                                     0.86559
religFundamentalist:opinionNeutral                               0.97856
religModerate:opinionDisagree                                    0.70263
religFundamentalist:opinionDisagree                              0.72405
religModerate:educAt least some college                          0.55586
religFundamentalist:educAt least some college                    0.74366
opinionNeutral:educAt least some college                         0.76574
opinionDisagree:educAt least some college                        1.14150
religModerate:opinionNeutral:educAt least some college           1.19401
religFundamentalist:opinionNeutral:educAt least some college     1.41528
religModerate:opinionDisagree:educAt least some college          1.33669
religFundamentalist:opinionDisagree:educAt least some college    1.38224
                                                              z value Pr(&gt;|z|)
(Intercept)                                                     7.953 1.82e-15
religModerate                                                  -0.685   0.4931
religFundamentalist                                            -1.194   0.2324
opinionNeutral                                                 -1.462   0.1438
opinionDisagree                                                -1.194   0.2324
educAt least some college                                       1.877   0.0605
religModerate:opinionNeutral                                   -0.222   0.8241
religFundamentalist:opinionNeutral                             -0.317   0.7513
religModerate:opinionDisagree                                   1.030   0.3029
religFundamentalist:opinionDisagree                             1.543   0.1229
religModerate:educAt least some college                         0.489   0.6247
religFundamentalist:educAt least some college                  -1.477   0.1396
opinionNeutral:educAt least some college                       -1.197   0.2315
opinionDisagree:educAt least some college                      -2.177   0.0295
religModerate:opinionNeutral:educAt least some college         -0.041   0.9674
religFundamentalist:opinionNeutral:educAt least some college    0.934   0.3503
religModerate:opinionDisagree:educAt least some college         0.697   0.4856
religFundamentalist:opinionDisagree:educAt least some college   2.160   0.0308
                                                                 
(Intercept)                                                   ***
religModerate                                                    
religFundamentalist                                              
opinionNeutral                                                   
opinionDisagree                                                  
educAt least some college                                     .  
religModerate:opinionNeutral                                     
religFundamentalist:opinionNeutral                               
religModerate:opinionDisagree                                    
religFundamentalist:opinionDisagree                              
religModerate:educAt least some college                          
religFundamentalist:educAt least some college                    
opinionNeutral:educAt least some college                         
opinionDisagree:educAt least some college                     *  
religModerate:opinionNeutral:educAt least some college           
religFundamentalist:opinionNeutral:educAt least some college     
religModerate:opinionDisagree:educAt least some college          
religFundamentalist:opinionDisagree:educAt least some college *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance:  7.2362e+01  on 17  degrees of freedom
Residual deviance: -2.1867e-21  on  0  degrees of freedom
AIC: 100.5

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p><strong>Residual DF are zero, the model is overfit</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                     2.5 %
(Intercept)                                                    1.742480843
religModerate                                                 -1.267420510
religFundamentalist                                           -1.671871082
opinionNeutral                                                -1.943435457
opinionDisagree                                               -1.671871082
educAt least some college                                     -0.009352458
religModerate:opinionNeutral                                  -1.993307908
religFundamentalist:opinionNeutral                            -2.450923140
religModerate:opinionDisagree                                 -0.637748305
religFundamentalist:opinionDisagree                           -0.271365102
religModerate:educAt least some college                       -0.812567305
religFundamentalist:educAt least some college                 -2.635442109
opinionNeutral:educAt least some college                      -2.483332868
opinionDisagree:educAt least some college                     -5.488683217
religModerate:opinionNeutral:educAt least some college        -2.420448446
religFundamentalist:opinionNeutral:educAt least some college  -1.503710058
religModerate:opinionDisagree:educAt least some college       -1.481979451
religFundamentalist:opinionDisagree:educAt least some college  0.502282533
                                                                  97.5 %
(Intercept)                                                    2.9358420
religModerate                                                  0.5859762
religFundamentalist                                            0.3601434
opinionNeutral                                                 0.2228733
opinionDisagree                                                0.3601434
educAt least some college                                      1.4546181
religModerate:opinionNeutral                                   1.4884261
religFundamentalist:opinionNeutral                             1.5435972
religModerate:opinionDisagree                                  2.1457413
religFundamentalist:opinionDisagree                            2.5975239
religModerate:educAt least some college                        1.3871701
religFundamentalist:educAt least some college                  0.3397077
opinionNeutral:educAt least some college                       0.5862740
opinionDisagree:educAt least some college                     -0.5634587
religModerate:opinionNeutral:educAt least some college         2.3367740
religFundamentalist:opinionNeutral:educAt least some college   4.1835517
religModerate:opinionDisagree:educAt least some college        4.1546178
religFundamentalist:opinionDisagree:educAt least some college  6.2766234</code></pre>
</div>
</div>
<p>opinionDisagree:educAt least some college -2.48491 1.14150 -2.177 0.0295 *<br>
religFundamentalist:opinionDisagree:educAt least some college 2.98568 1.38224 2.160 0.0308 *</p>
<p><em>religFundamentalist:opinionNeutral -2.450923140 1.5435972</em> <em>religModerate:opinionDisagree -0.637748305 2.1457413</em> <em>religFundamentalist:opinionDisagree -0.271365102 2.5975239</em> <em>religModerate:educAt least some college -0.812567305 1.3871701</em> <em>religFundamentalist:educAt least some college -2.635442109 0.3397077</em> <em>opinionNeutral:educAt least some college -2.483332868 0.5862740</em> opinionDisagree:educAt least some college -5.488683217 -0.5634587 <em>religModerate:opinionNeutral:educAt least some college -2.420448446 2.3367740</em> <em>religFundamentalist:opinionNeutral:educAt least some college -1.503710058 4.1835517</em> <em>religModerate:opinionDisagree:educAt least some college -1.481979451 4.1546178</em> religFundamentalist:opinionDisagree:educAt least some college 0.502282533 6.2766234</p>
<p><strong>In the model with three way interactions, there were only two significant terms which may be associated with variation in the model. Those are some college/disagreement and fundamentalists/disagree/college. There are 9 interaction terms that appear to be independent of each other, shown above. It looks like college mostly reduced disagreement, except among fundamentalists. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>marriage <span class="sc">|&gt;</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> <span class="fu">log</span>(Freq), <span class="at">color =</span> opinion, <span class="at">size =</span> Freq) <span class="sc">+</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>relig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z5_learnR_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/KingBlkMouth\.github\.io\/Data_Analysis_II_Notes\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>