<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data_Analysis_II_Notes - 7 Mixed Effects</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data_Analysis_II_Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notes" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notes">    
        <li>
    <a class="dropdown-item" href="./1_Types_of_Categoricals.html">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_Props_Risks_Odds.html">
 <span class="dropdown-text">2 Props, Risk &amp; Odds</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./3_Logistic_Regression_I.html">
 <span class="dropdown-text">3 Log Reg I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./4_Logistic_Regression_II.html">
 <span class="dropdown-text">4 Log-Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./5_Log_linear_Regression.html">
 <span class="dropdown-text">5 Log-lin-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./6_Dispersion_Zero_Inflation.html">
 <span class="dropdown-text">6 Disp &amp; 0 Inflation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./7_Random_Effects.html">
 <span class="dropdown-text">7 Random_Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./8_Evaluating_Models.html">
 <span class="dropdown-text">8 Model Eval</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./9_Imp_Pred_Validate.html">
 <span class="dropdown-text">9 Imp, Pred, Validate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_Final_Project.html">
 <span class="dropdown-text">10 Final Project</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="./z0_learnR.html">
 <span class="dropdown-text">LearnR 0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z1_learnR.html">
 <span class="dropdown-text">1 Types of Categoricals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z2_learnR.html">
 <span class="dropdown-text">2 Odds and risks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z3_learnR.html">
 <span class="dropdown-text">3 Log-Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z4_learnR.html">
 <span class="dropdown-text">4 Log Reg II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z5_learnR.html">
 <span class="dropdown-text">5 Log Lin Reg</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z6_learnR.html">
 <span class="dropdown-text">6 Zero Inflation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z7_learnR.html">
 <span class="dropdown-text">7 Mixed Effects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./z8_learnR.html">
 <span class="dropdown-text">8 Model Eval</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hw" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">HW</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hw">    
        <li>
    <a class="dropdown-item" href="./aHW_1.html">
 <span class="dropdown-text">ST-518 HW 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_2.html">
 <span class="dropdown-text">ST-518 HW 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_3.html">
 <span class="dropdown-text">ST-518 HW 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_4.html">
 <span class="dropdown-text">ST-518 HW 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_5.html">
 <span class="dropdown-text">ST-518 HW 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_6.html">
 <span class="dropdown-text">ST-518 HW 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_7.html">
 <span class="dropdown-text">ST-518 HW 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aHW_8.html">
 <span class="dropdown-text">ST-518 HW 8</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#simulation-of-machine-defects" id="toc-simulation-of-machine-defects" class="nav-link active" data-scroll-target="#simulation-of-machine-defects">Simulation of Machine Defects</a></li>
  <li><a href="#epilepsy-example" id="toc-epilepsy-example" class="nav-link" data-scroll-target="#epilepsy-example">Epilepsy Example</a>
  <ul class="collapse">
  <li><a href="#picking-the-random-effects" id="toc-picking-the-random-effects" class="nav-link" data-scroll-target="#picking-the-random-effects">Picking the Random Effects</a></li>
  <li><a href="#looking-at-the-results" id="toc-looking-at-the-results" class="nav-link" data-scroll-target="#looking-at-the-results">Looking at the results</a>
  <ul class="collapse">
  <li><a href="#residual-diagnostics" id="toc-residual-diagnostics" class="nav-link" data-scroll-target="#residual-diagnostics">Residual Diagnostics</a></li>
  </ul></li>
  <li><a href="#more-model-fitting" id="toc-more-model-fitting" class="nav-link" data-scroll-target="#more-model-fitting">More Model Fitting</a></li>
  </ul></li>
  <li><a href="#lab-questions" id="toc-lab-questions" class="nav-link" data-scroll-target="#lab-questions">Lab Questions</a>
  <ul class="collapse">
  <li><a href="#coefficient-estimates" id="toc-coefficient-estimates" class="nav-link" data-scroll-target="#coefficient-estimates">1 Coefficient estimates</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">2</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">3</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">4</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">5</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4">6</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">7 Mixed Effects</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this lab we’ll look at some simulated data that provide a nice demonstration of the interpretation problem presented by generalized linear mixed modeling. We’ll also go through another example of fitting a Generalized Linear Mixed Model (GLMM) and making sense of the output.</p>
<p>To start off, please load these libraries that you’ll need for this lab. Please note that <code>robustbase</code> is new, so you will likely have to install it first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(robustbase) <span class="co"># contains data we'll use</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)     <span class="co"># access the mixed functions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="simulation-of-machine-defects" class="level1">
<h1>Simulation of Machine Defects</h1>
<p>Let’s suppose that we have 10 machines producing a product and that we record the number of defective items that each machine produces at four different times (times 1, 2, 3, 4). In this scenario, we might reasonably expect there to be similarities in numbers of defects for the same machine and differences in numbers of defects from different machines. In this way, thinking of machine as a grouping variable, we would include it in an analysis as a random effect. The response (number of defects) is a count, and in this simulation, we’ll use the Poisson distribution to generate the numbers of defects.</p>
<p>We’ll simulate data from a Poisson model, and use a mixed effects Poisson regression model (a particular kind of GLMM) to fit the data and demonstrate a few things. We’ll also fit a linear mixed effects model so we can demonstrate the important difference between GLMM and LMM in terms of the interpretation of fixed effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">090901</span>) <span class="do">## set seed so we all get the same results</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Machine <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">rep</span>(<span class="dv">4</span>, <span class="dv">10</span>))) <span class="co"># 10 machines, each with 4 defect counts</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>Time <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">10</span>) <span class="co"># Time variable: 1,2,3,4 for each Machine</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>RE <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">2</span>) <span class="co"># generate 10 random effects, one for each Machine</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                              <span class="co"># random effect variance is  4.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>eta <span class="ot">&lt;-</span> <span class="fu">rep</span>(RE, <span class="fu">rep</span>(<span class="dv">4</span>, <span class="dv">10</span>)) <span class="co"># replicate the random effects four times for each Machine</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># See what we have so far:</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(Machine, Time, eta)[<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Machine Time        eta
 [1,]       1    1 -1.9025790
 [2,]       1    2 -1.9025790
 [3,]       1    3 -1.9025790
 [4,]       1    4 -1.9025790
 [5,]       2    1  4.9604863
 [6,]       2    2  4.9604863
 [7,]       2    3  4.9604863
 [8,]       2    4  4.9604863
 [9,]       3    1 -0.3009368
[10,]       3    2 -0.3009368
[11,]       3    3 -0.3009368
[12,]       3    4 -0.3009368</code></pre>
</div>
</div>
<p>The R output above shows the data for the first three machines. Each machine has four time points and one random effect that remains the same for each time point. Now let’s simulate defects from a mixed effects Poisson regression model where the true coefficient for time is 1.1 when <span class="math inline">\(\lambda\)</span> is on the log scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100233</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>llambda <span class="ot">&lt;-</span>  <span class="fl">1.1</span> <span class="sc">*</span> Time <span class="sc">+</span> eta <span class="co"># lambda on the log scale</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fu">exp</span>(llambda)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>Defects <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">40</span>, lambda)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>Simu_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Machine,Time,eta,Defects)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Simu_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Machine</th>
<th style="text-align: right;">Time</th>
<th style="text-align: right;">eta</th>
<th style="text-align: right;">Defects</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1.902579</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-1.902579</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1.902579</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1.902579</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.960486</td>
<td style="text-align: right;">407</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.960486</td>
<td style="text-align: right;">1233</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now, let’s take a look at the data, on the data scale:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Simu_dat, <span class="fu">aes</span>(Time, Defects, <span class="at">group=</span>Machine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It’s actually difficult to visualize the data on the data scale because there’s one machine with <em>a lot</em> of defects, and so all the defects for the other machines are squashed down below about 1000 on the y-axis. Let’s recreate the plot using the log of the defects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Simu_dat, <span class="fu">aes</span>(Time, <span class="fu">log</span>(Defects<span class="fl">+0.1</span>), <span class="at">group=</span>Machine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, let’s fit a GLMM to the simulated data and after that we’ll generate a plot of the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sim1 <span class="ot">&lt;-</span> <span class="fu">glmer</span>(Defects <span class="sc">~</span> Time <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Machine),</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Simu_dat, <span class="at">family =</span> poisson)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sim1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: poisson  ( log )
Formula: Defects ~ Time + (1 | Machine)
   Data: Simu_dat

     AIC      BIC   logLik deviance df.resid 
   305.4    310.4   -149.7    299.4       37 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.6119 -0.6806 -0.1589  0.4385  2.6663 

Random effects:
 Groups  Name        Variance Std.Dev.
 Machine (Intercept) 3.673    1.916   
Number of obs: 40, groups:  Machine, 10

Fixed effects:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.17030    0.60862    0.28     0.78    
Time         1.10981    0.01003  110.67   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
     (Intr)
Time -0.059</code></pre>
</div>
</div>
<p>Remember that we simulated these data with <span class="math inline">\(\beta_0 = 0\)</span>, <span class="math inline">\(\beta_1 = 1.1\)</span> and the random effect variance, <span class="math inline">\(\sigma^2_{\eta} = 4\)</span>. The model summary gives <span class="math inline">\(\hat{\beta}_0 = 0.17 (0.61)\)</span>; <span class="math inline">\(\hat{\beta}_1 = 1.11 (0.01)\)</span> and <span class="math inline">\(\hat{\sigma}^2_{\eta} = 3.67\)</span> The numbers in parentheses after the fixed effect estimates are the standard errors corresponding to those estimates. The GLMM does a very good job of estimating the the parameters, which should not be all that surprising since this is a relatively simple simulation.</p>
<p>The bigger take-away is still to come. Now, we’ll plot the fitted model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Simu_dat<span class="sc">$</span>fits <span class="ot">&lt;-</span> <span class="fu">predict</span>(sim1)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Simu_dat,<span class="fu">aes</span>(Time,<span class="fu">log</span>(Defects<span class="fl">+0.1</span>),<span class="at">by=</span>Machine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(Time,fits))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the fitted model for each Machine. Let’s now add the line that we obtain from just the fixed effects estimates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Simu_dat,<span class="fu">aes</span>(Time,<span class="fu">log</span>(Defects<span class="fl">+0.1</span>),<span class="at">by=</span>Machine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(Time,fits)) <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">0.17</span>, <span class="at">slope =</span> <span class="fl">1.11</span>,<span class="at">color =</span> <span class="st">"red"</span>,<span class="at">linewidth=</span><span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This all looks OK – the fitted line from just the fixed effect estimates (red, thicker line) certainly looks like the average of the fitted lines for all of the machines.</p>
<blockquote class="blockquote">
<p>If you are content to describe the results on the model scale, in this case in terms of log(Defects), then you can interpret the fixed effects estimates without first conditioning on the random effects.</p>
</blockquote>
<p>What if we look at this plot back on the data scale, however?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Simu_dat,<span class="fu">aes</span>(Time,Defects,<span class="at">by=</span>Machine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(Time,<span class="fu">exp</span>(fits))) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span>Time,<span class="at">y=</span><span class="fu">exp</span>(<span class="fl">0.17+1.11</span><span class="sc">*</span>Time)),<span class="at">color=</span><span class="st">"red"</span>,<span class="at">linewidth=</span><span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, back on the data scale, we see the problem – the fixed effects estimates by themselves do not well-represent everything that these data contain. The one machine that has unusually high numbers of defects is <em>not at all</em> well-represented by the thick, red line. If you were to communicate the results using the fixed effects estimates only, you would miss a major part of this story: there’s a big problem with one of the machines!</p>
<p>Let’s dig a little deeper still. What if we remove that one machine with the large number of defects from the plot above?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(Simu_dat<span class="sc">$</span>Defects,Simu_dat<span class="sc">$</span>Machine,sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5     6     7     8     9    10 
   14 17016    80   100   136    17   209    50   183   604 </code></pre>
</div>
</div>
<p>It’s Machine 2 that has all the problems.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(Simu_dat,Machine<span class="sc">!=</span><span class="dv">2</span>),<span class="fu">aes</span>(Time,Defects,<span class="at">by=</span>Machine)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(Time,<span class="fu">exp</span>(fits))) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span>Time,<span class="at">y=</span><span class="fu">exp</span>(<span class="fl">0.17+1.11</span><span class="sc">*</span>Time)),<span class="at">color=</span><span class="st">"red"</span>,<span class="at">size=</span><span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Even among the remaining machines, you can see that the fixed effect estimates do not really represent what’s going on here – there remains another machine that in particular doesn’t look like the others in terms of numbers of defects.</p>
<p>Even though these are simulated data, you can see that in this particular case, the interesting answer <em>isn’t</em> about the fixed effects estimates, it’s about the identification of one Machine (maybe more!) that has an unusual number of defects relative to the others.</p>
<p>There’s a good display in Agresti, Figure 13.1 on page 496, that provides another demonstration of how the fixed effect estimates from the GLMM does not well-represent all the structure in the data.</p>
<blockquote class="blockquote">
<p>Because of the presence of the random effect, and the non-linearity of the model on the data scale, the results from GLMM must be interpreted conditionally upon the random effects.</p>
</blockquote>
</section>
<section id="epilepsy-example" class="level1">
<h1>Epilepsy Example</h1>
<p>Now that we’ve examined some simulated data, let’s look at some real data to see how GLMM can be applied to actual data. The epilepsy data set contains information on the number of epilepsy attacks patients had during four follow-up periods post-treatment. Each patient received either an experimental anti-seizure treatment or a placebo, and for each patient additional information – baseline number of epilepsy attacks in the 8 weeks prior to randomization and age – is also included. The question of interest here is whether the treatment, a drug called <strong>progabide</strong>, reduced the number of seizures.</p>
<p>Let’s start by taking a look at the data and its help file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ?epilepsy</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(epilepsy)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(epilepsy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">Y1</th>
<th style="text-align: right;">Y2</th>
<th style="text-align: right;">Y3</th>
<th style="text-align: right;">Y4</th>
<th style="text-align: right;">Base</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Trt</th>
<th style="text-align: right;">Ysum</th>
<th style="text-align: right;">Age10</th>
<th style="text-align: right;">Base4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">104</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">2.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">106</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">2.75</td>
</tr>
<tr class="odd">
<td style="text-align: right;">107</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">1.50</td>
</tr>
<tr class="even">
<td style="text-align: right;">114</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">36</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">3.6</td>
<td style="text-align: right;">2.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">116</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">2.2</td>
<td style="text-align: right;">16.50</td>
</tr>
<tr class="even">
<td style="text-align: right;">118</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">29</td>
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">6.75</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="at">formula=</span><span class="sc">~</span>Trt,<span class="at">data=</span>epilepsy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Trt
  placebo progabide 
       28        31 </code></pre>
</div>
</div>
<p>The variable <code>Ysum</code> contains the cumulative sum of epilepsy attacks beginning at the treatment period to the end of the 8-week study while the variable <code>Base</code> contains the total epilepsy attacks in the 8 weeks prior to treatment. We might first investigate if the average number of seizures per week after treatment is related to the average number of seizures per week prior to treatment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>epilepsy) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Base <span class="sc">/</span> <span class="dv">8</span>, Ysum <span class="sc">/</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Seizures per Week before Treatment"</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Seizures per Week after Treatment"</span>) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>,<span class="at">intercept =</span> <span class="dv">0</span>) <span class="do">## reference line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From these plots, there does seem to be a relationship between average number of seizures before and after treatment though it’s somewhat difficult to see everything we might want to see because much of the data are clumped at low numbers of seizures. Let’s try plotting the data on the log-log scale, adding a small number to each of the counts to avoid the log(0) problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>epilepsy) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(Base<span class="fl">+0.1</span>), <span class="at">y =</span> <span class="fu">log</span>(Ysum<span class="fl">+0.1</span>))) <span class="sc">+</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Seizures per Week before Treatment (log scale)"</span>) <span class="sc">+</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Seizures per Week after Treatment (log scale)"</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>,<span class="at">intercept =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It certainly seems as though patients who have a lot of seizures before treatment also have a lot of them after treatment, regardless of whether they actually receive the treatment or the placebo.</p>
<p>There are any number of things we might do next. For example, we can also look at a table of improvements to see what proportion of patients on the placebo improved after the treatment period and what proportion of patients on the treatment improved after the treatment period.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>epilepsy<span class="sc">$</span>improvement <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(epilepsy<span class="sc">$</span>Ysum<span class="sc">/</span><span class="dv">8</span> <span class="sc">&lt;</span> epilepsy<span class="sc">$</span>Base<span class="sc">/</span><span class="dv">8</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"improved"</span>,<span class="st">"didn't"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="at">formula=</span><span class="sc">~</span>Trt<span class="sc">+</span>improvement, <span class="at">data=</span>epilepsy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           improvement
Trt         didn't improved
  placebo       16       12
  progabide     10       21</code></pre>
</div>
</div>
<p>So 12/28 or 43% improved on placebo, whereas 21/31 or 68% improved on progabide. Let’s look at odds of improvement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>success <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">21</span>) <span class="do">## number who improved on the placebo, progabide</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>fail <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">10</span>) <span class="do">## number who did not improve on the placebo, progabide</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>resp <span class="ot">=</span> <span class="fu">cbind</span>(success, fail)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>trt <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="do">## coding 0 as the placebo group, 1 as progabide</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>out <span class="ot">=</span> <span class="fu">glm</span>(resp <span class="sc">~</span> trt, <span class="at">family=</span>binomial) <span class="do">## simple GLM </span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = resp ~ trt, family = binomial)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -0.2877     0.3819  -0.753   0.4513  
trt           1.0296     0.5417   1.901   0.0573 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3.7305e+00  on 1  degrees of freedom
Residual deviance: 8.8818e-16  on 0  degrees of freedom
AIC: 11.552

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(<span class="fl">3.73</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05344339</code></pre>
</div>
</div>
<p>With a p-value of 0.05344, there is moderate to weak evidence of a treatment effect. The odds of improvement on progabide are estimated to be 2.8 times the odds of improvement on placebo.</p>
<p><strong>However</strong>, notice that so far, we have disregarded a lot of the information here (Age of patient and during which of the time periods the seizures occurred). If the researcher’s question of interest is only in reducing the total number of seizures in the 8-week follow-up period, then perhaps one of the methods above would suffice. The structure of the experiment, however, with repeated measurements per subject, suggests that we might also learn something about the progression of seizures over the eight week post-treatment period. For this, we’ll turn to a GLMM using subject as the random effect.</p>
<p>We first have to gather all of the responses, Y1, Y2, Y3, and Y4, together into one column (called <code>Seizures</code>), and add a new column (<code>Visit</code>) to keep track of which seizure counts correspond to which visits, post-treatment. Then we’ll be able to look at plots of the counts across time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>epil_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(epilepsy, <span class="fu">c</span>(Y1, Y2, Y3, Y4), <span class="at">names_to=</span><span class="st">"Visit"</span>, <span class="at">values_to=</span><span class="st">"Seizures"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>epil_long <span class="sc">%&lt;&gt;%</span> <span class="fu">arrange</span>(.,ID)  <span class="co"># sort by patient ID</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>epil_long <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(.,<span class="at">ID =</span> <span class="fu">as.factor</span>(ID),<span class="at">Visit =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">59</span>))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>        <span class="co"># change ID to factor and Visit to numeric</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(epil_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: right;">Base</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Trt</th>
<th style="text-align: right;">Ysum</th>
<th style="text-align: right;">Age10</th>
<th style="text-align: right;">Base4</th>
<th style="text-align: left;">improvement</th>
<th style="text-align: right;">Visit</th>
<th style="text-align: right;">Seizures</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">101</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: left;">improved</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">101</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: left;">improved</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">101</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: left;">improved</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">101</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: left;">improved</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">102</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: left;">improved</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">102</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: left;">improved</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Visit,Seizures,<span class="at">by=</span>ID)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Well, these look a little bit like spaghetti. Let’s check on the log scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Visit,<span class="fu">log</span>(Seizures<span class="fl">+0.1</span>),<span class="at">by=</span>ID)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Still spaghetti, but at least we can see a couple of things:</p>
<ol type="1">
<li><p>It’s not clear that progabide is generally better, and for one patient it’s particularly bad (though we should check the baseline number of seizures for that patient).</p></li>
<li><p>It’s not clear that there are differences in seizure numbers through time on either medication (although it’s a little hard to tell when some of the counts jump down to zero).</p></li>
</ol>
<p>Just to make a thorough examination of the data, let’s check for any differences in the Ages or in the Baseline numbers of seizures between the two groups. This was a randomized study, so there <em>shouldn’t</em> be differences in these covariates (i.e., the randomization should balance these out), but it never hurts to check.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> epilepsy, <span class="fu">aes</span>(<span class="at">x =</span> Trt, <span class="at">y =</span> Base)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">width=</span>.<span class="dv">01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> epilepsy, <span class="fu">aes</span>(<span class="at">x =</span> Trt, <span class="at">y =</span> Age)) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">width=</span>.<span class="dv">01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There’s not really any evidence that age or baseline number of attacks differ between the placebo and progabide group. There is one subject in the progabide group with an unusually high number of seizures at baseline – you can check to see if this is the same patient with the unusually high number after treatment.</p>
<p>Let’s fit a GLMM and see if our visual inspections are validated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glmer</span>(Seizures <span class="sc">~</span> Trt <span class="sc">+</span> Base <span class="sc">+</span> Age <span class="sc">+</span> Visit <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>        (<span class="dv">1</span><span class="sc">|</span>ID), <span class="at">family =</span> poisson, <span class="at">data =</span> epil_long)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: poisson  ( log )
Formula: Seizures ~ Trt + Base + Age + Visit + (1 | ID)
   Data: epil_long

     AIC      BIC   logLik deviance df.resid 
  1349.2   1370.0   -668.6   1337.2      230 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.2867 -0.8240 -0.1332  0.5549  7.2848 

Random effects:
 Groups Name        Variance Std.Dev.
 ID     (Intercept) 0.2856   0.5344  
Number of obs: 236, groups:  ID, 59

Fixed effects:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.666765   0.410081   1.626  0.10396    
Trtprogabide -0.261043   0.154119  -1.694  0.09031 .  
Base          0.027235   0.002799   9.731  &lt; 2e-16 ***
Age           0.014254   0.012548   1.136  0.25597    
Visit        -0.058725   0.020178  -2.910  0.00361 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) Trtprg Base   Age   
Trtprogabid -0.289                     
Base        -0.392 -0.006              
Age         -0.931  0.114  0.190       
Visit       -0.119  0.000  0.000  0.000</code></pre>
</div>
</div>
<section id="picking-the-random-effects" class="level2">
<h2 class="anchored" data-anchor-id="picking-the-random-effects">Picking the Random Effects</h2>
<p>In the model we just fit, we used a random intercepts model that just includes a random effect for patient. Specifically what this means that is the intercept term will be estimated differently for each patient.</p>
<p>Depending on the particular problem, this may or may not be a reasonable way to think about the variation in the data. In the context of this epilepsy example, it could be that the different patients show different <em>rates of change</em> in their numbers of seizures – this would suggest that each patient have his or her own effect of visit. We can accomplish this by putting in a random effect for visit.</p>
<p>Next we’ll fit a random intercepts and slopes model with <code>Visit</code> as the random slope. Again, this seems like a reasonable thing to do if we expect that some subjects will have a different rate of increase or decrease of number of seizures over time than other subjects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glmer</span>(Seizures <span class="sc">~</span> Trt <span class="sc">+</span> Base <span class="sc">+</span> Age <span class="sc">+</span> Visit <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Visit<span class="sc">|</span>ID), <span class="at">family =</span> poisson, <span class="at">data =</span> epil_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
Model failed to converge with max|grad| = 0.00368596 (tol = 0.002, component 1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># oops this didn't converge --- try the initialization trick again:</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>(init <span class="ot">&lt;-</span> <span class="fu">getME</span>(mod2, <span class="at">name =</span> <span class="fu">c</span>(<span class="st">"theta"</span>, <span class="st">"fixef"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$theta
      ID.(Intercept) ID.Visit.(Intercept)             ID.Visit 
          0.60038496          -0.06873505           0.12686483 

$fixef
 (Intercept) Trtprogabide         Base          Age        Visit 
  0.61274912  -0.25315623   0.02736649   0.01545712  -0.05904358 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glmer</span>(Seizures <span class="sc">~</span> Trt <span class="sc">+</span> Base <span class="sc">+</span> Age <span class="sc">+</span> Visit <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Visit<span class="sc">|</span>ID), <span class="at">family =</span> poisson, <span class="at">data =</span> epil_long, <span class="at">start =</span> init)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: poisson  ( log )
Formula: Seizures ~ Trt + Base + Age + Visit + (1 + Visit | ID)
   Data: epil_long

     AIC      BIC   logLik deviance df.resid 
  1333.1   1360.8   -658.5   1317.1      228 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.9215 -0.7439 -0.0919  0.5534  6.3674 

Random effects:
 Groups Name        Variance Std.Dev. Corr 
 ID     (Intercept) 0.36044  0.6004        
        Visit       0.02082  0.1443   -0.48
Number of obs: 236, groups:  ID, 59

Fixed effects:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.61284    0.41536   1.475   0.1401    
Trtprogabide -0.25314    0.15324  -1.652   0.0986 .  
Base          0.02737    0.00278   9.843   &lt;2e-16 ***
Age           0.01545    0.01273   1.214   0.2247    
Visit        -0.05904    0.03252  -1.816   0.0694 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) Trtprg Base   Age   
Trtprogabid -0.290                     
Base        -0.398 -0.003              
Age         -0.923  0.122  0.198       
Visit       -0.128 -0.018  0.009 -0.056</code></pre>
</div>
</div>
<p>The estimated variance for the <code>Visit</code> random effect is pretty small (0.02), but the fixed effect estimate for <code>Visit</code> is pretty small too (-0.06), so that random effect variance may still be important to consider. Remember that we can compare the two models with the <code>AIC</code> and <code>BIC</code> functions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod1, mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1349.228</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1333.084</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod1, mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1370.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1360.794</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Both criteria indicate that the model with random slopes for <code>Visit</code> is somewhat preferred over the model with only random intercepts, though simplicity and that the AIC and BIC are not very different (i.e., each for <code>mod1</code> vs <code>mod2</code>) would argue for using the model with only one random effect. As mentioned in last lab, in a real problem situation, we really want to think more carefully about what the model should be <strong>before</strong> fitting anything to the data. Choosing which model after fitting many models is a type of data snooping and should generally be avoided.</p>
</section>
<section id="looking-at-the-results" class="level2">
<h2 class="anchored" data-anchor-id="looking-at-the-results">Looking at the results</h2>
<p>Let’s go back to the random intercept only model and interpret/understand the model output. This model is already a bit complex but is somewhat simpler than the random intercepts and random slopes model (<code>mod2</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: poisson  ( log )
Formula: Seizures ~ Trt + Base + Age + Visit + (1 | ID)
   Data: epil_long

     AIC      BIC   logLik deviance df.resid 
  1349.2   1370.0   -668.6   1337.2      230 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.2867 -0.8240 -0.1332  0.5549  7.2848 

Random effects:
 Groups Name        Variance Std.Dev.
 ID     (Intercept) 0.2856   0.5344  
Number of obs: 236, groups:  ID, 59

Fixed effects:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.666765   0.410081   1.626  0.10396    
Trtprogabide -0.261043   0.154119  -1.694  0.09031 .  
Base          0.027235   0.002799   9.731  &lt; 2e-16 ***
Age           0.014254   0.012548   1.136  0.25597    
Visit        -0.058725   0.020178  -2.910  0.00361 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) Trtprg Base   Age   
Trtprogabid -0.289                     
Base        -0.392 -0.006              
Age         -0.931  0.114  0.190       
Visit       -0.119  0.000  0.000  0.000</code></pre>
</div>
</div>
<p>Before we comment on the model summary information, let’s perform some diagnostics to see if we feel like we have a good model to work with.</p>
<section id="residual-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="residual-diagnostics">Residual Diagnostics</h3>
<p>Let’s also take a look at some residual plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>epil_long<span class="sc">$</span>resid <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod1)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>epil_long<span class="sc">$</span>fits <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(mod1))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># first some plots of the residuals vs. explanatory variables </span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Visit,resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Base,resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Age,resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># now a look at the normality of the random effects</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">unlist</span>((<span class="fu">ranef</span>(mod1)<span class="sc">$</span>ID)))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">unlist</span>((<span class="fu">ranef</span>(mod1)<span class="sc">$</span>ID)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># finally, fitted values versus observations</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Seizures,fits)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt) <span class="sc">+</span> <span class="fu">geom_abline</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-24-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(<span class="fu">log</span>(Seizures<span class="fl">+0.1</span>),<span class="fu">log</span>(fits<span class="fl">+0.1</span>))) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt) <span class="sc">+</span> <span class="fu">geom_abline</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-24-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are a number of things to discuss based on these plots:</p>
<ol type="1">
<li><p>It looks like there’s evidence of some curvilinearity in the relationship between <code>Visit</code> and <code>Seizures</code>; the nature of that curvilinearity might be different for the two treatment groups (look at plot of <code>resid</code> versus <code>Visit</code>). You could add <code>Visit2</code> term, the square of <code>Visit</code>, or you could revert <code>Visit</code> back to a factor variable.</p></li>
<li><p>There is what appears to be one large outlier in the placebo group. If we had access to the original researchers, we might have been able to find out about that unusual value.</p></li>
<li><p>It seems that the random effects are not strictly Normal, especially in the upper tail. This may be because we haven’t gotten the fixed effects part of the model correctly specified.</p></li>
<li><p>There are some zeroes among the <code>Seizure</code> values, and the model is not fitting those very well – we may need to think about a zero-inflated model and/or a model for over dispersion.</p></li>
</ol>
</section>
</section>
<section id="more-model-fitting" class="level2">
<h2 class="anchored" data-anchor-id="more-model-fitting">More Model Fitting</h2>
<p>There is a <code>glmer.nb()</code> function in the <code>lme4</code> package, so we’ll try using that below. There are zero-inflated GLMM models, but they get rather complicated. We’ll leave it to you to explore those if you’re interested. Also, you might want to investigate what happens when you put terms in the model for the square of <code>Visit</code> and the interactions between <code>Trt</code> and the <code>Visit</code> variables (i.e., <code>Visit</code> and it’s square). Again, we’ll leave this to you for further exploration.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first, glmer.nb with the same form as above</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glmer.nb</span>(Seizures <span class="sc">~</span> Trt <span class="sc">+</span> Age <span class="sc">+</span> Base <span class="sc">+</span> Visit <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>ID), <span class="at">data =</span> epil_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
Model failed to converge with max|grad| = 0.0181557 (tol = 0.002, component 1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>init <span class="ot">&lt;-</span> <span class="fu">getME</span>(mod3,<span class="at">name=</span><span class="fu">c</span>(<span class="st">"theta"</span>,<span class="st">"fixef"</span>))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glmer.nb</span>(Seizures <span class="sc">~</span> Trt <span class="sc">+</span> Age <span class="sc">+</span> Base <span class="sc">+</span> Visit <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>ID), <span class="at">data =</span> epil_long, <span class="at">start =</span> init)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
Model failed to converge with max|grad| = 0.00295742 (tol = 0.002, component 1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: Negative Binomial(7.4718)  ( log )
Formula: Seizures ~ Trt + Age + Base + Visit + (1 | ID)
   Data: epil_long

     AIC      BIC   logLik deviance df.resid 
  1269.2   1293.4   -627.6   1255.2      229 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.9219 -0.6026 -0.1096  0.4506  3.6929 

Random effects:
 Groups Name        Variance Std.Dev.
 ID     (Intercept) 0.2522   0.5021  
Number of obs: 236, groups:  ID, 59

Fixed effects:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.662022   0.416600   1.589   0.1120    
Trtprogabide -0.260516   0.154359  -1.688   0.0915 .  
Age           0.014057   0.012567   1.119   0.2633    
Base          0.027184   0.002806   9.687   &lt;2e-16 ***
Visit        -0.052231   0.033086  -1.579   0.1144    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) Trtprg Age    Base  
Trtprogabid -0.286                     
Age         -0.919  0.115              
Base        -0.387 -0.006  0.189       
Visit       -0.205  0.004  0.010  0.001</code></pre>
</div>
</div>
<p>Let’s compare this model to the Poisson GLMM above (<code>mod1</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod1,mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1349.228</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1269.198</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod1,mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1370.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1293.445</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>OK, it seems like the negative binomial model is more appropriate here, so we’ll proceed with that. If you look at the summary information for <code>mod3</code> it now appears that there’s still only marginal evidence in support of a treatment effect (p = 0.09). Next, we’ve replicated the residual diagnostics that we showed above, but for the <code>mod3</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>epil_long<span class="sc">$</span>resid <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod3)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>epil_long<span class="sc">$</span>fits <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(mod3))</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># first some plots of the residuals vs. explanatory variables </span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Visit,resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Base,resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Age,resid)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-27-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># now a look at the normality of the random effects</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">unlist</span>((<span class="fu">ranef</span>(mod1)<span class="sc">$</span>ID)))</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">unlist</span>((<span class="fu">ranef</span>(mod1)<span class="sc">$</span>ID)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-27-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># finally, fitted values versus observations</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(Seizures,fits)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt) <span class="sc">+</span> <span class="fu">geom_abline</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-27-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long,<span class="fu">aes</span>(<span class="fu">log</span>(Seizures<span class="fl">+0.1</span>),<span class="fu">log</span>(fits<span class="fl">+0.1</span>))) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trt) <span class="sc">+</span> <span class="fu">geom_abline</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-27-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We still see many of the same problems we noted above, but despite that we won’t proceed beyond this model for the purpose of this Lab. <em>If</em> this were the final model from which we were to report results, we might say something like:</p>
<blockquote class="blockquote">
<p>We fit a generalized linear mixed model to the epilespy data, assuming that the number of seizures follows a negative binomial distribution and with a log link. The fixed effects are age, baseline number of seizures and visit, and the random effect is subject, to account for the repeated measurements for each subject. From this model, there is no evidence of an effect of the progabide treatment (p = 0.09), and the only factor that appears to be associated with the number of seizures post-treatment is the baseline number of seizures.</p>
</blockquote>
<p>One final note. <em>If</em> our final model does provide evidence of a treatment effect, we can go ahead and report the p-value. It will be difficult to quantify the treatment effect, however, because you’ll have to do that in the context of conditioning on the random subjects.</p>
</section>
</section>
<section id="lab-questions" class="level1">
<h1>Lab Questions</h1>
<p>In the <code>epilepsy</code> data, we really need to use a mixed effects model to account for the fact that observations within a subject are almost certainly not independent. Let’s suppose, however, that we are a naive statistician and do not realize that we need to account for this within subject correlation. Instead we fit a Poisson GLM and completely ignore the fact that we have non-independent observations (to be clear, this is <strong>not</strong> a correct way to do the analysis, but we are fitting the model to compare the results we get to the results from the more appropriate GLMM we fit above).</p>
<p>Please write 1-2 sentences in response to the following questions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mod3 &lt;- glmer.nb(Seizures ~ Trt + Age + Base + Visit + (1|ID), data = epil_long)</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="co"># init &lt;- getME(mod3,name=c("theta","fixef"))</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># mod3 &lt;- glmer.nb(Seizures ~ Trt + Age + Base + Visit + (1|ID), data = epil_long, start = init)</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(mod3)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mod.norand <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Seizures <span class="sc">~</span> Trt <span class="sc">+</span> Age <span class="sc">+</span> Base <span class="sc">+</span> Visit, <span class="at">data =</span> epil_long)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.norand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Seizures ~ Trt + Age + Base + Visit, data = epil_long, 
    init.theta = 2.417515912, link = log)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.661252   0.292126   2.264   0.0236 *  
Trtprogabide -0.189856   0.101516  -1.870   0.0615 .  
Age           0.017817   0.008234   2.164   0.0305 *  
Base          0.026865   0.001756  15.299   &lt;2e-16 ***
Visit        -0.044973   0.045012  -0.999   0.3177    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(2.4175) family taken to be 1)

    Null deviance: 554.89  on 235  degrees of freedom
Residual deviance: 265.34  on 231  degrees of freedom
AIC: 1325.4

Number of Fisher Scoring iterations: 1

              Theta:  2.418 
          Std. Err.:  0.325 

 2 x log-likelihood:  -1313.417 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate  Std. Error   z value     Pr(&gt;|z|)
(Intercept)   0.66202163 0.416600169  1.589106 1.120366e-01
Trtprogabide -0.26051591 0.154358783 -1.687730 9.146312e-02
Age           0.01405663 0.012566776  1.118555 2.633299e-01
Base          0.02718444 0.002806301  9.686930 3.426738e-22
Visit        -0.05223065 0.033086077 -1.578629 1.144211e-01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.norand)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate  Std. Error    z value     Pr(&gt;|z|)
(Intercept)   0.66125191 0.292126465  2.2635810 2.359990e-02
Trtprogabide -0.18985590 0.101516373 -1.8701998 6.145608e-02
Age           0.01781657 0.008234001  2.1637805 3.048120e-02
Base          0.02686460 0.001755952 15.2991685 7.743965e-53
Visit        -0.04497306 0.045011777 -0.9991399 3.177269e-01</code></pre>
</div>
</div>
<section id="coefficient-estimates" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-estimates">1 Coefficient estimates</h2>
<p>1.) How do the coefficient estimates for the fixed effects compare in the two models? Why do you think the coefficient estimates are approximately the same or very different?</p>
<p>They are similar.</p>
<p>A regular negative binomial gets one ML estimate for all the data. A negative binomial with random intercepts per group has a fixed effect ML estimate for all the data, where variation by group is accounted for by random intercepts. In this case I think the two models have very similar estimates because the variation due to grouping was low enough to not change the estimates that much.</p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">2</h2>
<p>2.) How do the standard errors for the coefficients compare in the two models? Why do you think the standard errors are approximately the same or very different?</p>
<p>The standard errors are much different. The model without mixed effects has lower SEs than the one with them, except for visit which is higher.</p>
<p>In this case, there is dispersion due to clustering. The model without mixed effects doesn’t account for the clustering. So, its standard errors are too small.</p>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1">3</h2>
<p>3.) How do the p-values compare for the two models?</p>
<p>The regular negative binomial model’s p-values are lower except for visit, which is higher. p-values are dependent on the standard errors.</p>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2">4</h2>
<p>4.) Based on your answers from (1) to (3), what is the danger in assuming independence between all the observations, when, in fact, some of the observations are not independent?</p>
<p>The danger is that inference will be invalid due to lack of independence. Standard errors and p-values will be too small. Effects may be declared significant by mistake.</p>
<p>Let’s next look at the first 40 fitted values for the incorrectly fitted model without a random effect for subject and the GLMM with a random effect for subject.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">fitted</span>(mod.norand), <span class="fu">fitted</span>(mod3))[<span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>, ] <span class="co">#|&gt; head()</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> t <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">&lt;-</span> t <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">norand_min_rand =</span> V1 <span class="sc">-</span> V2) <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(norand_min_rand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-3" class="level2">
<h2 class="anchored" data-anchor-id="section-3">5</h2>
<p>5.) How do the fitted values from the two models compare? Are the fitted values from one model consistently higher or lower than the other model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(t2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       V1               V2         norand_min_rand   
 Min.   : 2.968   Min.   : 1.978   Min.   :-10.1657  
 1st Qu.: 3.354   1st Qu.: 2.942   1st Qu.:  0.1650  
 Median : 3.931   Median : 3.500   Median :  0.4299  
 Mean   : 5.318   Mean   : 5.478   Mean   : -0.1599  
 3rd Qu.: 5.558   3rd Qu.: 6.607   3rd Qu.:  1.1962  
 Max.   :16.262   Max.   :16.178   Max.   :  4.4380  </code></pre>
</div>
</div>
<p>The model without mixed effects is usually higher than the one with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(t2) <span class="sc">+</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(V2, V1) <span class="sc">+</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section-4" class="level2">
<h2 class="anchored" data-anchor-id="section-4">6</h2>
<p>6.) Notice fitted values 37 through 40. These values correspond to the 10th subject in the data set (subject ID 112). Can you justify why these fitted values are much higher in the GLMM? In your justification, can you include a plot of some sort that highlights this particular subject?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>t[<span class="dv">37</span><span class="sc">:</span><span class="dv">40</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">V1</th>
<th style="text-align: right;">V2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">37</td>
<td style="text-align: right;">6.011792</td>
<td style="text-align: right;">16.17753</td>
</tr>
<tr class="even">
<td style="text-align: left;">38</td>
<td style="text-align: right;">5.747412</td>
<td style="text-align: right;">15.35425</td>
</tr>
<tr class="odd">
<td style="text-align: left;">39</td>
<td style="text-align: right;">5.494660</td>
<td style="text-align: right;">14.57287</td>
</tr>
<tr class="even">
<td style="text-align: left;">40</td>
<td style="text-align: right;">5.253022</td>
<td style="text-align: right;">13.83126</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>epil_long <span class="sc">|&gt;</span> <span class="fu">filter</span>(ID <span class="sc">==</span> <span class="dv">112</span> <span class="sc">|</span>ID <span class="sc">==</span> <span class="dv">113</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 11%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: right;">Base</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Trt</th>
<th style="text-align: right;">Ysum</th>
<th style="text-align: right;">Age10</th>
<th style="text-align: right;">Base4</th>
<th style="text-align: left;">improvement</th>
<th style="text-align: right;">Visit</th>
<th style="text-align: right;">Seizures</th>
<th style="text-align: right;">resid</th>
<th style="text-align: right;">fits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">112</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.7436494</td>
<td style="text-align: right;">16.177527</td>
</tr>
<tr class="even">
<td style="text-align: left;">112</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.2334746</td>
<td style="text-align: right;">15.354251</td>
</tr>
<tr class="odd">
<td style="text-align: left;">112</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.6256015</td>
<td style="text-align: right;">14.572872</td>
</tr>
<tr class="even">
<td style="text-align: left;">112</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.3315202</td>
<td style="text-align: right;">13.831258</td>
</tr>
<tr class="odd">
<td style="text-align: left;">113</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0673093</td>
<td style="text-align: right;">4.809035</td>
</tr>
<tr class="even">
<td style="text-align: left;">113</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-0.2143688</td>
<td style="text-align: right;">4.564303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">113</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.9056346</td>
<td style="text-align: right;">4.332025</td>
</tr>
<tr class="even">
<td style="text-align: left;">113</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">progabide</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: left;">didn’t</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-0.0444647</td>
<td style="text-align: right;">4.111568</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ?epilepsy</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">filter</span>(epil_long, ID <span class="sc">==</span> <span class="dv">112</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epil_long[<span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>,]) <span class="sc">+</span> </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(Base, Ysum) <span class="sc">+</span> </span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> l, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="z7_learnR_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I this set, patient 112 had more seizures after the treatment compared to the number of seizures before. The GLMM is doing a better job fitting the data than the glm.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/KingBlkMouth\.github\.io\/Data_Analysis_II_Notes\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>