{
  "hash": "b35743e8a4fe1c0bbff0f1dd9de8237a",
  "result": {
    "markdown": "---\ntitle: \"LearnR 4\"\nexecute: \n  freeze: auto\n---\n\n\n\n# Count responses\n\nPlease load these libraries that you'll need for this lab:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(arm)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'arm' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: MASS\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: Matrix\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: lme4\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\narm (Version 1.14-4, built: 2024-4-1)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWorking directory is C:/Users/cmeck/Desktop/D_Anal/Anal_II/Anal_II_Notes/Data_Analysis_II_Notes\n```\n:::\n\n```{.r .cell-code}\nlibrary(Sleuth3)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.0     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ tidyr::expand() masks Matrix::expand()\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ tidyr::pack()   masks Matrix::pack()\n✖ dplyr::select() masks MASS::select()\n✖ tidyr::unpack() masks Matrix::unpack()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(vcdExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'vcdExtra' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: vcd\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'vcd' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: grid\nLoading required package: gnm\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'gnm' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'vcdExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    summarise\n```\n:::\n\n```{.r .cell-code}\nlibrary(magrittr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'magrittr'\n\nThe following object is masked from 'package:purrr':\n\n    set_names\n\nThe following object is masked from 'package:tidyr':\n\n    extract\n```\n:::\n:::\n\n\nIn this lab, we'll go over some of the finer details of binomial logistic regression that you only saw briefly in the narrated lectures. We'll cover the drop in deviance and deviance goodness of fit tests, and show how to perform them using R. We'll also talk more about residuals from binomial logistic regression and about the dispersion parameter and over dispersion. Two additional topics are (1) a pathological (but not altogether rare) situation that can arise in logistic regression and (2) using logistic regression to perform a test of the difference in two proportions.\n\n# Binomial logistic regression\n\nIn the previous lab, we introduced binary logistic regression in the context of a continuous explanatory variable (age).  In this situation, each individual could, in principle, have had a unique combination of values of the explanatory variables.  In practice, due to rounding of ages to whole years, there were several explanatory variable combinations that occurred multiple times (this was why we had to jitter the plot of survival vs age). For those particular combinations of the explanatory variables, we could count up the number of Donner party survivors and non-survivors -- so we'd have a count as the response, rather than a binary observations.\n\nWe are typically still inclined to think of the survival of *individual* Donner Party members, however; rather than in terms of the *count* of survivors out of the total number of members at each age-sex combination.\n\nIn this lab, we take a different perspective on logistic regression.  We consider binary observations that are clustered into groups, where the *counts* of outcomes in each group are the natural measurements of interest.  We consider each count to have a *binomial* distribution with some probability $p$, and derive the log-odds from these binomial probabilities.  Since a binomial $p$ comes from an underlying Bernoulli $p$ (or since a Bernoulli is a special case of a binomial), however, logistic regressions for binary outcomes and binomial counts are not fundamentally different beasts -- they use the same model equations, they are fit with the same R function, they estimate the same parameters, and they rely on the same assumptions.  Using binomial logistic regression when applicable, though, makes *checking* some of those assumptions more direct.  \n\n## Aflatoxin data\n\nIn this lab we will continue with the `ex2116` data from *Sleuth3*, introduced in lecture.  Each of 20 tanks was stocked with fishes that had been exposed as embryos to one of 5 doses of a carcinogen.  When the fishes were dissected a year later, the number of fishes that had developed liver tumors was recorded.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(ex2116)\ntumors <- ex2116\nhead(tumors)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  Dose| Tumor| Total|\n|-----:|-----:|-----:|\n| 0.010|     9|    87|\n| 0.010|     5|    86|\n| 0.010|     2|    89|\n| 0.010|     9|    85|\n| 0.025|    30|    86|\n| 0.025|    41|    86|\n\n</div>\n:::\n:::\n\n\nHere we'll add a column that records the number of fish in each tank which did not develop liver tumors, and a column that assigns a unique label to each of the 20 tanks. We'll also add a column for log(Dose) and log(Dose)^2 since we used those as explanatory variables in the model you saw in the narrated lectures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntumors %<>% mutate(Dose = Dose, Tumor = Tumor, NoTumor = Total - Tumor, TankID = factor(1:nrow(tumors)),logDose = log(Dose), logDose2 = log(Dose)^2)\nhead(tumors)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  Dose| Tumor| Total| NoTumor|TankID |  logDose| logDose2|\n|-----:|-----:|-----:|-------:|:------|--------:|--------:|\n| 0.010|     9|    87|      78|1      | -4.60517| 21.20759|\n| 0.010|     5|    86|      81|2      | -4.60517| 21.20759|\n| 0.010|     2|    89|      87|3      | -4.60517| 21.20759|\n| 0.010|     9|    85|      76|4      | -4.60517| 21.20759|\n| 0.025|    30|    86|      56|5      | -3.68888| 13.60783|\n| 0.025|    41|    86|      45|6      | -3.68888| 13.60783|\n\n</div>\n:::\n:::\n\n\nWe'll also create a case-format version that records the binary status (tumor or not) for each of the 1739 individual fishes.  \n# check code tumors_case$Outcome should be a factor\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The syntax dplyr::select() ensures that the select() function from the dplyr package is \n# used instead of the select() function from the MASS package, in case you still have MASS\n# loaded in the library.\ntumors_freq <- tumors %>% dplyr::select(-Total) %>%\n  pivot_longer(Tumor:NoTumor,names_to=\"Outcome\",values_to=\"Freq\",cols_vary = \"slowest\") %>%\n  mutate(Outcome=as.factor(Outcome))\ntumors_case <- expand.dft(tumors_freq) %>%\n  mutate(Outcome=as.factor(Outcome))\nhead(tumors_case)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Dose| TankID|  logDose| logDose2|Outcome |\n|----:|------:|--------:|--------:|:-------|\n| 0.01|      1| -4.60517| 21.20759|Tumor   |\n| 0.01|      1| -4.60517| 21.20759|Tumor   |\n| 0.01|      1| -4.60517| 21.20759|Tumor   |\n| 0.01|      1| -4.60517| 21.20759|Tumor   |\n| 0.01|      1| -4.60517| 21.20759|Tumor   |\n| 0.01|      1| -4.60517| 21.20759|Tumor   |\n\n</div>\n:::\n:::\n\n\n(With most of the lab examples so far oriented around examples of death, discrimination, and disease, you might accuse us statisticians of attempting to usurp from economics the title of \"dismal science\"! (Economists think *they're* pessimists -- what they call \"maximizing utility\", statisticians call \"minimizing loss\"). We promise nobody dies in the next lab. Probably.\n\n## Binary vs binomial \n\nThere are several equivalent ways of fitting a logistic regression model with `glm()` to data such as the `ex2116` data.  We will see why the fitting methods that preserve information about the counts within each tank are preferable for our purposes.\n\n### Modeling a binomial count for each tank\n\nFirst, the response can be specified as a 2-column matrix containing counts of successes in the first column and counts of failures in the second.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- glm(data = tumors, cbind(Tumor, NoTumor) ~ logDose + logDose2, family = \"binomial\")\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = cbind(Tumor, NoTumor) ~ logDose + logDose2, family = \"binomial\", \n    data = tumors)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.02921    0.49343   2.086  0.03699 *  \nlogDose     -1.03048    0.35743  -2.883  0.00394 ** \nlogDose2    -0.39195    0.06136  -6.388 1.68e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 667.195  on 19  degrees of freedom\nResidual deviance:  26.048  on 17  degrees of freedom\nAIC: 119.45\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\nThe response can also be specified as a vector of *proportions* of successes in each group, with the total in each group given through the `weights` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- glm(data = tumors, Tumor/Total ~ logDose + logDose2, weights = Total, family = \"binomial\")\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Tumor/Total ~ logDose + logDose2, family = \"binomial\", \n    data = tumors, weights = Total)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.02921    0.49343   2.086  0.03699 *  \nlogDose     -1.03048    0.35743  -2.883  0.00394 ** \nlogDose2    -0.39195    0.06136  -6.388 1.68e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 667.195  on 19  degrees of freedom\nResidual deviance:  26.048  on 17  degrees of freedom\nAIC: 119.45\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\nBe sure to verify that `mod1` and `mod2` are equivalent.\n\n### Modeling a binary outcome for each fish\n\nWe have converted the data to case format, where each row contains an individual binary outcome corresponding to an individual fish. These outcomes can be modeled directly, just as we saw with the (ungrouped) Donner data in Lab 3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod3 <- glm(data = tumors_case, Outcome ~ logDose + logDose2, family = \"binomial\")\nsummary(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Outcome ~ logDose + logDose2, family = \"binomial\", \n    data = tumors_case)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.02921    0.49341   2.086  0.03698 *  \nlogDose     -1.03048    0.35740  -2.883  0.00394 ** \nlogDose2    -0.39195    0.06135  -6.388 1.68e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2395.8  on 1738  degrees of freedom\nResidual deviance: 1754.7  on 1736  degrees of freedom\nAIC: 1760.7\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\nMake a quick comparison of the coefficient estimates from `mod2` and `mod3`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(coefficients(mod2),coefficients(mod3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  [,1]      [,2]\n(Intercept)  1.0292126  1.029213\nlogDose     -1.0304804 -1.030480\nlogDose2    -0.3919491 -0.391949\n```\n:::\n:::\n\n\nThe two models give the same coefficient estimates, and you can also verify that the corresponding standard errors are the same. Therefore, in terms of inferences about the regression coefficients, treating the data as binary (one 0/1 outcome for each fish) or binomial (one count outcome for each tank) doesn't *seem* to matter. \n\nBut, let's remember that when we looked at the binomial logistic regression model in class, we noticed some over dispersion in the counts. We'll first examine one more approach to modeling the binomial counts, and then turn to talking about the over dispersion.\n\n### Modeling as binomial counts within each Dose\n\nNote that \"TankID\" is not a term in any of the models we fit above.  The binomial logistic models treat the 4 tanks in each of the 5 dose groups as independent binomial observations -- within each `Dose` level, the 4 tanks are supposed to be draws from 4 independent binomial random variables, with potentially different $n$ (different number of fish in each tank) but all with the same $p$.  In the binary logistic model, the tanks are ignored and the fish-level outcomes are treated as independent Bernoulli random variables, with a common $p$ at each `Dose`. In either form, a single $p$ applies to every fish in the `Dose` level, regardless of tank.  Indeed, we can explicitly collapse across the tanks before fitting the model, without affecting any of the inferences:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(summed_tumor <- summarize(group_by(tumors, Dose, logDose, logDose2), sum(Tumor), sum(NoTumor)))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Dose', 'logDose'. You can override using\nthe `.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  Dose|   logDose|  logDose2| sum(Tumor)| sum(NoTumor)|\n|-----:|---------:|---------:|----------:|------------:|\n| 0.010| -4.605170| 21.207592|         25|          322|\n| 0.025| -3.688880| 13.607832|        132|          214|\n| 0.050| -2.995732|  8.974412|        226|          127|\n| 0.100| -2.302585|  5.301898|        281|           74|\n| 0.250| -1.386294|  1.921812|        286|           52|\n\n</div>\n:::\n:::\n\n\nNotice that we've now reduced the dataset down to five observations! And now we'll fit the model to these summed responses:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod4 <- glm(data = summed_tumor, cbind(`sum(Tumor)`, `sum(NoTumor)`) ~ logDose + logDose2, family = \"binomial\")\nsummary(mod4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = cbind(`sum(Tumor)`, `sum(NoTumor)`) ~ logDose + \n    logDose2, family = \"binomial\", data = summed_tumor)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.02921    0.49343   2.086  0.03699 *  \nlogDose     -1.03048    0.35743  -2.883  0.00394 ** \nlogDose2    -0.39195    0.06136  -6.388 1.68e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 641.234089  on 4  degrees of freedom\nResidual deviance:   0.086879  on 2  degrees of freedom\nAIC: 35.091\n\nNumber of Fisher Scoring iterations: 3\n```\n:::\n:::\n\n\nAnd compare coefficient estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(coefficients(mod2),coefficients(mod3),coefficients(mod4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  [,1]      [,2]       [,3]\n(Intercept)  1.0292126  1.029213  1.0292126\nlogDose     -1.0304804 -1.030480 -1.0304804\nlogDose2    -0.3919491 -0.391949 -0.3919491\n```\n:::\n:::\n\n\nAnd once again you can verify that all of the corresponding standard errors are also the same. So what's going on here, and which of these models is \"the best one\" to use?\n\n### Ok, so now what?!\n\nThe parameter estimates and standard errors are all identical -- we reach the same conclusions from each model.  But let's look at the residual deviances for each of the models:\n \n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(deviance(mod2),deviance(mod3),deviance(mod4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         [,1]     [,2]       [,3]\n[1,] 26.04806 1754.692 0.08687945\n```\n:::\n:::\n\n\nIt's also important to recognize that in `mod2`, `mod3` and `mod4`, the sample sizes are n = 20, n = 1739 and n = 5, respectively.  And, the null deviances for each model are also substantially different; again in order of `mod2`, `mod3` and `mod4` these are 667.20, 2395.84 and 641.23. The *difference* in deviance (the deviance accounted for by a model), however, is the same for every form of the model.\n\nTo see more plainly that the methods above are equivalent, we can view minimal summaries from each using the `display()` function from *arm*.  The abbreviated output (compared to `summary`) facilitates comparison between several models on the same page.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# counts in tanks\ndisplay(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglm(formula = Tumor/Total ~ logDose + logDose2, family = \"binomial\", \n    data = tumors, weights = Total)\n            coef.est coef.se\n(Intercept)  1.03     0.49  \nlogDose     -1.03     0.36  \nlogDose2    -0.39     0.06  \n---\n  n = 20, k = 3\n  residual deviance = 26.0, null deviance = 667.2 (difference = 641.1)\n```\n:::\n\n```{.r .cell-code}\n# binary outcomes per fish\ndisplay(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglm(formula = Outcome ~ logDose + logDose2, family = \"binomial\", \n    data = tumors_case)\n            coef.est coef.se\n(Intercept)  1.03     0.49  \nlogDose     -1.03     0.36  \nlogDose2    -0.39     0.06  \n---\n  n = 1739, k = 3\n  residual deviance = 1754.7, null deviance = 2395.8 (difference = 641.1)\n```\n:::\n\n```{.r .cell-code}\n# counts in dose level ignoring tanks\ndisplay(mod4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglm(formula = cbind(`sum(Tumor)`, `sum(NoTumor)`) ~ logDose + \n    logDose2, family = \"binomial\", data = summed_tumor)\n            coef.est coef.se\n(Intercept)  1.03     0.49  \nlogDose     -1.03     0.36  \nlogDose2    -0.39     0.06  \n---\n  n = 5, k = 3\n  residual deviance = 0.1, null deviance = 641.2 (difference = 641.1)\n```\n:::\n:::\n\n\nAll the same assumptions go into each of these ways of fitting the models, and all the same inferences come out.  In particular, we are always assuming that once we know the `Dose` a fish received, knowing the particular *tank* in which that fish was housed cannot give us any more information about that fish's chance of having a tumor -- not even if we know that the fish came from a tank in which an especially large (or small) number of *other* fish got tumors, compared to other tanks within the same dose level.  In the binomial-tank-counts model, this assumption reads like \"every binomial within a dose level has the same $p$.\"  In the binary-fish model, it reads \"every Bernoulli within a dose level has the same $p$.\"  In the binomial-dose-count model, it reads \"the Bernoulli's across all tanks within a dose must be independent.\"  We could call this the assumption of \"irrelevant groups (tanks).\"  \n\nIf we have some grouping at all, however, we often suspect that this last assumption about independence is not sound.  Fish in the same tank are expected to be more similar to one another than fish in different tanks. That is, we should *not* expect same binomial $p$ in every tank, nor should we suppose that all the Bernoulli responses in a dose level are independent, regardless of tank.  \n\nIn what follows, we will see that fitting the model in the \"tank-count\" binomial form, as opposed to per-fish binary form or the dose-count binomial form, is the way that will allow us to *check* whether the group-irrelevance of assumption is reasonable. We'll see that *not* making this assumption comes with a steep price, and preview another technique that will sometimes allow us to avoid paying it.\n\n# Model fit and model comparison\n\nIn the binary logistic case, there was little we could do to directly assess model fit.  You could try squinting at some residual plots, but that's about it.  The single binary outcomes just bounce around too much to say of anything about what the fitted line \"should have done\" at any given predictor value -- it certainly should not chase every individual 1 or 0.  To get some stability, you need to be able to put multiple observations within the same \"bin\", so that you can say whether the proportion (or log-odds) in that bin is close to what the model predicts.  \n\n## Empirical logits\n\nThe empirical logit is just the logit transformation applied to the proportion within a bin (this isn't the log-odds of the *probability* within the bin, it's just an estimate based on the observed proportion -- hence \"empirical\").  \n\nRemember the logit transformation of a proportion/probability is given by `qlogis()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempirical_logits <- with(tumors, qlogis(Tumor/Total))\n```\n:::\n\n\nWe plot the empirical logits against `Dose` to see the shape of the relationship we're trying to capture on the log-odds scale, along with a loess smooth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = tumors, aes(x = Dose, y = empirical_logits))+ \n  geom_jitter(width = 0.005, height = 0.01) + \n  geom_smooth(se = FALSE) +\n  ggtitle(\"Empirical Logits vs Dose\") \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThis appearance of a logarithmic relationship between the Dose and the logits prompts the a log-transformation of the dose to straighten it out (that is, it suggests that the *odds* of tumor are nearly linear in dose).  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = tumors, aes(x = logDose, y = empirical_logits)) + \n  geom_jitter(width = 0.1, height = 0.1) + \n  geom_smooth(se = FALSE) +\n  ggtitle(\"Empirical Logits vs log(Dose)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThis plot suggests that a logistic regression model which includes both `log(Dose)` and `log(Dose)^2` would be appropriate to capture the observed trend in the empirical logits.  Unlike with binary logistic regression, the binomial model lets us measure the lack-of-fit to a proposed model, and compare the fit between models.\n\n## Deviance goodness of fit \n\nRecall that the deviance goodness of fit test compares a fitted model to a saturated model, or one in which there are as many parameters as there are data points. In these goodness of fit comparisons, the null hypothesis corresponds to the fitted model (which is a reduced model relative to the saturated model), and the alternative hypothesis corresponds to the saturated model. Therefore, a small p-value indicating evidence for rejection of the fitted model in favor of the saturated model is evidence of *lack of fit*.\n\nThe `LRstats()` from *vcdExtra* function shows a convenient summary of the fits of one or more model objects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod5 <- glm(data = tumors, (Tumor/Total) ~ Dose, weights = Total, family = \"binomial\")\nmod6 <- glm(data = tumors, (Tumor/Total) ~ logDose, weights = Total, family = \"binomial\")\nmod7 <- glm(data = tumors, (Tumor/Total) ~ logDose + logDose2, weights = Total, family = \"binomial\")\nLRstats(mod5, mod6, mod7)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     |      AIC|      BIC|  LR Chisq| Df| Pr(>Chisq)|\n|:----|--------:|--------:|---------:|--:|----------:|\n|mod5 | 368.4449| 370.4364| 277.04682| 18|  0.0000000|\n|mod6 | 160.2947| 162.2862|  68.89661| 18|  0.0000001|\n|mod7 | 119.4461| 122.4333|  26.04806| 17|  0.0735894|\n\n</div>\n:::\n:::\n\n\nThe `LR Chisq` is the residual deviance, which is the sum of the squared deviance residuals.  For instance, for `mod5`, the residual deviance value of 277 comes can be obtained as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid(mod5, type = 'deviance') %>% raise_to_power(2) %>% sum\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.0468\n```\n:::\n:::\n\nor as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod5$deviance\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.0468\n```\n:::\n:::\n\n\nThis quantity has an approximate chi-squared distribution if the model is correct, which is the basis for the deviance goodness of fit test. `Pr(>Chisq)` provides the p-value for this test.  For `mod6`, let's check that this is equivalent to doing this test \"by hand,\" using the residual deviance and residual df:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npchisq(mod6$deviance, df = mod6$df.residual, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.940025e-08\n```\n:::\n:::\n\n\nEach successive model shows a better fit, as evidenced by the successively larger p-values from the goodness of fit tests. \n\n## Drop-in-deviance test\n\nJust a reminder that the drop in deviance test is different from the deviance goodness of fit test. Whereas the deviance goodness of fit test provides a comparison between a single fitted model and a saturated model, a drop in deviance test provides a way to compare two fitted models when one of those models is nested within the other one. Put another way, the drop in deviance test is a comparison between a reduced model (null hypothesis) and a full model (alternative hypothesis) -- and we use it in cases where the reduced model is reduced from (or nested in) the full model.\n\nUsing the models we have already fit, let's use the `anova()` function to perform a drop in deviance test comparing a reduced model (only `logDose` included) to a full model (`logDose` and `logDose2` included):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod6, mod7,test=\"Chisq\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Resid. Df| Resid. Dev| Df| Deviance| Pr(>Chi)|\n|---------:|----------:|--:|--------:|--------:|\n|        18|   68.89661| NA|       NA|       NA|\n|        17|   26.04806|  1| 42.84856|        0|\n\n</div>\n:::\n:::\n\n\nThe p-value of the drop in deviance test is quite small, p < 0.0001. This provides convincing evidence in favor of the full model; namely, the one that includes `logDose` and `logDose2`.\n\n## Information criteria for model comparison\n\nLet's look at the `LRstats` again, this time with a focus on the first two columns:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLRstats(mod5, mod6,mod7)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     |      AIC|      BIC|  LR Chisq| Df| Pr(>Chisq)|\n|:----|--------:|--------:|---------:|--:|----------:|\n|mod5 | 368.4449| 370.4364| 277.04682| 18|  0.0000000|\n|mod6 | 160.2947| 162.2862|  68.89661| 18|  0.0000001|\n|mod7 | 119.4461| 122.4333|  26.04806| 17|  0.0735894|\n\n</div>\n:::\n:::\n\n\nThe AIC and BIC, as you may recall from Data Analytics I, are likelihood-based methods for comparing models.  Both penalize models with more parameters, but the BIC generally applies a larger penalty (and hence promotes selection of simpler models).  Models with smaller values are preferred.  The AIC or BIC of a single model is not a measure of the goodness of fit for that model -- the information criteria are only meaningful as comparisons between models. The information criteria can be applied to compare models which are not nested (neither model's parameters are a strict subset of the other's), as long as each model has a likelihood. \n\n> Which of these three candidate models would we choose, based on the information criteria?  Does this align with the conclusion from the drop-in-deviance test, given that mod6 is nested within mod7?\n\n## Deviance residuals, Pearson residuals - dispersion parameter estimated from Pearson -- chi squared\n\nIn the case of binomial logistic regression it can be helpful to look at the deviance and/or Pearson residuals to (a) evaluate the model fit and (b) check for outliers. Provided that the binomial counts are fairly large, both the deviance and Pearson residuals should look like draws from a standard Normal distribution, so too many residuals outside of the [-2,2] interval may be cause for concern. Here' we'll look at a few plots of both the deviance and Pearson residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntumors$residuals_deviance <- residuals(mod7)\ntumors$residuals_pearson <- residuals(mod7, type = \"pearson\")\nggplot(data = tumors, aes(logDose,residuals_deviance)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = tumors, aes(logDose,residuals_pearson)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-23-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = tumors, aes(residuals_deviance,residuals_pearson)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-23-3.png){width=672}\n:::\n:::\n\n\nThere are no obvious patterns in either of the plots showing the residuals against `logDose`, and there are also no outliers. This is all good -- it suggests that we've done a good job at modeling the log odds of tumors (although we still have to talk about the over dispersion). We created the scatterplot of the Pearson residuals versus the deviance residuals just so you could see how similar they are -- for the most part, they fall along the y = x diagonal. \n\nWhen looking at residuals, it can also be useful to plot the residuals versus the fitted values of a model. Again, we're hoping that we *don't* see any patterns in such a plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntumors$fitted = predict.glm(mod7,scale=\"link\")\nggplot(data = tumors, aes(fitted,residuals_deviance)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThere are no clear patterns or problems with this plot, so again we have confirmation that we're using a decent model at this point.\n\n# Dealing with over-dispersion\n\nOver dispersion can arise when there is structure in the data that is not accounted for by a model. A high degree of over dispersion may indicate that important predictors have been omitted, the functional form of the predictors is inadequate to capture relevant features of the data, observations assumed independent are not so, or large outliers are present. When there is evidence of lack of fit, we expect overdispersion.  \n\nFrom the residuals of `mod7` that we just examined (`mod7` includes `logDose + logDose2`), it doesn't seem that there are outliers. It also seems that we've gotten a good functional form for the predictors (i.e., `logDose + logDose2`). Is there even evidence of lack of fit here?  We looked at the deviance goodness of fit above, but let's repeat it here just for `mod7`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLRstats(mod7)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     |      AIC|      BIC| LR Chisq| Df| Pr(>Chisq)|\n|:----|--------:|--------:|--------:|--:|----------:|\n|mod7 | 119.4461| 122.4333| 26.04806| 17|  0.0735894|\n\n</div>\n:::\n:::\n\n\nThe p-value is 0.07, which suggests that our model is a good fit, but just barely.  You also saw in the narrated lectures that the estimated dispersion parameter here is 1.48 -- not wildly larger than one, but larger nonetheless.  Even though there may not be strong evidence for over dispersion here, it makes sense that the counts of fish with tumors are over dispersed because it's not likely that measurements on fish from the same tank are statistically independent.\n\n> When in doubt, assume that counts are over dispersed.\n\nYou saw in the narrated lecture that the approach to use in the binomial setting when over dispersion is present is called quasi-binomial logistic regression. We'll perform this in R, and then we'll compare the model output from the quasi-binomial approach to the binomial approach in `mod7`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod8 <- glm(data = tumors, (Tumor/Total) ~ logDose + logDose2, weights = Total, family = \"quasibinomial\")\ndisplay(mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglm(formula = (Tumor/Total) ~ logDose + logDose2, family = \"binomial\", \n    data = tumors, weights = Total)\n            coef.est coef.se\n(Intercept)  1.03     0.49  \nlogDose     -1.03     0.36  \nlogDose2    -0.39     0.06  \n---\n  n = 20, k = 3\n  residual deviance = 26.0, null deviance = 667.2 (difference = 641.1)\n```\n:::\n\n```{.r .cell-code}\ndisplay(mod8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nglm(formula = (Tumor/Total) ~ logDose + logDose2, family = \"quasibinomial\", \n    data = tumors, weights = Total)\n            coef.est coef.se\n(Intercept)  1.03     0.60  \nlogDose     -1.03     0.43  \nlogDose2    -0.39     0.07  \n---\n  n = 20, k = 3\n  residual deviance = 26.0, null deviance = 667.2 (difference = 641.1)\n  overdispersion parameter = 1.5\n```\n:::\n:::\n\n\nThe fundamental change between `mod7` and `mod8` is that the standard errors of the regression coefficients in `mod8`, the quasi-binomial model are larger than they are in `mod7`. This illustrates the problem with ignoring a lack of statistical independence:\n\n> If responses are not statistically independent, but you fit a model that assumes statistical independence, the mistake you often make is that of underestimating standard errors. This results in p-values being smaller than they should be, and confidence intervals being more narrow than they should be.\n\nA strong disadvantage of the quasi-likelihood (in this case quasi-binomial) approach is that since quasi-likelihoods are not real likelihoods, we cannot use likelihood-based methods of model comparison, like AIC and BIC, to choose between them, nor can we compare them with true likelihood models.  Indeed, the idea of \"model comparison\" becomes somewhat muddled when we are talking about a collection of things that are not proper probability models to begin with.\n\nYou'll learn about an alternative to the quasi-binomial model in Module 7 when we introduce mixed effects models. In that Module, we'll refit the tumor data, including `TankID` as a random effect. You might wonder why we can't just include `TankID` in our logistic regression model to address the over dispersion problem. Recall, however, that there are 20 tanks, so that if we use `TankID` in the model, we'll gobble up all 20 data points before we can estimate all the \"tank effects.\" Look at what happens:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod9 <- glm(data = tumors, (Tumor/Total) ~ logDose + logDose2 + TankID, weights = Total, family = \"binomial\")\nsummary(mod9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = (Tumor/Total) ~ logDose + logDose2 + TankID, family = \"binomial\", \n    data = tumors, weights = Total)\n\nCoefficients: (2 not defined because of singularities)\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept)  0.33225    1.28208   0.259  0.79552   \nlogDose     -1.45660    1.00434  -1.450  0.14697   \nlogDose2    -0.43379    0.16314  -2.659  0.00784 **\nTankID2     -0.62553    0.57989  -1.079  0.28073   \nTankID3     -1.61328    0.79714  -2.024  0.04299 * \nTankID4      0.02598    0.49820   0.052  0.95842   \nTankID5     -0.42670    0.39718  -1.074  0.28269   \nTankID6      0.10437    0.39138   0.267  0.78973   \nTankID7     -0.58424    0.40069  -1.458  0.14481   \nTankID8     -0.26517    0.39306  -0.675  0.49991   \nTankID9     -0.36920    0.40678  -0.908  0.36409   \nTankID10    -0.32905    0.40933  -0.804  0.42147   \nTankID11     0.09795    0.41529   0.236  0.81354   \nTankID12    -0.29201    0.40849  -0.715  0.47471   \nTankID13     0.04317    0.37730   0.114  0.90890   \nTankID14     0.13158    0.38163   0.345  0.73027   \nTankID15    -0.34740    0.35820  -0.970  0.33212   \nTankID16          NA         NA      NA       NA   \nTankID17    -0.32395    0.37597  -0.862  0.38888   \nTankID18     0.85371    0.48207   1.771  0.07657 . \nTankID19     0.56157    0.44855   1.252  0.21058   \nTankID20          NA         NA      NA       NA   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 6.6720e+02  on 19  degrees of freedom\nResidual deviance: 6.2617e-14  on  0  degrees of freedom\nAIC: 127.4\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\nThis model is *over-saturated* -- we've put too many terms in it, and not all of them can be estimated. Notice also that the degrees of freedom corresponding to the residual deviance is 0. We should not use this model for inference.\n\n# A Pitfall -- perfect separation\n\nIn this section of the lab, we'll discuss a pathology that can arise in logistic regression. We'll show you what happens, and we'll make a suggestion for dealing with the problem.\n\nFirst, we'll create some fake data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(0,0,0,0,1,1,1,1)\nx1 <-c(1,2,3,3,5,6,10,11)\nx2 <-c(3,2,-1,-1,2,4,1,0)\ndf <- data.frame(y, x1, x2)\ndf\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  y| x1| x2|\n|--:|--:|--:|\n|  0|  1|  3|\n|  0|  2|  2|\n|  0|  3| -1|\n|  0|  3| -1|\n|  1|  5|  2|\n|  1|  6|  4|\n|  1| 10|  1|\n|  1| 11|  0|\n\n</div>\n:::\n:::\n\n\nTake a look at a plot of the data below, and it will be easy to see what the potential problem is -- somewhere between 3 and 5, there's perfect separation between the y = 0 responses and the y = 1 responses. The question is, where is \"somewhere?\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = df, aes(x = x1, y = y)) +\n  geom_point() +\n  ggtitle(\"Note the clean split between 0's and 1's\")\n```\n\n::: {.cell-output-display}\n![](z4_learnR_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\nThe following will not work -- try inserting an \"r\" to make it executable. \n\n```{}\nm1 <- glm(y ~ x1 + x2, family = binomial, data = df)\n```\n \nThis generates an error, because `x1` predicts *too well*. There is no unique \"maximum likelihood estimate\" for the coefficient on `x1`, because there are too many super-excellent solutions, and the numerical algorithm behind the `glm()` function just can't choose. This might seem like the silliest possible problem to have -- that there are *too many* good solutions -- but saying that doesn't make the algorithm converge.\n\nIf we really believe that we can predict `y` perfectly from `x1`, we could throw out the whole model and just write down a decision rule like \"predict y = 1 if x1 >= 4, predict y = 0 otherwise.\" Of course, we don't know if this is a better or worse rule than, say, \"predict y = 1 if x1 >= 3.5, predict y = 0 otherwise\" -- the choice of '4' as the cutpoint was arbitrary.  That is, we might have the same problem that the `glm()` algorithm had -- which cut-point is the best one?! \n\nThe real underlying issue here is that we should not believe that we've derived a perfect classifier (i.e., a decision rule that says when y = 1 and when y = 0) from 8 data points! In fact, in the fake data we created above, we also created a second explanatory variable, `x2`, and we never even used it.\n\nAn alternative approach sidesteps the problem by directly imposing our belief that a perfect classifier is too good to be true, and so it allows for estimating a coefficient on `x1`. This approach, a Bayesian generalized linear model, is well beyond the scope of this course, but you can nevertheless see it in action using the `bayesglm()` function in the *arm* package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes1 <- bayesglm(y ~ x1 + x2, family = binomial, data = df, prior.df = 1)\nsummary(bayes1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nbayesglm(formula = y ~ x1 + x2, family = binomial, data = df, \n    prior.df = 1)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)  -3.6937     1.9372  -1.907   0.0566 .\nx1            0.7055     0.3863   1.826   0.0678 .\nx2            0.3347     0.4448   0.752   0.4518  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 11.0904  on 7  degrees of freedom\nResidual deviance:  2.4855  on 5  degrees of freedom\nAIC: 8.4855\n\nNumber of Fisher Scoring iterations: 57\n```\n:::\n:::\n\n\nYou should still take a careful look at this model summary. In particular there were 46 iterations of the Fisher scoring algorithm -- even with the prior specification about imperfect separation, the algorithm still took a while to find a solution.\n\n# Test for difference in proportions\n\nAnother important application of logistic regression is its use in testing the difference in two proportions. We'll return to the Berkeley Admissions data to take a look.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n (UCBA_sum <- t(margin.table(UCBAdmissions,c(1,2))))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Admit\nGender   Admitted Rejected\n  Male       1198     1493\n  Female      557     1278\n```\n:::\n:::\n\n\nAnd remember that we looked at the equivalence between `prop.test()` and `chisq.test()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(UCBA_sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  UCBA_sum\nX-squared = 91.61, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.1129887 0.1703022\nsample estimates:\n   prop 1    prop 2 \n0.4451877 0.3035422 \n```\n:::\n\n```{.r .cell-code}\nchisq.test(UCBA_sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  UCBA_sum\nX-squared = 91.61, df = 1, p-value < 2.2e-16\n```\n:::\n:::\n\n\nNow let's perform the same test, using logistic regression.\n# Check code: gender should be factor and admit is factor with 0 levels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBA_case <- expand.dft(UCBA_sum)\nUCBA_case %<>% mutate(Gender=factor(Gender), Admit = relevel(factor(Admit),\"Rejected\"))\n  #mutate(Admit = factor(Admit,levels(Admit)[2:1]))\n  # make sure that \"Rejected\" is the failure level in glm\nhead(UCBA_case)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Gender |Admit    |\n|:------|:--------|\n|Male   |Admitted |\n|Male   |Admitted |\n|Male   |Admitted |\n|Male   |Admitted |\n|Male   |Admitted |\n|Male   |Admitted |\n\n</div>\n:::\n\n```{.r .cell-code}\ntest1 <- glm(data = UCBA_case, Admit ~ Gender, family = binomial)\nsummary(test1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Admit ~ Gender, family = binomial, data = UCBA_case)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.83049    0.05077 -16.357   <2e-16 ***\nGenderMale   0.61035    0.06389   9.553   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 6044.3  on 4525  degrees of freedom\nResidual deviance: 5950.9  on 4524  degrees of freedom\nAIC: 5954.9\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\nThe relationship to `prop.test()` may not be immediately clear, and this is partly because the logistic regression output is on then model scale -- in this case the log odds. Take a look at the `z value` corresponding to the `GenderMale` variable. If you take the square of this value, you get 91.26, which is quite similar to the `X squared` value you get from `prop.test()` and from `Chisq.test`. Recall that the square of a standard Normal random variable is a Chi-square random variable, and this helps to explain the similarity.\n\nIf we perform the appropriate back-transformations from the logistic regression output, we'll see the correspondence to the test for a difference in proportions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplogis(-0.83049) #Pr(Admit|Female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3035415\n```\n:::\n\n```{.r .cell-code}\nplogis(-0.83049+0.61035) # Pr(Admit|Male)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4451862\n```\n:::\n:::\n\n\n# Lab 4 Assignment\n\n## Question\n\nHere we will return to the UCBAdmissions dataset and fit a logistic regression model for the count of students admitted (out of the total applicants) for each combination of the factors gender and department.  The usual drill applies -- submit your answers as an RMarkdown document, following the instructions given in the previous labs.\n\n(a) Construct an informative ggplot() of the empirical logits of admission proportion vs gender and department.  It's up to you what aesthetics to map to which variables -- there is more than one right answer here.  \n\nSome tips for part (a):\n\n- You can use the `group` argument to geom_line() to connect points within a group -- for instance, given a plot with Gender on the x axis and a variable called `eLogits` on the y, you could add `geom_line(aes(group = Dept, x = Gender, y = eLogits))`, where the slope of the connecting lines would correspond to the sign and magnitude of the difference in empirical logits (log of observed odds ratio) between genders within each department.  \n\n- You can also incorporate information about the total number of applicants to each department into your plot.  For instance, supposing you had a data frame with separate columns containing counts of \"Admitted\" and \"Rejected\" by sex and department, you could map the number of applicants to the size of the plot points using `geom_point(size = Admitted + Rejected)`. \n\n(b) Based on your plot from (a), which variable (gender or department) appears to account for more of the variability in admissions?  Explain.\n\n(c) Fit an appropriate (binomial) logistic regression model for admissions.  What is the estimated dispersion parameter?  Is there evidence of lack of fit? \n\n(d) Construct a plot of residuals vs fitted values (try just `plot`-ing your fitted model object).  From this plot, can you identify a source for any fit problems encountered in part (c)?\n\n(d) Refit the binomial model above, but excluding the data from department A.  Now what is the estimated dispersion parameter?  Based on the p-value, what would you conclude about the effect of Gender on admissions (to departments other than A) using this model?     \n\n(e) The approach in part (d) allowed us to keep the binomial likelihood model, but only by performing an unprincipled exclusion of some apparently-legitimate data that happened to be \"outlying\".  \n\nTo avoid this, we'll refit the model for all departments with the quasibinomial family.  \n\nUsing the quasibinomial model for all departments, what do you conclude about the effect of Gender on admissions?  Support your conclusion by constructing and interpreting a 95% confidence interval for \n\n$P_{diff} = [P(Admit | (Department, Male)) - P(Admit | (Department, Female))]$ \n\nThat is, construct an interval on the model scale, then backtransform to the data scale.  Be careful with the direction (male higher or female higher) of the observed difference in conditional probability of admission.    \n\n",
    "supporting": [
      "z4_learnR_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}